// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: authority/user.proto

package user_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common_pb "basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	RoleId        uint64                 `protobuf:"varint,6,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_authority_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_authority_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserReq) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *CreateUserReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

var File_authority_user_proto protoreflect.FileDescriptor

const file_authority_user_proto_rawDesc = "" +
	"\n" +
	"\x14authority/user.proto\x12\x14basis.authority.user\x1a\fcommon.proto\"\xa4\x01\n" +
	"\rCreateUserReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x17\n" +
	"\arole_id\x18\x06 \x01(\x04R\x06roleId2\x92\x01\n" +
	"\x04User\x12<\n" +
	"\n" +
	"DeleteUser\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessResp\x12L\n" +
	"\n" +
	"CreateUser\x12#.basis.authority.user.CreateUserReq\x1a\x19.basis.common.SuccessRespB\x19Z\x17types/authority/user_pbb\x06proto3"

var (
	file_authority_user_proto_rawDescOnce sync.Once
	file_authority_user_proto_rawDescData []byte
)

func file_authority_user_proto_rawDescGZIP() []byte {
	file_authority_user_proto_rawDescOnce.Do(func() {
		file_authority_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authority_user_proto_rawDesc), len(file_authority_user_proto_rawDesc)))
	})
	return file_authority_user_proto_rawDescData
}

var file_authority_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authority_user_proto_goTypes = []any{
	(*CreateUserReq)(nil),         // 0: basis.authority.user.CreateUserReq
	(*common_pb.IdReq)(nil),       // 1: basis.common.IdReq
	(*common_pb.SuccessResp)(nil), // 2: basis.common.SuccessResp
}
var file_authority_user_proto_depIdxs = []int32{
	1, // 0: basis.authority.user.User.DeleteUser:input_type -> basis.common.IdReq
	0, // 1: basis.authority.user.User.CreateUser:input_type -> basis.authority.user.CreateUserReq
	2, // 2: basis.authority.user.User.DeleteUser:output_type -> basis.common.SuccessResp
	2, // 3: basis.authority.user.User.CreateUser:output_type -> basis.common.SuccessResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authority_user_proto_init() }
func file_authority_user_proto_init() {
	if File_authority_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authority_user_proto_rawDesc), len(file_authority_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authority_user_proto_goTypes,
		DependencyIndexes: file_authority_user_proto_depIdxs,
		MessageInfos:      file_authority_user_proto_msgTypes,
	}.Build()
	File_authority_user_proto = out.File
	file_authority_user_proto_goTypes = nil
	file_authority_user_proto_depIdxs = nil
}
