// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: authority/user.proto

package user_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	role_pb "td27/rpc/basis/types/authority/role_pb"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Phone         *string                `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Active        *bool                  `protobuf:"varint,5,opt,name=active,proto3,oneof" json:"active,omitempty"`
	DeptId        *uint64                `protobuf:"varint,6,opt,name=dept_id,json=deptId,proto3,oneof" json:"dept_id,omitempty"`
	RoleIds       []uint64               `protobuf:"varint,7,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_authority_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_authority_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserReq) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *CreateUserReq) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *CreateUserReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *CreateUserReq) GetDeptId() uint64 {
	if x != nil && x.DeptId != nil {
		return *x.DeptId
	}
	return 0
}

func (x *CreateUserReq) GetRoleIds() []uint64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	Phone         *string                `protobuf:"bytes,3,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Active        *bool                  `protobuf:"varint,5,opt,name=active,proto3,oneof" json:"active,omitempty"`
	DeptId        *uint64                `protobuf:"varint,6,opt,name=dept_id,json=deptId,proto3,oneof" json:"dept_id,omitempty"`
	RoleIds       []uint64               `protobuf:"varint,7,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_authority_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_authority_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserReq) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateUserReq) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateUserReq) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateUserReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *UpdateUserReq) GetDeptId() uint64 {
	if x != nil && x.DeptId != nil {
		return *x.DeptId
	}
	return 0
}

func (x *UpdateUserReq) GetRoleIds() []uint64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type UserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	DeptId        uint64                 `protobuf:"varint,6,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	Roles         []*role_pb.RoleResp    `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResp) Reset() {
	*x = UserResp{}
	mi := &file_authority_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResp) ProtoMessage() {}

func (x *UserResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResp.ProtoReflect.Descriptor instead.
func (*UserResp) Descriptor() ([]byte, []int) {
	return file_authority_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserResp) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserResp) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UserResp) GetDeptId() uint64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *UserResp) GetRoles() []*role_pb.RoleResp {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserResp) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserResp            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserResp) Reset() {
	*x = ListUserResp{}
	mi := &file_authority_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserResp) ProtoMessage() {}

func (x *ListUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserResp.ProtoReflect.Descriptor instead.
func (*ListUserResp) Descriptor() ([]byte, []int) {
	return file_authority_user_proto_rawDescGZIP(), []int{3}
}

func (x *ListUserResp) GetList() []*UserResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListUserResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ModifyPasswdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyPasswdReq) Reset() {
	*x = ModifyPasswdReq{}
	mi := &file_authority_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyPasswdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPasswdReq) ProtoMessage() {}

func (x *ModifyPasswdReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPasswdReq.ProtoReflect.Descriptor instead.
func (*ModifyPasswdReq) Descriptor() ([]byte, []int) {
	return file_authority_user_proto_rawDescGZIP(), []int{4}
}

func (x *ModifyPasswdReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModifyPasswdReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ModifyPasswdReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type SwitchActiveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Active        bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchActiveReq) Reset() {
	*x = SwitchActiveReq{}
	mi := &file_authority_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchActiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchActiveReq) ProtoMessage() {}

func (x *SwitchActiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchActiveReq.ProtoReflect.Descriptor instead.
func (*SwitchActiveReq) Descriptor() ([]byte, []int) {
	return file_authority_user_proto_rawDescGZIP(), []int{5}
}

func (x *SwitchActiveReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SwitchActiveReq) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type AssignRolesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleIds       []uint64               `protobuf:"varint,2,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRolesReq) Reset() {
	*x = AssignRolesReq{}
	mi := &file_authority_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolesReq) ProtoMessage() {}

func (x *AssignRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolesReq.ProtoReflect.Descriptor instead.
func (*AssignRolesReq) Descriptor() ([]byte, []int) {
	return file_authority_user_proto_rawDescGZIP(), []int{6}
}

func (x *AssignRolesReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AssignRolesReq) GetRoleIds() []uint64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_authority_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_authority_user_proto_rawDescGZIP(), []int{7}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *UserResp              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_authority_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_authority_user_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResp) GetUser() *UserResp {
	if x != nil {
		return x.User
	}
	return nil
}

var File_authority_user_proto protoreflect.FileDescriptor

const file_authority_user_proto_rawDesc = "" +
	"\n" +
	"\x14authority/user.proto\x12\x14basis.authority.user\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14authority/role.proto\"\xfe\x01\n" +
	"\rCreateUserReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\x05phone\x18\x03 \x01(\tH\x00R\x05phone\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x01R\x05email\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x05 \x01(\bH\x02R\x06active\x88\x01\x01\x12\x1c\n" +
	"\adept_id\x18\x06 \x01(\x04H\x03R\x06deptId\x88\x01\x01\x12\x19\n" +
	"\brole_ids\x18\a \x03(\x04R\aroleIdsB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_emailB\t\n" +
	"\a_activeB\n" +
	"\n" +
	"\b_dept_id\"\x84\x02\n" +
	"\rUpdateUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x03 \x01(\tH\x01R\x05phone\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x02R\x05email\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x05 \x01(\bH\x03R\x06active\x88\x01\x01\x12\x1c\n" +
	"\adept_id\x18\x06 \x01(\x04H\x04R\x06deptId\x88\x01\x01\x12\x19\n" +
	"\brole_ids\x18\a \x03(\x04R\aroleIdsB\v\n" +
	"\t_usernameB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_emailB\t\n" +
	"\a_activeB\n" +
	"\n" +
	"\b_dept_id\"\xbf\x02\n" +
	"\bUserResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12\x17\n" +
	"\adept_id\x18\x06 \x01(\x04R\x06deptId\x124\n" +
	"\x05roles\x18\a \x03(\v2\x1e.basis.authority.role.RoleRespR\x05roles\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"X\n" +
	"\fListUserResp\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.basis.authority.user.UserRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"g\n" +
	"\x0fModifyPasswdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"9\n" +
	"\x0fSwitchActiveReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\"D\n" +
	"\x0eAssignRolesReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\x04R\aroleIds\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"U\n" +
	"\tLoginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x122\n" +
	"\x04user\x18\x02 \x01(\v2\x1e.basis.authority.user.UserRespR\x04user2\xb4\x05\n" +
	"\x04User\x12H\n" +
	"\x05Login\x12\x1e.basis.authority.user.LoginReq\x1a\x1f.basis.authority.user.LoginResp\x12B\n" +
	"\vGetUserInfo\x12\x13.basis.common.IdReq\x1a\x1e.basis.authority.user.UserResp\x12E\n" +
	"\bListUser\x12\x15.basis.common.PageReq\x1a\".basis.authority.user.ListUserResp\x12<\n" +
	"\n" +
	"DeleteUser\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessResp\x12L\n" +
	"\n" +
	"CreateUser\x12#.basis.authority.user.CreateUserReq\x1a\x19.basis.common.SuccessResp\x12Q\n" +
	"\n" +
	"UpdateUser\x12#.basis.authority.user.UpdateUserReq\x1a\x1e.basis.authority.user.UserResp\x12R\n" +
	"\x0eModifyPassword\x12%.basis.authority.user.ModifyPasswdReq\x1a\x19.basis.common.SuccessResp\x12T\n" +
	"\x10SwitchUserActive\x12%.basis.authority.user.SwitchActiveReq\x1a\x19.basis.common.SuccessResp\x12N\n" +
	"\vAssignRoles\x12$.basis.authority.user.AssignRolesReq\x1a\x19.basis.common.SuccessRespB0Z.td27/rpc/basis/types/authority/user_pb;user_pbb\x06proto3"

var (
	file_authority_user_proto_rawDescOnce sync.Once
	file_authority_user_proto_rawDescData []byte
)

func file_authority_user_proto_rawDescGZIP() []byte {
	file_authority_user_proto_rawDescOnce.Do(func() {
		file_authority_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authority_user_proto_rawDesc), len(file_authority_user_proto_rawDesc)))
	})
	return file_authority_user_proto_rawDescData
}

var file_authority_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_authority_user_proto_goTypes = []any{
	(*CreateUserReq)(nil),         // 0: basis.authority.user.CreateUserReq
	(*UpdateUserReq)(nil),         // 1: basis.authority.user.UpdateUserReq
	(*UserResp)(nil),              // 2: basis.authority.user.UserResp
	(*ListUserResp)(nil),          // 3: basis.authority.user.ListUserResp
	(*ModifyPasswdReq)(nil),       // 4: basis.authority.user.ModifyPasswdReq
	(*SwitchActiveReq)(nil),       // 5: basis.authority.user.SwitchActiveReq
	(*AssignRolesReq)(nil),        // 6: basis.authority.user.AssignRolesReq
	(*LoginReq)(nil),              // 7: basis.authority.user.LoginReq
	(*LoginResp)(nil),             // 8: basis.authority.user.LoginResp
	(*role_pb.RoleResp)(nil),      // 9: basis.authority.role.RoleResp
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*common_pb.IdReq)(nil),       // 11: basis.common.IdReq
	(*common_pb.PageReq)(nil),     // 12: basis.common.PageReq
	(*common_pb.SuccessResp)(nil), // 13: basis.common.SuccessResp
}
var file_authority_user_proto_depIdxs = []int32{
	9,  // 0: basis.authority.user.UserResp.roles:type_name -> basis.authority.role.RoleResp
	10, // 1: basis.authority.user.UserResp.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: basis.authority.user.UserResp.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: basis.authority.user.ListUserResp.list:type_name -> basis.authority.user.UserResp
	2,  // 4: basis.authority.user.LoginResp.user:type_name -> basis.authority.user.UserResp
	7,  // 5: basis.authority.user.User.Login:input_type -> basis.authority.user.LoginReq
	11, // 6: basis.authority.user.User.GetUserInfo:input_type -> basis.common.IdReq
	12, // 7: basis.authority.user.User.ListUser:input_type -> basis.common.PageReq
	11, // 8: basis.authority.user.User.DeleteUser:input_type -> basis.common.IdReq
	0,  // 9: basis.authority.user.User.CreateUser:input_type -> basis.authority.user.CreateUserReq
	1,  // 10: basis.authority.user.User.UpdateUser:input_type -> basis.authority.user.UpdateUserReq
	4,  // 11: basis.authority.user.User.ModifyPassword:input_type -> basis.authority.user.ModifyPasswdReq
	5,  // 12: basis.authority.user.User.SwitchUserActive:input_type -> basis.authority.user.SwitchActiveReq
	6,  // 13: basis.authority.user.User.AssignRoles:input_type -> basis.authority.user.AssignRolesReq
	8,  // 14: basis.authority.user.User.Login:output_type -> basis.authority.user.LoginResp
	2,  // 15: basis.authority.user.User.GetUserInfo:output_type -> basis.authority.user.UserResp
	3,  // 16: basis.authority.user.User.ListUser:output_type -> basis.authority.user.ListUserResp
	13, // 17: basis.authority.user.User.DeleteUser:output_type -> basis.common.SuccessResp
	13, // 18: basis.authority.user.User.CreateUser:output_type -> basis.common.SuccessResp
	2,  // 19: basis.authority.user.User.UpdateUser:output_type -> basis.authority.user.UserResp
	13, // 20: basis.authority.user.User.ModifyPassword:output_type -> basis.common.SuccessResp
	13, // 21: basis.authority.user.User.SwitchUserActive:output_type -> basis.common.SuccessResp
	13, // 22: basis.authority.user.User.AssignRoles:output_type -> basis.common.SuccessResp
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_authority_user_proto_init() }
func file_authority_user_proto_init() {
	if File_authority_user_proto != nil {
		return
	}
	file_authority_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_authority_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authority_user_proto_rawDesc), len(file_authority_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authority_user_proto_goTypes,
		DependencyIndexes: file_authority_user_proto_depIdxs,
		MessageInfos:      file_authority_user_proto_msgTypes,
	}.Build()
	File_authority_user_proto = out.File
	file_authority_user_proto_goTypes = nil
	file_authority_user_proto_depIdxs = nil
}
