syntax = "proto3";

import "common/common.proto";
import "google/protobuf/timestamp.proto";

package basis.authority.button;

option go_package = "td27/rpc/basis/types/authority/button_pb;button_pb";

message CreateButtonReq {
  string button_code = 1;
  string button_name = 2;
  optional string description = 3;
  string page_path = 4;
}

message UpdateButtonReq {
  uint64 id = 1;
  optional string button_code = 2;
  optional string button_name = 3;
  optional string description = 4;
  optional string page_path = 5;
}

message ButtonResp {
  uint64 id = 1;
  string button_code = 2;
  string button_name = 3;
  string description = 4;
  string page_path = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}

message ListButtonResp {
  repeated ButtonResp list = 1;
  int64 total = 2;
}

message GetButtonsByPagePathReq {
  string page_path = 1;
}

message GetUserButtonsReq {
  repeated uint64 role_ids = 1;
}

service Button {
  rpc GetButton(basis.common.IdReq) returns (ButtonResp);
  rpc ListButton(basis.common.PageReq) returns (ListButtonResp);
  rpc GetButtonsByPagePath(GetButtonsByPagePathReq) returns (ListButtonResp);
  rpc GetUserButtons(GetUserButtonsReq) returns (ListButtonResp);
  rpc CreateButton(CreateButtonReq) returns (basis.common.SuccessResp);
  rpc UpdateButton(UpdateButtonReq) returns (ButtonResp);
  rpc DeleteButton(basis.common.IdReq) returns (basis.common.SuccessResp);
}
