syntax = "proto3";

import "common/common.proto";
import "google/protobuf/timestamp.proto";

package basis.authority.dept;

option go_package = "td27/rpc/basis/types/authority/dept_pb;dept_pb";

message CreateDeptReq {
  string dept_name = 1;
  optional uint64 parent_id = 2;
  optional uint32 sort = 3;
  optional bool status = 4;
}

message UpdateDeptReq {
  uint64 id = 1;
  optional string dept_name = 2;
  optional uint64 parent_id = 3;
  optional uint32 sort = 4;
  optional bool status = 5;
}

message DeptResp {
  uint64 id = 1;
  string dept_name = 2;
  uint64 parent_id = 3;
  string path = 4;
  uint32 level = 5;
  uint32 sort = 6;
  bool status = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
}

message DeptTreeResp {
  DeptResp dept = 1;
  repeated DeptTreeResp children = 2;
}

message GetDeptTreeResp {
  repeated DeptTreeResp tree = 1;
}

message GetDeptDescendantsReq {
  uint64 dept_id = 1;
}

service Dept {
  rpc GetDept(basis.common.IdReq) returns (DeptResp);
  rpc GetDeptTree(basis.common.Empty) returns (GetDeptTreeResp);
  rpc GetDeptDescendants(GetDeptDescendantsReq) returns (GetDeptTreeResp);
  rpc CreateDept(CreateDeptReq) returns (basis.common.SuccessResp);
  rpc UpdateDept(UpdateDeptReq) returns (DeptResp);
  rpc DeleteDept(basis.common.IdReq) returns (basis.common.SuccessResp);
}
