syntax = "proto3";

import "common/common.proto";
import "google/protobuf/timestamp.proto";

package basis.authority.menu;

option go_package = "td27/rpc/basis/types/authority/menu_pb;menu_pb";

message CreateMenuReq {
  string menu_name = 1;
  optional string icon = 2;
  string path = 3;
  optional string component = 4;
  optional string redirect = 5;
  optional uint64 parent_id = 6;
  optional uint32 sort = 7;
  optional bool hidden = 8;
  optional bool keep_alive = 9;
  optional bool affix = 10;
  optional bool always_show = 11;
  string title = 12;
}

message UpdateMenuReq {
  uint64 id = 1;
  optional string menu_name = 2;
  optional string icon = 3;
  optional string path = 4;
  optional string component = 5;
  optional string redirect = 6;
  optional uint64 parent_id = 7;
  optional uint32 sort = 8;
  optional bool hidden = 9;
  optional bool keep_alive = 10;
  optional bool affix = 11;
  optional bool always_show = 12;
  optional string title = 13;
}

message MenuResp {
  uint64 id = 1;
  string menu_name = 2;
  string icon = 3;
  string path = 4;
  string component = 5;
  string redirect = 6;
  uint64 parent_id = 7;
  uint32 sort = 8;
  bool hidden = 9;
  bool keep_alive = 10;
  bool affix = 11;
  bool always_show = 12;
  string title = 13;
  google.protobuf.Timestamp created_at = 14;
  google.protobuf.Timestamp updated_at = 15;
}

message MenuTreeResp {
  MenuResp menu = 1;
  repeated MenuTreeResp children = 2;
}

message GetMenuTreeResp {
  repeated MenuTreeResp tree = 1;
}

message GetUserMenusReq {
  repeated uint64 role_ids = 1;
}

service Menu {
  rpc GetMenu(basis.common.IdReq) returns (MenuResp);
  rpc GetMenuTree(basis.common.Empty) returns (GetMenuTreeResp);
  rpc GetUserMenus(GetUserMenusReq) returns (GetMenuTreeResp);
  rpc CreateMenu(CreateMenuReq) returns (basis.common.SuccessResp);
  rpc UpdateMenu(UpdateMenuReq) returns (MenuResp);
  rpc DeleteMenu(basis.common.IdReq) returns (basis.common.SuccessResp);
}
