syntax = "proto3";

import "common/common.proto";
import "google/protobuf/timestamp.proto";

package basis.authority.role;

option go_package = "td27/rpc/basis/types/authority/role_pb;role_pb";

message CreateRoleReq {
  string role_name = 1;
  optional uint64 parent_id = 2;
}

message UpdateRoleReq {
  uint64 id = 1;
  optional string role_name = 2;
  optional uint64 parent_id = 3;
}

message RoleResp {
  uint64 id = 1;
  string role_name = 2;
  optional uint64 parent_id = 3;
  google.protobuf.Timestamp created_at = 4;
  google.protobuf.Timestamp updated_at = 5;
}

message RoleTreeResp {
  RoleResp role = 1;
  repeated RoleTreeResp children = 2;
}

message ListRoleResp {
  repeated RoleResp list = 1;
  int64 total = 2;
}

message AssignPermissionsReq {
  uint64 role_id = 1;
  repeated uint64 permission_ids = 2;
}

message GetRolePermissionsResp {
  repeated uint64 permission_ids = 1;
}

service Role {
  rpc GetRole(basis.common.IdReq) returns (RoleResp);
  rpc GetRoleWithChildren(basis.common.IdReq) returns (RoleTreeResp);
  rpc ListRole(basis.common.PageReq) returns (ListRoleResp);
  rpc GetAllRoles(basis.common.Empty) returns (ListRoleResp);
  rpc CreateRole(CreateRoleReq) returns (basis.common.SuccessResp);
  rpc UpdateRole(UpdateRoleReq) returns (RoleResp);
  rpc DeleteRole(basis.common.IdReq) returns (basis.common.SuccessResp);
  rpc AssignPermissions(AssignPermissionsReq) returns (basis.common.SuccessResp);
  rpc GetRolePermissions(basis.common.IdReq) returns (GetRolePermissionsResp);
}