// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: authority/role.proto

package role_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	ParentId      *uint64                `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReq) Reset() {
	*x = CreateRoleReq{}
	mi := &file_authority_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReq) ProtoMessage() {}

func (x *CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReq.ProtoReflect.Descriptor instead.
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_authority_role_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoleReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *CreateRoleReq) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

type UpdateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName      *string                `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3,oneof" json:"role_name,omitempty"`
	ParentId      *uint64                `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	mi := &file_authority_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_authority_role_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRoleReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleReq) GetRoleName() string {
	if x != nil && x.RoleName != nil {
		return *x.RoleName
	}
	return ""
}

func (x *UpdateRoleReq) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

type RoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	ParentId      *uint64                `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResp) Reset() {
	*x = RoleResp{}
	mi := &file_authority_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResp) ProtoMessage() {}

func (x *RoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResp.ProtoReflect.Descriptor instead.
func (*RoleResp) Descriptor() ([]byte, []int) {
	return file_authority_role_proto_rawDescGZIP(), []int{2}
}

func (x *RoleResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleResp) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleResp) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *RoleResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoleResp) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RoleTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleResp              `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Children      []*RoleTreeResp        `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleTreeResp) Reset() {
	*x = RoleTreeResp{}
	mi := &file_authority_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleTreeResp) ProtoMessage() {}

func (x *RoleTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleTreeResp.ProtoReflect.Descriptor instead.
func (*RoleTreeResp) Descriptor() ([]byte, []int) {
	return file_authority_role_proto_rawDescGZIP(), []int{3}
}

func (x *RoleTreeResp) GetRole() *RoleResp {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *RoleTreeResp) GetChildren() []*RoleTreeResp {
	if x != nil {
		return x.Children
	}
	return nil
}

type ListRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RoleResp            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleResp) Reset() {
	*x = ListRoleResp{}
	mi := &file_authority_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleResp) ProtoMessage() {}

func (x *ListRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleResp.ProtoReflect.Descriptor instead.
func (*ListRoleResp) Descriptor() ([]byte, []int) {
	return file_authority_role_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoleResp) GetList() []*RoleResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListRoleResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AssignPermissionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        uint64                 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionIds []uint64               `protobuf:"varint,2,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionsReq) Reset() {
	*x = AssignPermissionsReq{}
	mi := &file_authority_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionsReq) ProtoMessage() {}

func (x *AssignPermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionsReq.ProtoReflect.Descriptor instead.
func (*AssignPermissionsReq) Descriptor() ([]byte, []int) {
	return file_authority_role_proto_rawDescGZIP(), []int{5}
}

func (x *AssignPermissionsReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AssignPermissionsReq) GetPermissionIds() []uint64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

type GetRolePermissionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionIds []uint64               `protobuf:"varint,1,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsResp) Reset() {
	*x = GetRolePermissionsResp{}
	mi := &file_authority_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsResp) ProtoMessage() {}

func (x *GetRolePermissionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsResp.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsResp) Descriptor() ([]byte, []int) {
	return file_authority_role_proto_rawDescGZIP(), []int{6}
}

func (x *GetRolePermissionsResp) GetPermissionIds() []uint64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

var File_authority_role_proto protoreflect.FileDescriptor

const file_authority_role_proto_rawDesc = "" +
	"\n" +
	"\x14authority/role.proto\x12\x14basis.authority.role\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n" +
	"\rCreateRoleReq\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12 \n" +
	"\tparent_id\x18\x02 \x01(\x04H\x00R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_id\"\x7f\n" +
	"\rUpdateRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12 \n" +
	"\trole_name\x18\x02 \x01(\tH\x00R\broleName\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x03 \x01(\x04H\x01R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_role_nameB\f\n" +
	"\n" +
	"_parent_id\"\xdd\x01\n" +
	"\bRoleResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12 \n" +
	"\tparent_id\x18\x03 \x01(\x04H\x00R\bparentId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\f\n" +
	"\n" +
	"_parent_id\"\x82\x01\n" +
	"\fRoleTreeResp\x122\n" +
	"\x04role\x18\x01 \x01(\v2\x1e.basis.authority.role.RoleRespR\x04role\x12>\n" +
	"\bchildren\x18\x02 \x03(\v2\".basis.authority.role.RoleTreeRespR\bchildren\"X\n" +
	"\fListRoleResp\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.basis.authority.role.RoleRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"V\n" +
	"\x14AssignPermissionsReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x04R\x06roleId\x12%\n" +
	"\x0epermission_ids\x18\x02 \x03(\x04R\rpermissionIds\"?\n" +
	"\x16GetRolePermissionsResp\x12%\n" +
	"\x0epermission_ids\x18\x01 \x03(\x04R\rpermissionIds2\xb9\x05\n" +
	"\x04Role\x12>\n" +
	"\aGetRole\x12\x13.basis.common.IdReq\x1a\x1e.basis.authority.role.RoleResp\x12N\n" +
	"\x13GetRoleWithChildren\x12\x13.basis.common.IdReq\x1a\".basis.authority.role.RoleTreeResp\x12E\n" +
	"\bListRole\x12\x15.basis.common.PageReq\x1a\".basis.authority.role.ListRoleResp\x12F\n" +
	"\vGetAllRoles\x12\x13.basis.common.Empty\x1a\".basis.authority.role.ListRoleResp\x12L\n" +
	"\n" +
	"CreateRole\x12#.basis.authority.role.CreateRoleReq\x1a\x19.basis.common.SuccessResp\x12Q\n" +
	"\n" +
	"UpdateRole\x12#.basis.authority.role.UpdateRoleReq\x1a\x1e.basis.authority.role.RoleResp\x12<\n" +
	"\n" +
	"DeleteRole\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessResp\x12Z\n" +
	"\x11AssignPermissions\x12*.basis.authority.role.AssignPermissionsReq\x1a\x19.basis.common.SuccessResp\x12W\n" +
	"\x12GetRolePermissions\x12\x13.basis.common.IdReq\x1a,.basis.authority.role.GetRolePermissionsRespB0Z.td27/rpc/basis/types/authority/role_pb;role_pbb\x06proto3"

var (
	file_authority_role_proto_rawDescOnce sync.Once
	file_authority_role_proto_rawDescData []byte
)

func file_authority_role_proto_rawDescGZIP() []byte {
	file_authority_role_proto_rawDescOnce.Do(func() {
		file_authority_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authority_role_proto_rawDesc), len(file_authority_role_proto_rawDesc)))
	})
	return file_authority_role_proto_rawDescData
}

var file_authority_role_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_authority_role_proto_goTypes = []any{
	(*CreateRoleReq)(nil),          // 0: basis.authority.role.CreateRoleReq
	(*UpdateRoleReq)(nil),          // 1: basis.authority.role.UpdateRoleReq
	(*RoleResp)(nil),               // 2: basis.authority.role.RoleResp
	(*RoleTreeResp)(nil),           // 3: basis.authority.role.RoleTreeResp
	(*ListRoleResp)(nil),           // 4: basis.authority.role.ListRoleResp
	(*AssignPermissionsReq)(nil),   // 5: basis.authority.role.AssignPermissionsReq
	(*GetRolePermissionsResp)(nil), // 6: basis.authority.role.GetRolePermissionsResp
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
	(*common_pb.IdReq)(nil),        // 8: basis.common.IdReq
	(*common_pb.PageReq)(nil),      // 9: basis.common.PageReq
	(*common_pb.Empty)(nil),        // 10: basis.common.Empty
	(*common_pb.SuccessResp)(nil),  // 11: basis.common.SuccessResp
}
var file_authority_role_proto_depIdxs = []int32{
	7,  // 0: basis.authority.role.RoleResp.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: basis.authority.role.RoleResp.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: basis.authority.role.RoleTreeResp.role:type_name -> basis.authority.role.RoleResp
	3,  // 3: basis.authority.role.RoleTreeResp.children:type_name -> basis.authority.role.RoleTreeResp
	2,  // 4: basis.authority.role.ListRoleResp.list:type_name -> basis.authority.role.RoleResp
	8,  // 5: basis.authority.role.Role.GetRole:input_type -> basis.common.IdReq
	8,  // 6: basis.authority.role.Role.GetRoleWithChildren:input_type -> basis.common.IdReq
	9,  // 7: basis.authority.role.Role.ListRole:input_type -> basis.common.PageReq
	10, // 8: basis.authority.role.Role.GetAllRoles:input_type -> basis.common.Empty
	0,  // 9: basis.authority.role.Role.CreateRole:input_type -> basis.authority.role.CreateRoleReq
	1,  // 10: basis.authority.role.Role.UpdateRole:input_type -> basis.authority.role.UpdateRoleReq
	8,  // 11: basis.authority.role.Role.DeleteRole:input_type -> basis.common.IdReq
	5,  // 12: basis.authority.role.Role.AssignPermissions:input_type -> basis.authority.role.AssignPermissionsReq
	8,  // 13: basis.authority.role.Role.GetRolePermissions:input_type -> basis.common.IdReq
	2,  // 14: basis.authority.role.Role.GetRole:output_type -> basis.authority.role.RoleResp
	3,  // 15: basis.authority.role.Role.GetRoleWithChildren:output_type -> basis.authority.role.RoleTreeResp
	4,  // 16: basis.authority.role.Role.ListRole:output_type -> basis.authority.role.ListRoleResp
	4,  // 17: basis.authority.role.Role.GetAllRoles:output_type -> basis.authority.role.ListRoleResp
	11, // 18: basis.authority.role.Role.CreateRole:output_type -> basis.common.SuccessResp
	2,  // 19: basis.authority.role.Role.UpdateRole:output_type -> basis.authority.role.RoleResp
	11, // 20: basis.authority.role.Role.DeleteRole:output_type -> basis.common.SuccessResp
	11, // 21: basis.authority.role.Role.AssignPermissions:output_type -> basis.common.SuccessResp
	6,  // 22: basis.authority.role.Role.GetRolePermissions:output_type -> basis.authority.role.GetRolePermissionsResp
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_authority_role_proto_init() }
func file_authority_role_proto_init() {
	if File_authority_role_proto != nil {
		return
	}
	file_authority_role_proto_msgTypes[0].OneofWrappers = []any{}
	file_authority_role_proto_msgTypes[1].OneofWrappers = []any{}
	file_authority_role_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authority_role_proto_rawDesc), len(file_authority_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authority_role_proto_goTypes,
		DependencyIndexes: file_authority_role_proto_depIdxs,
		MessageInfos:      file_authority_role_proto_msgTypes,
	}.Build()
	File_authority_role_proto = out.File
	file_authority_role_proto_goTypes = nil
	file_authority_role_proto_depIdxs = nil
}
