// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: sysManagement/menu.proto

package menu_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMenuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuName      string                 `protobuf:"bytes,1,opt,name=menu_name,json=menuName,proto3" json:"menu_name,omitempty"`
	Icon          *string                `protobuf:"bytes,2,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Component     *string                `protobuf:"bytes,4,opt,name=component,proto3,oneof" json:"component,omitempty"`
	Redirect      *string                `protobuf:"bytes,5,opt,name=redirect,proto3,oneof" json:"redirect,omitempty"`
	ParentId      *int64                 `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Sort          *uint32                `protobuf:"varint,7,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Hidden        *bool                  `protobuf:"varint,8,opt,name=hidden,proto3,oneof" json:"hidden,omitempty"`
	KeepAlive     *bool                  `protobuf:"varint,9,opt,name=keep_alive,json=keepAlive,proto3,oneof" json:"keep_alive,omitempty"`
	Affix         *bool                  `protobuf:"varint,10,opt,name=affix,proto3,oneof" json:"affix,omitempty"`
	AlwaysShow    *bool                  `protobuf:"varint,11,opt,name=always_show,json=alwaysShow,proto3,oneof" json:"always_show,omitempty"`
	Title         string                 `protobuf:"bytes,12,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuReq) Reset() {
	*x = CreateMenuReq{}
	mi := &file_sysManagement_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuReq) ProtoMessage() {}

func (x *CreateMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuReq.ProtoReflect.Descriptor instead.
func (*CreateMenuReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_menu_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMenuReq) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *CreateMenuReq) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *CreateMenuReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateMenuReq) GetComponent() string {
	if x != nil && x.Component != nil {
		return *x.Component
	}
	return ""
}

func (x *CreateMenuReq) GetRedirect() string {
	if x != nil && x.Redirect != nil {
		return *x.Redirect
	}
	return ""
}

func (x *CreateMenuReq) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *CreateMenuReq) GetSort() uint32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *CreateMenuReq) GetHidden() bool {
	if x != nil && x.Hidden != nil {
		return *x.Hidden
	}
	return false
}

func (x *CreateMenuReq) GetKeepAlive() bool {
	if x != nil && x.KeepAlive != nil {
		return *x.KeepAlive
	}
	return false
}

func (x *CreateMenuReq) GetAffix() bool {
	if x != nil && x.Affix != nil {
		return *x.Affix
	}
	return false
}

func (x *CreateMenuReq) GetAlwaysShow() bool {
	if x != nil && x.AlwaysShow != nil {
		return *x.AlwaysShow
	}
	return false
}

func (x *CreateMenuReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateMenuReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MenuName      *string                `protobuf:"bytes,2,opt,name=menu_name,json=menuName,proto3,oneof" json:"menu_name,omitempty"`
	Icon          *string                `protobuf:"bytes,3,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Path          *string                `protobuf:"bytes,4,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Component     *string                `protobuf:"bytes,5,opt,name=component,proto3,oneof" json:"component,omitempty"`
	Redirect      *string                `protobuf:"bytes,6,opt,name=redirect,proto3,oneof" json:"redirect,omitempty"`
	ParentId      *int64                 `protobuf:"varint,7,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Sort          *uint32                `protobuf:"varint,8,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Hidden        *bool                  `protobuf:"varint,9,opt,name=hidden,proto3,oneof" json:"hidden,omitempty"`
	KeepAlive     *bool                  `protobuf:"varint,10,opt,name=keep_alive,json=keepAlive,proto3,oneof" json:"keep_alive,omitempty"`
	Affix         *bool                  `protobuf:"varint,11,opt,name=affix,proto3,oneof" json:"affix,omitempty"`
	AlwaysShow    *bool                  `protobuf:"varint,12,opt,name=always_show,json=alwaysShow,proto3,oneof" json:"always_show,omitempty"`
	Title         *string                `protobuf:"bytes,13,opt,name=title,proto3,oneof" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuReq) Reset() {
	*x = UpdateMenuReq{}
	mi := &file_sysManagement_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuReq) ProtoMessage() {}

func (x *UpdateMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuReq.ProtoReflect.Descriptor instead.
func (*UpdateMenuReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_menu_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMenuReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMenuReq) GetMenuName() string {
	if x != nil && x.MenuName != nil {
		return *x.MenuName
	}
	return ""
}

func (x *UpdateMenuReq) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *UpdateMenuReq) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *UpdateMenuReq) GetComponent() string {
	if x != nil && x.Component != nil {
		return *x.Component
	}
	return ""
}

func (x *UpdateMenuReq) GetRedirect() string {
	if x != nil && x.Redirect != nil {
		return *x.Redirect
	}
	return ""
}

func (x *UpdateMenuReq) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *UpdateMenuReq) GetSort() uint32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *UpdateMenuReq) GetHidden() bool {
	if x != nil && x.Hidden != nil {
		return *x.Hidden
	}
	return false
}

func (x *UpdateMenuReq) GetKeepAlive() bool {
	if x != nil && x.KeepAlive != nil {
		return *x.KeepAlive
	}
	return false
}

func (x *UpdateMenuReq) GetAffix() bool {
	if x != nil && x.Affix != nil {
		return *x.Affix
	}
	return false
}

func (x *UpdateMenuReq) GetAlwaysShow() bool {
	if x != nil && x.AlwaysShow != nil {
		return *x.AlwaysShow
	}
	return false
}

func (x *UpdateMenuReq) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

type MenuResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MenuName      string                 `protobuf:"bytes,2,opt,name=menu_name,json=menuName,proto3" json:"menu_name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Component     string                 `protobuf:"bytes,5,opt,name=component,proto3" json:"component,omitempty"`
	Redirect      string                 `protobuf:"bytes,6,opt,name=redirect,proto3" json:"redirect,omitempty"`
	ParentId      int64                  `protobuf:"varint,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Sort          uint32                 `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Hidden        bool                   `protobuf:"varint,9,opt,name=hidden,proto3" json:"hidden,omitempty"`
	KeepAlive     bool                   `protobuf:"varint,10,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	Affix         bool                   `protobuf:"varint,11,opt,name=affix,proto3" json:"affix,omitempty"`
	AlwaysShow    bool                   `protobuf:"varint,12,opt,name=always_show,json=alwaysShow,proto3" json:"always_show,omitempty"`
	Title         string                 `protobuf:"bytes,13,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuResp) Reset() {
	*x = MenuResp{}
	mi := &file_sysManagement_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuResp) ProtoMessage() {}

func (x *MenuResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuResp.ProtoReflect.Descriptor instead.
func (*MenuResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_menu_proto_rawDescGZIP(), []int{2}
}

func (x *MenuResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MenuResp) GetMenuName() string {
	if x != nil {
		return x.MenuName
	}
	return ""
}

func (x *MenuResp) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MenuResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MenuResp) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *MenuResp) GetRedirect() string {
	if x != nil {
		return x.Redirect
	}
	return ""
}

func (x *MenuResp) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *MenuResp) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *MenuResp) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *MenuResp) GetKeepAlive() bool {
	if x != nil {
		return x.KeepAlive
	}
	return false
}

func (x *MenuResp) GetAffix() bool {
	if x != nil {
		return x.Affix
	}
	return false
}

func (x *MenuResp) GetAlwaysShow() bool {
	if x != nil {
		return x.AlwaysShow
	}
	return false
}

func (x *MenuResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MenuResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MenuResp) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type MenuTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Menu          *MenuResp              `protobuf:"bytes,1,opt,name=menu,proto3" json:"menu,omitempty"`
	Children      []*MenuTreeResp        `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuTreeResp) Reset() {
	*x = MenuTreeResp{}
	mi := &file_sysManagement_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuTreeResp) ProtoMessage() {}

func (x *MenuTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuTreeResp.ProtoReflect.Descriptor instead.
func (*MenuTreeResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_menu_proto_rawDescGZIP(), []int{3}
}

func (x *MenuTreeResp) GetMenu() *MenuResp {
	if x != nil {
		return x.Menu
	}
	return nil
}

func (x *MenuTreeResp) GetChildren() []*MenuTreeResp {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetMenuTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          []*MenuTreeResp        `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuTreeResp) Reset() {
	*x = GetMenuTreeResp{}
	mi := &file_sysManagement_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuTreeResp) ProtoMessage() {}

func (x *GetMenuTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuTreeResp.ProtoReflect.Descriptor instead.
func (*GetMenuTreeResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_menu_proto_rawDescGZIP(), []int{4}
}

func (x *GetMenuTreeResp) GetTree() []*MenuTreeResp {
	if x != nil {
		return x.Tree
	}
	return nil
}

type GetUserMenusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleIds       []int64                `protobuf:"varint,1,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserMenusReq) Reset() {
	*x = GetUserMenusReq{}
	mi := &file_sysManagement_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserMenusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMenusReq) ProtoMessage() {}

func (x *GetUserMenusReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMenusReq.ProtoReflect.Descriptor instead.
func (*GetUserMenusReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_menu_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserMenusReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type ListMenuResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MenuResp            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuResp) Reset() {
	*x = ListMenuResp{}
	mi := &file_sysManagement_menu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuResp) ProtoMessage() {}

func (x *ListMenuResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_menu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuResp.ProtoReflect.Descriptor instead.
func (*ListMenuResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_menu_proto_rawDescGZIP(), []int{6}
}

func (x *ListMenuResp) GetList() []*MenuResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListMenuResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_sysManagement_menu_proto protoreflect.FileDescriptor

const file_sysManagement_menu_proto_rawDesc = "" +
	"\n" +
	"\x18sysManagement/menu.proto\x12\x18basis.sysManagement.menu\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x03\n" +
	"\rCreateMenuReq\x12\x1b\n" +
	"\tmenu_name\x18\x01 \x01(\tR\bmenuName\x12\x17\n" +
	"\x04icon\x18\x02 \x01(\tH\x00R\x04icon\x88\x01\x01\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12!\n" +
	"\tcomponent\x18\x04 \x01(\tH\x01R\tcomponent\x88\x01\x01\x12\x1f\n" +
	"\bredirect\x18\x05 \x01(\tH\x02R\bredirect\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x06 \x01(\x03H\x03R\bparentId\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\a \x01(\rH\x04R\x04sort\x88\x01\x01\x12\x1b\n" +
	"\x06hidden\x18\b \x01(\bH\x05R\x06hidden\x88\x01\x01\x12\"\n" +
	"\n" +
	"keep_alive\x18\t \x01(\bH\x06R\tkeepAlive\x88\x01\x01\x12\x19\n" +
	"\x05affix\x18\n" +
	" \x01(\bH\aR\x05affix\x88\x01\x01\x12$\n" +
	"\valways_show\x18\v \x01(\bH\bR\n" +
	"alwaysShow\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\f \x01(\tR\x05titleB\a\n" +
	"\x05_iconB\f\n" +
	"\n" +
	"_componentB\v\n" +
	"\t_redirectB\f\n" +
	"\n" +
	"_parent_idB\a\n" +
	"\x05_sortB\t\n" +
	"\a_hiddenB\r\n" +
	"\v_keep_aliveB\b\n" +
	"\x06_affixB\x0e\n" +
	"\f_always_show\"\x9f\x04\n" +
	"\rUpdateMenuReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\tmenu_name\x18\x02 \x01(\tH\x00R\bmenuName\x88\x01\x01\x12\x17\n" +
	"\x04icon\x18\x03 \x01(\tH\x01R\x04icon\x88\x01\x01\x12\x17\n" +
	"\x04path\x18\x04 \x01(\tH\x02R\x04path\x88\x01\x01\x12!\n" +
	"\tcomponent\x18\x05 \x01(\tH\x03R\tcomponent\x88\x01\x01\x12\x1f\n" +
	"\bredirect\x18\x06 \x01(\tH\x04R\bredirect\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\a \x01(\x03H\x05R\bparentId\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\b \x01(\rH\x06R\x04sort\x88\x01\x01\x12\x1b\n" +
	"\x06hidden\x18\t \x01(\bH\aR\x06hidden\x88\x01\x01\x12\"\n" +
	"\n" +
	"keep_alive\x18\n" +
	" \x01(\bH\bR\tkeepAlive\x88\x01\x01\x12\x19\n" +
	"\x05affix\x18\v \x01(\bH\tR\x05affix\x88\x01\x01\x12$\n" +
	"\valways_show\x18\f \x01(\bH\n" +
	"R\n" +
	"alwaysShow\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\r \x01(\tH\vR\x05title\x88\x01\x01B\f\n" +
	"\n" +
	"_menu_nameB\a\n" +
	"\x05_iconB\a\n" +
	"\x05_pathB\f\n" +
	"\n" +
	"_componentB\v\n" +
	"\t_redirectB\f\n" +
	"\n" +
	"_parent_idB\a\n" +
	"\x05_sortB\t\n" +
	"\a_hiddenB\r\n" +
	"\v_keep_aliveB\b\n" +
	"\x06_affixB\x0e\n" +
	"\f_always_showB\b\n" +
	"\x06_title\"\xc4\x03\n" +
	"\bMenuResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tmenu_name\x18\x02 \x01(\tR\bmenuName\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1c\n" +
	"\tcomponent\x18\x05 \x01(\tR\tcomponent\x12\x1a\n" +
	"\bredirect\x18\x06 \x01(\tR\bredirect\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\x03R\bparentId\x12\x12\n" +
	"\x04sort\x18\b \x01(\rR\x04sort\x12\x16\n" +
	"\x06hidden\x18\t \x01(\bR\x06hidden\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\n" +
	" \x01(\bR\tkeepAlive\x12\x14\n" +
	"\x05affix\x18\v \x01(\bR\x05affix\x12\x1f\n" +
	"\valways_show\x18\f \x01(\bR\n" +
	"alwaysShow\x12\x14\n" +
	"\x05title\x18\r \x01(\tR\x05title\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8a\x01\n" +
	"\fMenuTreeResp\x126\n" +
	"\x04menu\x18\x01 \x01(\v2\".basis.sysManagement.menu.MenuRespR\x04menu\x12B\n" +
	"\bchildren\x18\x02 \x03(\v2&.basis.sysManagement.menu.MenuTreeRespR\bchildren\"M\n" +
	"\x0fGetMenuTreeResp\x12:\n" +
	"\x04tree\x18\x01 \x03(\v2&.basis.sysManagement.menu.MenuTreeRespR\x04tree\",\n" +
	"\x0fGetUserMenusReq\x12\x19\n" +
	"\brole_ids\x18\x01 \x03(\x03R\aroleIds\"\\\n" +
	"\fListMenuResp\x126\n" +
	"\x04list\x18\x01 \x03(\v2\".basis.sysManagement.menu.MenuRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xb5\x04\n" +
	"\x04Menu\x12B\n" +
	"\aGetMenu\x12\x13.basis.common.IdReq\x1a\".basis.sysManagement.menu.MenuResp\x12I\n" +
	"\bListMenu\x12\x15.basis.common.PageReq\x1a&.basis.sysManagement.menu.ListMenuResp\x12M\n" +
	"\vGetMenuTree\x12\x13.basis.common.Empty\x1a).basis.sysManagement.menu.GetMenuTreeResp\x12d\n" +
	"\fGetUserMenus\x12).basis.sysManagement.menu.GetUserMenusReq\x1a).basis.sysManagement.menu.GetMenuTreeResp\x12P\n" +
	"\n" +
	"CreateMenu\x12'.basis.sysManagement.menu.CreateMenuReq\x1a\x19.basis.common.SuccessResp\x12Y\n" +
	"\n" +
	"UpdateMenu\x12'.basis.sysManagement.menu.UpdateMenuReq\x1a\".basis.sysManagement.menu.MenuResp\x12<\n" +
	"\n" +
	"DeleteMenu\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessRespB4Z2td27/rpc/basis/types/sysManagement/menu_pb;menu_pbb\x06proto3"

var (
	file_sysManagement_menu_proto_rawDescOnce sync.Once
	file_sysManagement_menu_proto_rawDescData []byte
)

func file_sysManagement_menu_proto_rawDescGZIP() []byte {
	file_sysManagement_menu_proto_rawDescOnce.Do(func() {
		file_sysManagement_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysManagement_menu_proto_rawDesc), len(file_sysManagement_menu_proto_rawDesc)))
	})
	return file_sysManagement_menu_proto_rawDescData
}

var file_sysManagement_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sysManagement_menu_proto_goTypes = []any{
	(*CreateMenuReq)(nil),         // 0: basis.sysManagement.menu.CreateMenuReq
	(*UpdateMenuReq)(nil),         // 1: basis.sysManagement.menu.UpdateMenuReq
	(*MenuResp)(nil),              // 2: basis.sysManagement.menu.MenuResp
	(*MenuTreeResp)(nil),          // 3: basis.sysManagement.menu.MenuTreeResp
	(*GetMenuTreeResp)(nil),       // 4: basis.sysManagement.menu.GetMenuTreeResp
	(*GetUserMenusReq)(nil),       // 5: basis.sysManagement.menu.GetUserMenusReq
	(*ListMenuResp)(nil),          // 6: basis.sysManagement.menu.ListMenuResp
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*common_pb.IdReq)(nil),       // 8: basis.common.IdReq
	(*common_pb.PageReq)(nil),     // 9: basis.common.PageReq
	(*common_pb.Empty)(nil),       // 10: basis.common.Empty
	(*common_pb.SuccessResp)(nil), // 11: basis.common.SuccessResp
}
var file_sysManagement_menu_proto_depIdxs = []int32{
	7,  // 0: basis.sysManagement.menu.MenuResp.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: basis.sysManagement.menu.MenuResp.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: basis.sysManagement.menu.MenuTreeResp.menu:type_name -> basis.sysManagement.menu.MenuResp
	3,  // 3: basis.sysManagement.menu.MenuTreeResp.children:type_name -> basis.sysManagement.menu.MenuTreeResp
	3,  // 4: basis.sysManagement.menu.GetMenuTreeResp.tree:type_name -> basis.sysManagement.menu.MenuTreeResp
	2,  // 5: basis.sysManagement.menu.ListMenuResp.list:type_name -> basis.sysManagement.menu.MenuResp
	8,  // 6: basis.sysManagement.menu.Menu.GetMenu:input_type -> basis.common.IdReq
	9,  // 7: basis.sysManagement.menu.Menu.ListMenu:input_type -> basis.common.PageReq
	10, // 8: basis.sysManagement.menu.Menu.GetMenuTree:input_type -> basis.common.Empty
	5,  // 9: basis.sysManagement.menu.Menu.GetUserMenus:input_type -> basis.sysManagement.menu.GetUserMenusReq
	0,  // 10: basis.sysManagement.menu.Menu.CreateMenu:input_type -> basis.sysManagement.menu.CreateMenuReq
	1,  // 11: basis.sysManagement.menu.Menu.UpdateMenu:input_type -> basis.sysManagement.menu.UpdateMenuReq
	8,  // 12: basis.sysManagement.menu.Menu.DeleteMenu:input_type -> basis.common.IdReq
	2,  // 13: basis.sysManagement.menu.Menu.GetMenu:output_type -> basis.sysManagement.menu.MenuResp
	6,  // 14: basis.sysManagement.menu.Menu.ListMenu:output_type -> basis.sysManagement.menu.ListMenuResp
	4,  // 15: basis.sysManagement.menu.Menu.GetMenuTree:output_type -> basis.sysManagement.menu.GetMenuTreeResp
	4,  // 16: basis.sysManagement.menu.Menu.GetUserMenus:output_type -> basis.sysManagement.menu.GetMenuTreeResp
	11, // 17: basis.sysManagement.menu.Menu.CreateMenu:output_type -> basis.common.SuccessResp
	2,  // 18: basis.sysManagement.menu.Menu.UpdateMenu:output_type -> basis.sysManagement.menu.MenuResp
	11, // 19: basis.sysManagement.menu.Menu.DeleteMenu:output_type -> basis.common.SuccessResp
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_sysManagement_menu_proto_init() }
func file_sysManagement_menu_proto_init() {
	if File_sysManagement_menu_proto != nil {
		return
	}
	file_sysManagement_menu_proto_msgTypes[0].OneofWrappers = []any{}
	file_sysManagement_menu_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysManagement_menu_proto_rawDesc), len(file_sysManagement_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysManagement_menu_proto_goTypes,
		DependencyIndexes: file_sysManagement_menu_proto_depIdxs,
		MessageInfos:      file_sysManagement_menu_proto_msgTypes,
	}.Build()
	File_sysManagement_menu_proto = out.File
	file_sysManagement_menu_proto_goTypes = nil
	file_sysManagement_menu_proto_depIdxs = nil
}
