// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: basis.proto

package basisclient

import (
	"context"

	"basis/basis"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = basis.Request
	Response = basis.Response

	Basis interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultBasis struct {
		cli zrpc.Client
	}
)

func NewBasis(cli zrpc.Client) Basis {
	return &defaultBasis{
		cli: cli,
	}
}

func (m *defaultBasis) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := basis.NewBasisClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
