// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: authority/dept.proto

package dept_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common_pb "td27/rpc/basis/types/common_pb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dept_GetDept_FullMethodName            = "/basis.authority.dept.Dept/GetDept"
	Dept_GetDeptTree_FullMethodName        = "/basis.authority.dept.Dept/GetDeptTree"
	Dept_GetDeptDescendants_FullMethodName = "/basis.authority.dept.Dept/GetDeptDescendants"
	Dept_CreateDept_FullMethodName         = "/basis.authority.dept.Dept/CreateDept"
	Dept_UpdateDept_FullMethodName         = "/basis.authority.dept.Dept/UpdateDept"
	Dept_DeleteDept_FullMethodName         = "/basis.authority.dept.Dept/DeleteDept"
)

// DeptClient is the client API for Dept service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeptClient interface {
	GetDept(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*DeptResp, error)
	GetDeptTree(ctx context.Context, in *common_pb.Empty, opts ...grpc.CallOption) (*GetDeptTreeResp, error)
	GetDeptDescendants(ctx context.Context, in *GetDeptDescendantsReq, opts ...grpc.CallOption) (*GetDeptTreeResp, error)
	CreateDept(ctx context.Context, in *CreateDeptReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
	UpdateDept(ctx context.Context, in *UpdateDeptReq, opts ...grpc.CallOption) (*DeptResp, error)
	DeleteDept(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
}

type deptClient struct {
	cc grpc.ClientConnInterface
}

func NewDeptClient(cc grpc.ClientConnInterface) DeptClient {
	return &deptClient{cc}
}

func (c *deptClient) GetDept(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*DeptResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeptResp)
	err := c.cc.Invoke(ctx, Dept_GetDept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deptClient) GetDeptTree(ctx context.Context, in *common_pb.Empty, opts ...grpc.CallOption) (*GetDeptTreeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeptTreeResp)
	err := c.cc.Invoke(ctx, Dept_GetDeptTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deptClient) GetDeptDescendants(ctx context.Context, in *GetDeptDescendantsReq, opts ...grpc.CallOption) (*GetDeptTreeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeptTreeResp)
	err := c.cc.Invoke(ctx, Dept_GetDeptDescendants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deptClient) CreateDept(ctx context.Context, in *CreateDeptReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Dept_CreateDept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deptClient) UpdateDept(ctx context.Context, in *UpdateDeptReq, opts ...grpc.CallOption) (*DeptResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeptResp)
	err := c.cc.Invoke(ctx, Dept_UpdateDept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deptClient) DeleteDept(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Dept_DeleteDept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeptServer is the server API for Dept service.
// All implementations must embed UnimplementedDeptServer
// for forward compatibility.
type DeptServer interface {
	GetDept(context.Context, *common_pb.IdReq) (*DeptResp, error)
	GetDeptTree(context.Context, *common_pb.Empty) (*GetDeptTreeResp, error)
	GetDeptDescendants(context.Context, *GetDeptDescendantsReq) (*GetDeptTreeResp, error)
	CreateDept(context.Context, *CreateDeptReq) (*common_pb.SuccessResp, error)
	UpdateDept(context.Context, *UpdateDeptReq) (*DeptResp, error)
	DeleteDept(context.Context, *common_pb.IdReq) (*common_pb.SuccessResp, error)
	mustEmbedUnimplementedDeptServer()
}

// UnimplementedDeptServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeptServer struct{}

func (UnimplementedDeptServer) GetDept(context.Context, *common_pb.IdReq) (*DeptResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDept not implemented")
}
func (UnimplementedDeptServer) GetDeptTree(context.Context, *common_pb.Empty) (*GetDeptTreeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeptTree not implemented")
}
func (UnimplementedDeptServer) GetDeptDescendants(context.Context, *GetDeptDescendantsReq) (*GetDeptTreeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeptDescendants not implemented")
}
func (UnimplementedDeptServer) CreateDept(context.Context, *CreateDeptReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDept not implemented")
}
func (UnimplementedDeptServer) UpdateDept(context.Context, *UpdateDeptReq) (*DeptResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDept not implemented")
}
func (UnimplementedDeptServer) DeleteDept(context.Context, *common_pb.IdReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDept not implemented")
}
func (UnimplementedDeptServer) mustEmbedUnimplementedDeptServer() {}
func (UnimplementedDeptServer) testEmbeddedByValue()              {}

// UnsafeDeptServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeptServer will
// result in compilation errors.
type UnsafeDeptServer interface {
	mustEmbedUnimplementedDeptServer()
}

func RegisterDeptServer(s grpc.ServiceRegistrar, srv DeptServer) {
	// If the following call pancis, it indicates UnimplementedDeptServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dept_ServiceDesc, srv)
}

func _Dept_GetDept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeptServer).GetDept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dept_GetDept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeptServer).GetDept(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dept_GetDeptTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeptServer).GetDeptTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dept_GetDeptTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeptServer).GetDeptTree(ctx, req.(*common_pb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dept_GetDeptDescendants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeptDescendantsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeptServer).GetDeptDescendants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dept_GetDeptDescendants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeptServer).GetDeptDescendants(ctx, req.(*GetDeptDescendantsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dept_CreateDept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeptServer).CreateDept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dept_CreateDept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeptServer).CreateDept(ctx, req.(*CreateDeptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dept_UpdateDept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeptReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeptServer).UpdateDept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dept_UpdateDept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeptServer).UpdateDept(ctx, req.(*UpdateDeptReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dept_DeleteDept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeptServer).DeleteDept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dept_DeleteDept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeptServer).DeleteDept(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Dept_ServiceDesc is the grpc.ServiceDesc for Dept service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dept_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basis.authority.dept.Dept",
	HandlerType: (*DeptServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDept",
			Handler:    _Dept_GetDept_Handler,
		},
		{
			MethodName: "GetDeptTree",
			Handler:    _Dept_GetDeptTree_Handler,
		},
		{
			MethodName: "GetDeptDescendants",
			Handler:    _Dept_GetDeptDescendants_Handler,
		},
		{
			MethodName: "CreateDept",
			Handler:    _Dept_CreateDept_Handler,
		},
		{
			MethodName: "UpdateDept",
			Handler:    _Dept_UpdateDept_Handler,
		},
		{
			MethodName: "DeleteDept",
			Handler:    _Dept_DeleteDept_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authority/dept.proto",
}
