// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: authority/dept.proto

package dept_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDeptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeptName      string                 `protobuf:"bytes,1,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	ParentId      *uint64                `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Sort          *uint32                `protobuf:"varint,3,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Status        *bool                  `protobuf:"varint,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeptReq) Reset() {
	*x = CreateDeptReq{}
	mi := &file_authority_dept_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeptReq) ProtoMessage() {}

func (x *CreateDeptReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dept_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeptReq.ProtoReflect.Descriptor instead.
func (*CreateDeptReq) Descriptor() ([]byte, []int) {
	return file_authority_dept_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDeptReq) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *CreateDeptReq) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *CreateDeptReq) GetSort() uint32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *CreateDeptReq) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

type UpdateDeptReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeptName      *string                `protobuf:"bytes,2,opt,name=dept_name,json=deptName,proto3,oneof" json:"dept_name,omitempty"`
	ParentId      *uint64                `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Sort          *uint32                `protobuf:"varint,4,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Status        *bool                  `protobuf:"varint,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeptReq) Reset() {
	*x = UpdateDeptReq{}
	mi := &file_authority_dept_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeptReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeptReq) ProtoMessage() {}

func (x *UpdateDeptReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dept_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeptReq.ProtoReflect.Descriptor instead.
func (*UpdateDeptReq) Descriptor() ([]byte, []int) {
	return file_authority_dept_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDeptReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDeptReq) GetDeptName() string {
	if x != nil && x.DeptName != nil {
		return *x.DeptName
	}
	return ""
}

func (x *UpdateDeptReq) GetParentId() uint64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *UpdateDeptReq) GetSort() uint32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *UpdateDeptReq) GetStatus() bool {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return false
}

type DeptResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeptName      string                 `protobuf:"bytes,2,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	ParentId      uint64                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Level         uint32                 `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Sort          uint32                 `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        bool                   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptResp) Reset() {
	*x = DeptResp{}
	mi := &file_authority_dept_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptResp) ProtoMessage() {}

func (x *DeptResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dept_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptResp.ProtoReflect.Descriptor instead.
func (*DeptResp) Descriptor() ([]byte, []int) {
	return file_authority_dept_proto_rawDescGZIP(), []int{2}
}

func (x *DeptResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeptResp) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *DeptResp) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *DeptResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeptResp) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *DeptResp) GetSort() uint32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *DeptResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DeptResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeptResp) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DeptTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dept          *DeptResp              `protobuf:"bytes,1,opt,name=dept,proto3" json:"dept,omitempty"`
	Children      []*DeptTreeResp        `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeptTreeResp) Reset() {
	*x = DeptTreeResp{}
	mi := &file_authority_dept_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeptTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeptTreeResp) ProtoMessage() {}

func (x *DeptTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dept_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeptTreeResp.ProtoReflect.Descriptor instead.
func (*DeptTreeResp) Descriptor() ([]byte, []int) {
	return file_authority_dept_proto_rawDescGZIP(), []int{3}
}

func (x *DeptTreeResp) GetDept() *DeptResp {
	if x != nil {
		return x.Dept
	}
	return nil
}

func (x *DeptTreeResp) GetChildren() []*DeptTreeResp {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetDeptTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          []*DeptTreeResp        `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeptTreeResp) Reset() {
	*x = GetDeptTreeResp{}
	mi := &file_authority_dept_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeptTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeptTreeResp) ProtoMessage() {}

func (x *GetDeptTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dept_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeptTreeResp.ProtoReflect.Descriptor instead.
func (*GetDeptTreeResp) Descriptor() ([]byte, []int) {
	return file_authority_dept_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeptTreeResp) GetTree() []*DeptTreeResp {
	if x != nil {
		return x.Tree
	}
	return nil
}

type GetDeptDescendantsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeptId        uint64                 `protobuf:"varint,1,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeptDescendantsReq) Reset() {
	*x = GetDeptDescendantsReq{}
	mi := &file_authority_dept_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeptDescendantsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeptDescendantsReq) ProtoMessage() {}

func (x *GetDeptDescendantsReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dept_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeptDescendantsReq.ProtoReflect.Descriptor instead.
func (*GetDeptDescendantsReq) Descriptor() ([]byte, []int) {
	return file_authority_dept_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeptDescendantsReq) GetDeptId() uint64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

var File_authority_dept_proto protoreflect.FileDescriptor

const file_authority_dept_proto_rawDesc = "" +
	"\n" +
	"\x14authority/dept.proto\x12\x14basis.authority.dept\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x01\n" +
	"\rCreateDeptReq\x12\x1b\n" +
	"\tdept_name\x18\x01 \x01(\tR\bdeptName\x12 \n" +
	"\tparent_id\x18\x02 \x01(\x04H\x00R\bparentId\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x03 \x01(\rH\x01R\x04sort\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\bH\x02R\x06status\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\a\n" +
	"\x05_sortB\t\n" +
	"\a_status\"\xc9\x01\n" +
	"\rUpdateDeptReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12 \n" +
	"\tdept_name\x18\x02 \x01(\tH\x00R\bdeptName\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x03 \x01(\x04H\x01R\bparentId\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x04 \x01(\rH\x02R\x04sort\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\bH\x03R\x06status\x88\x01\x01B\f\n" +
	"\n" +
	"_dept_nameB\f\n" +
	"\n" +
	"_parent_idB\a\n" +
	"\x05_sortB\t\n" +
	"\a_status\"\xa0\x02\n" +
	"\bDeptResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tdept_name\x18\x02 \x01(\tR\bdeptName\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x04R\bparentId\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x14\n" +
	"\x05level\x18\x05 \x01(\rR\x05level\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\rR\x04sort\x12\x16\n" +
	"\x06status\x18\a \x01(\bR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x82\x01\n" +
	"\fDeptTreeResp\x122\n" +
	"\x04dept\x18\x01 \x01(\v2\x1e.basis.authority.dept.DeptRespR\x04dept\x12>\n" +
	"\bchildren\x18\x02 \x03(\v2\".basis.authority.dept.DeptTreeRespR\bchildren\"I\n" +
	"\x0fGetDeptTreeResp\x126\n" +
	"\x04tree\x18\x01 \x03(\v2\".basis.authority.dept.DeptTreeRespR\x04tree\"0\n" +
	"\x15GetDeptDescendantsReq\x12\x17\n" +
	"\adept_id\x18\x01 \x01(\x04R\x06deptId2\xda\x03\n" +
	"\x04Dept\x12>\n" +
	"\aGetDept\x12\x13.basis.common.IdReq\x1a\x1e.basis.authority.dept.DeptResp\x12I\n" +
	"\vGetDeptTree\x12\x13.basis.common.Empty\x1a%.basis.authority.dept.GetDeptTreeResp\x12h\n" +
	"\x12GetDeptDescendants\x12+.basis.authority.dept.GetDeptDescendantsReq\x1a%.basis.authority.dept.GetDeptTreeResp\x12L\n" +
	"\n" +
	"CreateDept\x12#.basis.authority.dept.CreateDeptReq\x1a\x19.basis.common.SuccessResp\x12Q\n" +
	"\n" +
	"UpdateDept\x12#.basis.authority.dept.UpdateDeptReq\x1a\x1e.basis.authority.dept.DeptResp\x12<\n" +
	"\n" +
	"DeleteDept\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessRespB0Z.td27/rpc/basis/types/authority/dept_pb;dept_pbb\x06proto3"

var (
	file_authority_dept_proto_rawDescOnce sync.Once
	file_authority_dept_proto_rawDescData []byte
)

func file_authority_dept_proto_rawDescGZIP() []byte {
	file_authority_dept_proto_rawDescOnce.Do(func() {
		file_authority_dept_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authority_dept_proto_rawDesc), len(file_authority_dept_proto_rawDesc)))
	})
	return file_authority_dept_proto_rawDescData
}

var file_authority_dept_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_authority_dept_proto_goTypes = []any{
	(*CreateDeptReq)(nil),         // 0: basis.authority.dept.CreateDeptReq
	(*UpdateDeptReq)(nil),         // 1: basis.authority.dept.UpdateDeptReq
	(*DeptResp)(nil),              // 2: basis.authority.dept.DeptResp
	(*DeptTreeResp)(nil),          // 3: basis.authority.dept.DeptTreeResp
	(*GetDeptTreeResp)(nil),       // 4: basis.authority.dept.GetDeptTreeResp
	(*GetDeptDescendantsReq)(nil), // 5: basis.authority.dept.GetDeptDescendantsReq
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*common_pb.IdReq)(nil),       // 7: basis.common.IdReq
	(*common_pb.Empty)(nil),       // 8: basis.common.Empty
	(*common_pb.SuccessResp)(nil), // 9: basis.common.SuccessResp
}
var file_authority_dept_proto_depIdxs = []int32{
	6,  // 0: basis.authority.dept.DeptResp.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: basis.authority.dept.DeptResp.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: basis.authority.dept.DeptTreeResp.dept:type_name -> basis.authority.dept.DeptResp
	3,  // 3: basis.authority.dept.DeptTreeResp.children:type_name -> basis.authority.dept.DeptTreeResp
	3,  // 4: basis.authority.dept.GetDeptTreeResp.tree:type_name -> basis.authority.dept.DeptTreeResp
	7,  // 5: basis.authority.dept.Dept.GetDept:input_type -> basis.common.IdReq
	8,  // 6: basis.authority.dept.Dept.GetDeptTree:input_type -> basis.common.Empty
	5,  // 7: basis.authority.dept.Dept.GetDeptDescendants:input_type -> basis.authority.dept.GetDeptDescendantsReq
	0,  // 8: basis.authority.dept.Dept.CreateDept:input_type -> basis.authority.dept.CreateDeptReq
	1,  // 9: basis.authority.dept.Dept.UpdateDept:input_type -> basis.authority.dept.UpdateDeptReq
	7,  // 10: basis.authority.dept.Dept.DeleteDept:input_type -> basis.common.IdReq
	2,  // 11: basis.authority.dept.Dept.GetDept:output_type -> basis.authority.dept.DeptResp
	4,  // 12: basis.authority.dept.Dept.GetDeptTree:output_type -> basis.authority.dept.GetDeptTreeResp
	4,  // 13: basis.authority.dept.Dept.GetDeptDescendants:output_type -> basis.authority.dept.GetDeptTreeResp
	9,  // 14: basis.authority.dept.Dept.CreateDept:output_type -> basis.common.SuccessResp
	2,  // 15: basis.authority.dept.Dept.UpdateDept:output_type -> basis.authority.dept.DeptResp
	9,  // 16: basis.authority.dept.Dept.DeleteDept:output_type -> basis.common.SuccessResp
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_authority_dept_proto_init() }
func file_authority_dept_proto_init() {
	if File_authority_dept_proto != nil {
		return
	}
	file_authority_dept_proto_msgTypes[0].OneofWrappers = []any{}
	file_authority_dept_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authority_dept_proto_rawDesc), len(file_authority_dept_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authority_dept_proto_goTypes,
		DependencyIndexes: file_authority_dept_proto_depIdxs,
		MessageInfos:      file_authority_dept_proto_msgTypes,
	}.Build()
	File_authority_dept_proto = out.File
	file_authority_dept_proto_goTypes = nil
	file_authority_dept_proto_depIdxs = nil
}
