// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: sysTool/cache.proto

package cache_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCacheReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheReq) Reset() {
	*x = GetCacheReq{}
	mi := &file_sysTool_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheReq) ProtoMessage() {}

func (x *GetCacheReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysTool_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheReq.ProtoReflect.Descriptor instead.
func (*GetCacheReq) Descriptor() ([]byte, []int) {
	return file_sysTool_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GetCacheReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetCacheResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCacheResp) Reset() {
	*x = GetCacheResp{}
	mi := &file_sysTool_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCacheResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheResp) ProtoMessage() {}

func (x *GetCacheResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysTool_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheResp.ProtoReflect.Descriptor instead.
func (*GetCacheResp) Descriptor() ([]byte, []int) {
	return file_sysTool_cache_proto_rawDescGZIP(), []int{1}
}

func (x *GetCacheResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetCacheResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetCacheResp) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type SetCacheReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCacheReq) Reset() {
	*x = SetCacheReq{}
	mi := &file_sysTool_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCacheReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCacheReq) ProtoMessage() {}

func (x *SetCacheReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysTool_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCacheReq.ProtoReflect.Descriptor instead.
func (*SetCacheReq) Descriptor() ([]byte, []int) {
	return file_sysTool_cache_proto_rawDescGZIP(), []int{2}
}

func (x *SetCacheReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetCacheReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetCacheReq) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type DeleteCacheReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCacheReq) Reset() {
	*x = DeleteCacheReq{}
	mi := &file_sysTool_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCacheReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCacheReq) ProtoMessage() {}

func (x *DeleteCacheReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysTool_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCacheReq.ProtoReflect.Descriptor instead.
func (*DeleteCacheReq) Descriptor() ([]byte, []int) {
	return file_sysTool_cache_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCacheReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CacheResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheResp) Reset() {
	*x = CacheResp{}
	mi := &file_sysTool_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheResp) ProtoMessage() {}

func (x *CacheResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysTool_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheResp.ProtoReflect.Descriptor instead.
func (*CacheResp) Descriptor() ([]byte, []int) {
	return file_sysTool_cache_proto_rawDescGZIP(), []int{4}
}

func (x *CacheResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CacheResp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CacheResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CacheResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CacheResp) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CacheResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CacheResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListCacheResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CacheResp           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCacheResp) Reset() {
	*x = ListCacheResp{}
	mi := &file_sysTool_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCacheResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCacheResp) ProtoMessage() {}

func (x *ListCacheResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysTool_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCacheResp.ProtoReflect.Descriptor instead.
func (*ListCacheResp) Descriptor() ([]byte, []int) {
	return file_sysTool_cache_proto_rawDescGZIP(), []int{5}
}

func (x *ListCacheResp) GetList() []*CacheResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListCacheResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CleanupExpiredResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int64                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupExpiredResp) Reset() {
	*x = CleanupExpiredResp{}
	mi := &file_sysTool_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupExpiredResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupExpiredResp) ProtoMessage() {}

func (x *CleanupExpiredResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysTool_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupExpiredResp.ProtoReflect.Descriptor instead.
func (*CleanupExpiredResp) Descriptor() ([]byte, []int) {
	return file_sysTool_cache_proto_rawDescGZIP(), []int{6}
}

func (x *CleanupExpiredResp) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_sysTool_cache_proto protoreflect.FileDescriptor

const file_sysTool_cache_proto_rawDesc = "" +
	"\n" +
	"\x13sysTool/cache.proto\x12\x13basis.sysTool.cache\x1a\x13common/common.proto\"\x1f\n" +
	"\vGetCacheReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"U\n" +
	"\fGetCacheResp\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"V\n" +
	"\vSetCacheReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"\"\n" +
	"\x0eDeleteCacheReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xbc\x01\n" +
	"\tCacheResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"Y\n" +
	"\rListCacheResp\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.basis.sysTool.cache.CacheRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"9\n" +
	"\x12CleanupExpiredResp\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x03R\fdeletedCount2\x88\x03\n" +
	"\x05Cache\x12O\n" +
	"\bGetCache\x12 .basis.sysTool.cache.GetCacheReq\x1a!.basis.sysTool.cache.GetCacheResp\x12G\n" +
	"\bSetCache\x12 .basis.sysTool.cache.SetCacheReq\x1a\x19.basis.common.SuccessResp\x12M\n" +
	"\vDeleteCache\x12#.basis.sysTool.cache.DeleteCacheReq\x1a\x19.basis.common.SuccessResp\x12F\n" +
	"\tListCache\x12\x15.basis.common.PageReq\x1a\".basis.sysTool.cache.ListCacheResp\x12N\n" +
	"\x0eCleanupExpired\x12\x13.basis.common.Empty\x1a'.basis.sysTool.cache.CleanupExpiredRespB0Z.td27/rpc/basis/types/sysTool/cache_pb;cache_pbb\x06proto3"

var (
	file_sysTool_cache_proto_rawDescOnce sync.Once
	file_sysTool_cache_proto_rawDescData []byte
)

func file_sysTool_cache_proto_rawDescGZIP() []byte {
	file_sysTool_cache_proto_rawDescOnce.Do(func() {
		file_sysTool_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysTool_cache_proto_rawDesc), len(file_sysTool_cache_proto_rawDesc)))
	})
	return file_sysTool_cache_proto_rawDescData
}

var file_sysTool_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sysTool_cache_proto_goTypes = []any{
	(*GetCacheReq)(nil),           // 0: basis.sysTool.cache.GetCacheReq
	(*GetCacheResp)(nil),          // 1: basis.sysTool.cache.GetCacheResp
	(*SetCacheReq)(nil),           // 2: basis.sysTool.cache.SetCacheReq
	(*DeleteCacheReq)(nil),        // 3: basis.sysTool.cache.DeleteCacheReq
	(*CacheResp)(nil),             // 4: basis.sysTool.cache.CacheResp
	(*ListCacheResp)(nil),         // 5: basis.sysTool.cache.ListCacheResp
	(*CleanupExpiredResp)(nil),    // 6: basis.sysTool.cache.CleanupExpiredResp
	(*common_pb.PageReq)(nil),     // 7: basis.common.PageReq
	(*common_pb.Empty)(nil),       // 8: basis.common.Empty
	(*common_pb.SuccessResp)(nil), // 9: basis.common.SuccessResp
}
var file_sysTool_cache_proto_depIdxs = []int32{
	4, // 0: basis.sysTool.cache.ListCacheResp.list:type_name -> basis.sysTool.cache.CacheResp
	0, // 1: basis.sysTool.cache.Cache.GetCache:input_type -> basis.sysTool.cache.GetCacheReq
	2, // 2: basis.sysTool.cache.Cache.SetCache:input_type -> basis.sysTool.cache.SetCacheReq
	3, // 3: basis.sysTool.cache.Cache.DeleteCache:input_type -> basis.sysTool.cache.DeleteCacheReq
	7, // 4: basis.sysTool.cache.Cache.ListCache:input_type -> basis.common.PageReq
	8, // 5: basis.sysTool.cache.Cache.CleanupExpired:input_type -> basis.common.Empty
	1, // 6: basis.sysTool.cache.Cache.GetCache:output_type -> basis.sysTool.cache.GetCacheResp
	9, // 7: basis.sysTool.cache.Cache.SetCache:output_type -> basis.common.SuccessResp
	9, // 8: basis.sysTool.cache.Cache.DeleteCache:output_type -> basis.common.SuccessResp
	5, // 9: basis.sysTool.cache.Cache.ListCache:output_type -> basis.sysTool.cache.ListCacheResp
	6, // 10: basis.sysTool.cache.Cache.CleanupExpired:output_type -> basis.sysTool.cache.CleanupExpiredResp
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sysTool_cache_proto_init() }
func file_sysTool_cache_proto_init() {
	if File_sysTool_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysTool_cache_proto_rawDesc), len(file_sysTool_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysTool_cache_proto_goTypes,
		DependencyIndexes: file_sysTool_cache_proto_depIdxs,
		MessageInfos:      file_sysTool_cache_proto_msgTypes,
	}.Build()
	File_sysTool_cache_proto = out.File
	file_sysTool_cache_proto_goTypes = nil
	file_sysTool_cache_proto_depIdxs = nil
}
