// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: sysManagement/dict.proto

package dict_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDictReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CnName        string                 `protobuf:"bytes,1,opt,name=cn_name,json=cnName,proto3" json:"cn_name,omitempty"`
	EnName        string                 `protobuf:"bytes,2,opt,name=en_name,json=enName,proto3" json:"en_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictReq) Reset() {
	*x = CreateDictReq{}
	mi := &file_sysManagement_dict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictReq) ProtoMessage() {}

func (x *CreateDictReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_dict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictReq.ProtoReflect.Descriptor instead.
func (*CreateDictReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_dict_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDictReq) GetCnName() string {
	if x != nil {
		return x.CnName
	}
	return ""
}

func (x *CreateDictReq) GetEnName() string {
	if x != nil {
		return x.EnName
	}
	return ""
}

type UpdateDictReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CnName        *string                `protobuf:"bytes,2,opt,name=cn_name,json=cnName,proto3,oneof" json:"cn_name,omitempty"`
	EnName        *string                `protobuf:"bytes,3,opt,name=en_name,json=enName,proto3,oneof" json:"en_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictReq) Reset() {
	*x = UpdateDictReq{}
	mi := &file_sysManagement_dict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictReq) ProtoMessage() {}

func (x *UpdateDictReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_dict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictReq.ProtoReflect.Descriptor instead.
func (*UpdateDictReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_dict_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDictReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDictReq) GetCnName() string {
	if x != nil && x.CnName != nil {
		return *x.CnName
	}
	return ""
}

func (x *UpdateDictReq) GetEnName() string {
	if x != nil && x.EnName != nil {
		return *x.EnName
	}
	return ""
}

type DictDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      int64                  `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Children      []*DictDetailResp      `protobuf:"bytes,9,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictDetailResp) Reset() {
	*x = DictDetailResp{}
	mi := &file_sysManagement_dict_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictDetailResp) ProtoMessage() {}

func (x *DictDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_dict_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictDetailResp.ProtoReflect.Descriptor instead.
func (*DictDetailResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_dict_proto_rawDescGZIP(), []int{2}
}

func (x *DictDetailResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DictDetailResp) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DictDetailResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DictDetailResp) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *DictDetailResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DictDetailResp) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *DictDetailResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DictDetailResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *DictDetailResp) GetChildren() []*DictDetailResp {
	if x != nil {
		return x.Children
	}
	return nil
}

type DictResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CnName        string                 `protobuf:"bytes,2,opt,name=cn_name,json=cnName,proto3" json:"cn_name,omitempty"`
	EnName        string                 `protobuf:"bytes,3,opt,name=en_name,json=enName,proto3" json:"en_name,omitempty"`
	Details       []*DictDetailResp      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictResp) Reset() {
	*x = DictResp{}
	mi := &file_sysManagement_dict_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictResp) ProtoMessage() {}

func (x *DictResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_dict_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictResp.ProtoReflect.Descriptor instead.
func (*DictResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_dict_proto_rawDescGZIP(), []int{3}
}

func (x *DictResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DictResp) GetCnName() string {
	if x != nil {
		return x.CnName
	}
	return ""
}

func (x *DictResp) GetEnName() string {
	if x != nil {
		return x.EnName
	}
	return ""
}

func (x *DictResp) GetDetails() []*DictDetailResp {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *DictResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DictResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListDictResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*DictResp            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictResp) Reset() {
	*x = ListDictResp{}
	mi := &file_sysManagement_dict_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictResp) ProtoMessage() {}

func (x *ListDictResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_dict_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictResp.ProtoReflect.Descriptor instead.
func (*ListDictResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_dict_proto_rawDescGZIP(), []int{4}
}

func (x *ListDictResp) GetList() []*DictResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListDictResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetDictByENNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnName        string                 `protobuf:"bytes,1,opt,name=en_name,json=enName,proto3" json:"en_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDictByENNameReq) Reset() {
	*x = GetDictByENNameReq{}
	mi := &file_sysManagement_dict_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDictByENNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictByENNameReq) ProtoMessage() {}

func (x *GetDictByENNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_dict_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictByENNameReq.ProtoReflect.Descriptor instead.
func (*GetDictByENNameReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_dict_proto_rawDescGZIP(), []int{5}
}

func (x *GetDictByENNameReq) GetEnName() string {
	if x != nil {
		return x.EnName
	}
	return ""
}

var File_sysManagement_dict_proto protoreflect.FileDescriptor

const file_sysManagement_dict_proto_rawDesc = "" +
	"\n" +
	"\x18sysManagement/dict.proto\x12\x18basis.sysManagement.dict\x1a\x13common/common.proto\"A\n" +
	"\rCreateDictReq\x12\x17\n" +
	"\acn_name\x18\x01 \x01(\tR\x06cnName\x12\x17\n" +
	"\aen_name\x18\x02 \x01(\tR\x06enName\"s\n" +
	"\rUpdateDictReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\acn_name\x18\x02 \x01(\tH\x00R\x06cnName\x88\x01\x01\x12\x1c\n" +
	"\aen_name\x18\x03 \x01(\tH\x01R\x06enName\x88\x01\x01B\n" +
	"\n" +
	"\b_cn_nameB\n" +
	"\n" +
	"\b_en_name\"\xa3\x02\n" +
	"\x0eDictDetailResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\x03R\bparentId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12D\n" +
	"\bchildren\x18\t \x03(\v2(.basis.sysManagement.dict.DictDetailRespR\bchildren\"\xce\x01\n" +
	"\bDictResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\acn_name\x18\x02 \x01(\tR\x06cnName\x12\x17\n" +
	"\aen_name\x18\x03 \x01(\tR\x06enName\x12B\n" +
	"\adetails\x18\x04 \x03(\v2(.basis.sysManagement.dict.DictDetailRespR\adetails\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\\\n" +
	"\fListDictResp\x126\n" +
	"\x04list\x18\x01 \x03(\v2\".basis.sysManagement.dict.DictRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"-\n" +
	"\x12GetDictByENNameReq\x12\x17\n" +
	"\aen_name\x18\x01 \x01(\tR\x06enName2\xe5\x03\n" +
	"\x04Dict\x12B\n" +
	"\aGetDict\x12\x13.basis.common.IdReq\x1a\".basis.sysManagement.dict.DictResp\x12c\n" +
	"\x0fGetDictByENName\x12,.basis.sysManagement.dict.GetDictByENNameReq\x1a\".basis.sysManagement.dict.DictResp\x12I\n" +
	"\bListDict\x12\x15.basis.common.PageReq\x1a&.basis.sysManagement.dict.ListDictResp\x12P\n" +
	"\n" +
	"CreateDict\x12'.basis.sysManagement.dict.CreateDictReq\x1a\x19.basis.common.SuccessResp\x12Y\n" +
	"\n" +
	"UpdateDict\x12'.basis.sysManagement.dict.UpdateDictReq\x1a\".basis.sysManagement.dict.DictResp\x12<\n" +
	"\n" +
	"DeleteDict\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessRespB4Z2td27/rpc/basis/types/sysManagement/dict_pb;dict_pbb\x06proto3"

var (
	file_sysManagement_dict_proto_rawDescOnce sync.Once
	file_sysManagement_dict_proto_rawDescData []byte
)

func file_sysManagement_dict_proto_rawDescGZIP() []byte {
	file_sysManagement_dict_proto_rawDescOnce.Do(func() {
		file_sysManagement_dict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysManagement_dict_proto_rawDesc), len(file_sysManagement_dict_proto_rawDesc)))
	})
	return file_sysManagement_dict_proto_rawDescData
}

var file_sysManagement_dict_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sysManagement_dict_proto_goTypes = []any{
	(*CreateDictReq)(nil),         // 0: basis.sysManagement.dict.CreateDictReq
	(*UpdateDictReq)(nil),         // 1: basis.sysManagement.dict.UpdateDictReq
	(*DictDetailResp)(nil),        // 2: basis.sysManagement.dict.DictDetailResp
	(*DictResp)(nil),              // 3: basis.sysManagement.dict.DictResp
	(*ListDictResp)(nil),          // 4: basis.sysManagement.dict.ListDictResp
	(*GetDictByENNameReq)(nil),    // 5: basis.sysManagement.dict.GetDictByENNameReq
	(*common_pb.IdReq)(nil),       // 6: basis.common.IdReq
	(*common_pb.PageReq)(nil),     // 7: basis.common.PageReq
	(*common_pb.SuccessResp)(nil), // 8: basis.common.SuccessResp
}
var file_sysManagement_dict_proto_depIdxs = []int32{
	2, // 0: basis.sysManagement.dict.DictDetailResp.children:type_name -> basis.sysManagement.dict.DictDetailResp
	2, // 1: basis.sysManagement.dict.DictResp.details:type_name -> basis.sysManagement.dict.DictDetailResp
	3, // 2: basis.sysManagement.dict.ListDictResp.list:type_name -> basis.sysManagement.dict.DictResp
	6, // 3: basis.sysManagement.dict.Dict.GetDict:input_type -> basis.common.IdReq
	5, // 4: basis.sysManagement.dict.Dict.GetDictByENName:input_type -> basis.sysManagement.dict.GetDictByENNameReq
	7, // 5: basis.sysManagement.dict.Dict.ListDict:input_type -> basis.common.PageReq
	0, // 6: basis.sysManagement.dict.Dict.CreateDict:input_type -> basis.sysManagement.dict.CreateDictReq
	1, // 7: basis.sysManagement.dict.Dict.UpdateDict:input_type -> basis.sysManagement.dict.UpdateDictReq
	6, // 8: basis.sysManagement.dict.Dict.DeleteDict:input_type -> basis.common.IdReq
	3, // 9: basis.sysManagement.dict.Dict.GetDict:output_type -> basis.sysManagement.dict.DictResp
	3, // 10: basis.sysManagement.dict.Dict.GetDictByENName:output_type -> basis.sysManagement.dict.DictResp
	4, // 11: basis.sysManagement.dict.Dict.ListDict:output_type -> basis.sysManagement.dict.ListDictResp
	8, // 12: basis.sysManagement.dict.Dict.CreateDict:output_type -> basis.common.SuccessResp
	3, // 13: basis.sysManagement.dict.Dict.UpdateDict:output_type -> basis.sysManagement.dict.DictResp
	8, // 14: basis.sysManagement.dict.Dict.DeleteDict:output_type -> basis.common.SuccessResp
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sysManagement_dict_proto_init() }
func file_sysManagement_dict_proto_init() {
	if File_sysManagement_dict_proto != nil {
		return
	}
	file_sysManagement_dict_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysManagement_dict_proto_rawDesc), len(file_sysManagement_dict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysManagement_dict_proto_goTypes,
		DependencyIndexes: file_sysManagement_dict_proto_depIdxs,
		MessageInfos:      file_sysManagement_dict_proto_msgTypes,
	}.Build()
	File_sysManagement_dict_proto = out.File
	file_sysManagement_dict_proto_goTypes = nil
	file_sysManagement_dict_proto_depIdxs = nil
}
