// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: monitor/operation_log.proto

package operation_log_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common_pb "td27/rpc/basis/types/common_pb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperationLog_ListOperationLog_FullMethodName   = "/basis.monitor.operation_log.OperationLog/ListOperationLog"
	OperationLog_CleanupExpiredLogs_FullMethodName = "/basis.monitor.operation_log.OperationLog/CleanupExpiredLogs"
)

// OperationLogClient is the client API for OperationLog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OperationLogClient interface {
	ListOperationLog(ctx context.Context, in *ListOperationLogReq, opts ...grpc.CallOption) (*ListOperationLogResp, error)
	CleanupExpiredLogs(ctx context.Context, in *CleanupExpiredLogsReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
}

type operationLogClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationLogClient(cc grpc.ClientConnInterface) OperationLogClient {
	return &operationLogClient{cc}
}

func (c *operationLogClient) ListOperationLog(ctx context.Context, in *ListOperationLogReq, opts ...grpc.CallOption) (*ListOperationLogResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperationLogResp)
	err := c.cc.Invoke(ctx, OperationLog_ListOperationLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationLogClient) CleanupExpiredLogs(ctx context.Context, in *CleanupExpiredLogsReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, OperationLog_CleanupExpiredLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationLogServer is the server API for OperationLog service.
// All implementations must embed UnimplementedOperationLogServer
// for forward compatibility.
type OperationLogServer interface {
	ListOperationLog(context.Context, *ListOperationLogReq) (*ListOperationLogResp, error)
	CleanupExpiredLogs(context.Context, *CleanupExpiredLogsReq) (*common_pb.SuccessResp, error)
	mustEmbedUnimplementedOperationLogServer()
}

// UnimplementedOperationLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperationLogServer struct{}

func (UnimplementedOperationLogServer) ListOperationLog(context.Context, *ListOperationLogReq) (*ListOperationLogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOperationLog not implemented")
}
func (UnimplementedOperationLogServer) CleanupExpiredLogs(context.Context, *CleanupExpiredLogsReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanupExpiredLogs not implemented")
}
func (UnimplementedOperationLogServer) mustEmbedUnimplementedOperationLogServer() {}
func (UnimplementedOperationLogServer) testEmbeddedByValue()                      {}

// UnsafeOperationLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperationLogServer will
// result in compilation errors.
type UnsafeOperationLogServer interface {
	mustEmbedUnimplementedOperationLogServer()
}

func RegisterOperationLogServer(s grpc.ServiceRegistrar, srv OperationLogServer) {
	// If the following call pancis, it indicates UnimplementedOperationLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperationLog_ServiceDesc, srv)
}

func _OperationLog_ListOperationLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperationLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationLogServer).ListOperationLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationLog_ListOperationLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationLogServer).ListOperationLog(ctx, req.(*ListOperationLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperationLog_CleanupExpiredLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupExpiredLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationLogServer).CleanupExpiredLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperationLog_CleanupExpiredLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationLogServer).CleanupExpiredLogs(ctx, req.(*CleanupExpiredLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// OperationLog_ServiceDesc is the grpc.ServiceDesc for OperationLog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperationLog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basis.monitor.operation_log.OperationLog",
	HandlerType: (*OperationLogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOperationLog",
			Handler:    _OperationLog_ListOperationLog_Handler,
		},
		{
			MethodName: "CleanupExpiredLogs",
			Handler:    _OperationLog_CleanupExpiredLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor/operation_log.proto",
}
