// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: basis.proto

package server

import (
	"context"

	"basis/basis"
	"basis/internal/logic"
	"basis/internal/svc"
)

type BasisServer struct {
	svcCtx *svc.ServiceContext
	basis.UnimplementedBasisServer
}

func NewBasisServer(svcCtx *svc.ServiceContext) *BasisServer {
	return &BasisServer{
		svcCtx: svcCtx,
	}
}

func (s *BasisServer) Ping(ctx context.Context, in *basis.Request) (*basis.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
