syntax = "proto3";

import "common/common.proto";
import "google/protobuf/timestamp.proto";

package basis.tool.cron;

option go_package = "td27/rpc/basis/types/tool/cron_pb;cron_pb";

enum CronMethod {
  METHOD_CLEAR_TABLE = 0;
  METHOD_CLEAR_CACHE = 1;
  METHOD_SHELL = 2;
}

message ClearTableParam {
  string table_name = 1;
  string compare_field = 2;
  string interval = 3;
}

message CronExtraParams {
  repeated ClearTableParam table_info = 1;
  string command = 2;
}

message CreateCronReq {
  string name = 1;
  CronMethod method = 2;
  string expression = 3;
  optional string strategy = 4;
  optional bool open = 5;
  optional CronExtraParams extra_params = 6;
  optional string comment = 7;
}

message UpdateCronReq {
  uint64 id = 1;
  optional string name = 2;
  optional CronMethod method = 3;
  optional string expression = 4;
  optional string strategy = 5;
  optional bool open = 6;
  optional CronExtraParams extra_params = 7;
  optional string comment = 8;
}

message CronResp {
  uint64 id = 1;
  string name = 2;
  CronMethod method = 3;
  string expression = 4;
  string strategy = 5;
  bool open = 6;
  CronExtraParams extra_params = 7;
  int32 entry_id = 8;
  string comment = 9;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
}

message ListCronResp {
  repeated CronResp list = 1;
  int64 total = 2;
}

message ToggleCronStatusReq {
  uint64 id = 1;
  bool open = 2;
}

message ExecuteCronNowReq {
  uint64 id = 1;
}

service Cron {
  rpc GetCron(basis.common.IdReq) returns (CronResp);
  rpc ListCron(basis.common.PageReq) returns (ListCronResp);
  rpc CreateCron(CreateCronReq) returns (basis.common.SuccessResp);
  rpc UpdateCron(UpdateCronReq) returns (CronResp);
  rpc ToggleCronStatus(ToggleCronStatusReq) returns (basis.common.SuccessResp);
  rpc ExecuteCronNow(ExecuteCronNowReq) returns (basis.common.SuccessResp);
  rpc DeleteCron(basis.common.IdReq) returns (basis.common.SuccessResp);
}
