// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: sysMonitor/operation_log.proto

package operation_log_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ReqParam      string                 `protobuf:"bytes,7,opt,name=req_param,json=reqParam,proto3" json:"req_param,omitempty"`
	RespData      string                 `protobuf:"bytes,8,opt,name=resp_data,json=respData,proto3" json:"resp_data,omitempty"`
	RespTime      int64                  `protobuf:"varint,9,opt,name=resp_time,json=respTime,proto3" json:"resp_time,omitempty"`
	UserId        int64                  `protobuf:"varint,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,11,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationLogResp) Reset() {
	*x = OperationLogResp{}
	mi := &file_sysMonitor_operation_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationLogResp) ProtoMessage() {}

func (x *OperationLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysMonitor_operation_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationLogResp.ProtoReflect.Descriptor instead.
func (*OperationLogResp) Descriptor() ([]byte, []int) {
	return file_sysMonitor_operation_log_proto_rawDescGZIP(), []int{0}
}

func (x *OperationLogResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OperationLogResp) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OperationLogResp) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *OperationLogResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OperationLogResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OperationLogResp) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *OperationLogResp) GetReqParam() string {
	if x != nil {
		return x.ReqParam
	}
	return ""
}

func (x *OperationLogResp) GetRespData() string {
	if x != nil {
		return x.RespData
	}
	return ""
}

func (x *OperationLogResp) GetRespTime() int64 {
	if x != nil {
		return x.RespTime
	}
	return 0
}

func (x *OperationLogResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OperationLogResp) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *OperationLogResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListOperationLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *common_pb.PageReq     `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	UserId        *int64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Status        *int32                 `protobuf:"varint,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Path          *string                `protobuf:"bytes,4,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Method        *string                `protobuf:"bytes,5,opt,name=method,proto3,oneof" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationLogReq) Reset() {
	*x = ListOperationLogReq{}
	mi := &file_sysMonitor_operation_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationLogReq) ProtoMessage() {}

func (x *ListOperationLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysMonitor_operation_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationLogReq.ProtoReflect.Descriptor instead.
func (*ListOperationLogReq) Descriptor() ([]byte, []int) {
	return file_sysMonitor_operation_log_proto_rawDescGZIP(), []int{1}
}

func (x *ListOperationLogReq) GetPage() *common_pb.PageReq {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListOperationLogReq) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *ListOperationLogReq) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *ListOperationLogReq) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *ListOperationLogReq) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

type ListOperationLogResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*OperationLogResp    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationLogResp) Reset() {
	*x = ListOperationLogResp{}
	mi := &file_sysMonitor_operation_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationLogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationLogResp) ProtoMessage() {}

func (x *ListOperationLogResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysMonitor_operation_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationLogResp.ProtoReflect.Descriptor instead.
func (*ListOperationLogResp) Descriptor() ([]byte, []int) {
	return file_sysMonitor_operation_log_proto_rawDescGZIP(), []int{2}
}

func (x *ListOperationLogResp) GetList() []*OperationLogResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListOperationLogResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateOperationLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ReqParam      string                 `protobuf:"bytes,6,opt,name=req_param,json=reqParam,proto3" json:"req_param,omitempty"`
	RespData      string                 `protobuf:"bytes,7,opt,name=resp_data,json=respData,proto3" json:"resp_data,omitempty"`
	RespTime      int64                  `protobuf:"varint,8,opt,name=resp_time,json=respTime,proto3" json:"resp_time,omitempty"`
	UserId        int64                  `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,10,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOperationLogReq) Reset() {
	*x = CreateOperationLogReq{}
	mi := &file_sysMonitor_operation_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperationLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperationLogReq) ProtoMessage() {}

func (x *CreateOperationLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysMonitor_operation_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperationLogReq.ProtoReflect.Descriptor instead.
func (*CreateOperationLogReq) Descriptor() ([]byte, []int) {
	return file_sysMonitor_operation_log_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOperationLogReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CreateOperationLogReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreateOperationLogReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateOperationLogReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateOperationLogReq) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *CreateOperationLogReq) GetReqParam() string {
	if x != nil {
		return x.ReqParam
	}
	return ""
}

func (x *CreateOperationLogReq) GetRespData() string {
	if x != nil {
		return x.RespData
	}
	return ""
}

func (x *CreateOperationLogReq) GetRespTime() int64 {
	if x != nil {
		return x.RespTime
	}
	return 0
}

func (x *CreateOperationLogReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOperationLogReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type CleanupExpiredLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int32                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupExpiredLogsReq) Reset() {
	*x = CleanupExpiredLogsReq{}
	mi := &file_sysMonitor_operation_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupExpiredLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupExpiredLogsReq) ProtoMessage() {}

func (x *CleanupExpiredLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysMonitor_operation_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupExpiredLogsReq.ProtoReflect.Descriptor instead.
func (*CleanupExpiredLogsReq) Descriptor() ([]byte, []int) {
	return file_sysMonitor_operation_log_proto_rawDescGZIP(), []int{4}
}

func (x *CleanupExpiredLogsReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

var File_sysMonitor_operation_log_proto protoreflect.FileDescriptor

const file_sysMonitor_operation_log_proto_rawDesc = "" +
	"\n" +
	"\x1esysMonitor/operation_log.proto\x12\x1ebasis.sysMonitor.operation_log\x1a\x13common/common.proto\"\xc1\x02\n" +
	"\x10OperationLogResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x12\x1b\n" +
	"\treq_param\x18\a \x01(\tR\breqParam\x12\x1b\n" +
	"\tresp_data\x18\b \x01(\tR\brespData\x12\x1b\n" +
	"\tresp_time\x18\t \x01(\x03R\brespTime\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\v \x01(\tR\buserName\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"\xdc\x01\n" +
	"\x13ListOperationLogReq\x12)\n" +
	"\x04page\x18\x01 \x01(\v2\x15.basis.common.PageReqR\x04page\x12\x1c\n" +
	"\auser_id\x18\x02 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\x05H\x01R\x06status\x88\x01\x01\x12\x17\n" +
	"\x04path\x18\x04 \x01(\tH\x02R\x04path\x88\x01\x01\x12\x1b\n" +
	"\x06method\x18\x05 \x01(\tH\x03R\x06method\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\t\n" +
	"\a_statusB\a\n" +
	"\x05_pathB\t\n" +
	"\a_method\"r\n" +
	"\x14ListOperationLogResp\x12D\n" +
	"\x04list\x18\x01 \x03(\v20.basis.sysMonitor.operation_log.OperationLogRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x97\x02\n" +
	"\x15CreateOperationLogReq\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x1b\n" +
	"\treq_param\x18\x06 \x01(\tR\breqParam\x12\x1b\n" +
	"\tresp_data\x18\a \x01(\tR\brespData\x12\x1b\n" +
	"\tresp_time\x18\b \x01(\x03R\brespTime\x12\x17\n" +
	"\auser_id\x18\t \x01(\x03R\x06userId\x12\x1b\n" +
	"\tuser_name\x18\n" +
	" \x01(\tR\buserName\"+\n" +
	"\x15CleanupExpiredLogsReq\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x05R\x04days2\xd7\x03\n" +
	"\fOperationLog\x12}\n" +
	"\x10ListOperationLog\x123.basis.sysMonitor.operation_log.ListOperationLogReq\x1a4.basis.sysMonitor.operation_log.ListOperationLogResp\x12f\n" +
	"\x12CreateOperationLog\x125.basis.sysMonitor.operation_log.CreateOperationLogReq\x1a\x19.basis.common.SuccessResp\x12f\n" +
	"\x12CleanupExpiredLogs\x125.basis.sysMonitor.operation_log.CleanupExpiredLogsReq\x1a\x19.basis.common.SuccessResp\x128\n" +
	"\x06Delete\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessResp\x12>\n" +
	"\vDeleteByIds\x12\x14.basis.common.IdsReq\x1a\x19.basis.common.SuccessRespBCZAtd27/rpc/basis/types/sysMonitor/operation_log_pb;operation_log_pbb\x06proto3"

var (
	file_sysMonitor_operation_log_proto_rawDescOnce sync.Once
	file_sysMonitor_operation_log_proto_rawDescData []byte
)

func file_sysMonitor_operation_log_proto_rawDescGZIP() []byte {
	file_sysMonitor_operation_log_proto_rawDescOnce.Do(func() {
		file_sysMonitor_operation_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysMonitor_operation_log_proto_rawDesc), len(file_sysMonitor_operation_log_proto_rawDesc)))
	})
	return file_sysMonitor_operation_log_proto_rawDescData
}

var file_sysMonitor_operation_log_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sysMonitor_operation_log_proto_goTypes = []any{
	(*OperationLogResp)(nil),      // 0: basis.sysMonitor.operation_log.OperationLogResp
	(*ListOperationLogReq)(nil),   // 1: basis.sysMonitor.operation_log.ListOperationLogReq
	(*ListOperationLogResp)(nil),  // 2: basis.sysMonitor.operation_log.ListOperationLogResp
	(*CreateOperationLogReq)(nil), // 3: basis.sysMonitor.operation_log.CreateOperationLogReq
	(*CleanupExpiredLogsReq)(nil), // 4: basis.sysMonitor.operation_log.CleanupExpiredLogsReq
	(*common_pb.PageReq)(nil),     // 5: basis.common.PageReq
	(*common_pb.IdReq)(nil),       // 6: basis.common.IdReq
	(*common_pb.IdsReq)(nil),      // 7: basis.common.IdsReq
	(*common_pb.SuccessResp)(nil), // 8: basis.common.SuccessResp
}
var file_sysMonitor_operation_log_proto_depIdxs = []int32{
	5, // 0: basis.sysMonitor.operation_log.ListOperationLogReq.page:type_name -> basis.common.PageReq
	0, // 1: basis.sysMonitor.operation_log.ListOperationLogResp.list:type_name -> basis.sysMonitor.operation_log.OperationLogResp
	1, // 2: basis.sysMonitor.operation_log.OperationLog.ListOperationLog:input_type -> basis.sysMonitor.operation_log.ListOperationLogReq
	3, // 3: basis.sysMonitor.operation_log.OperationLog.CreateOperationLog:input_type -> basis.sysMonitor.operation_log.CreateOperationLogReq
	4, // 4: basis.sysMonitor.operation_log.OperationLog.CleanupExpiredLogs:input_type -> basis.sysMonitor.operation_log.CleanupExpiredLogsReq
	6, // 5: basis.sysMonitor.operation_log.OperationLog.Delete:input_type -> basis.common.IdReq
	7, // 6: basis.sysMonitor.operation_log.OperationLog.DeleteByIds:input_type -> basis.common.IdsReq
	2, // 7: basis.sysMonitor.operation_log.OperationLog.ListOperationLog:output_type -> basis.sysMonitor.operation_log.ListOperationLogResp
	8, // 8: basis.sysMonitor.operation_log.OperationLog.CreateOperationLog:output_type -> basis.common.SuccessResp
	8, // 9: basis.sysMonitor.operation_log.OperationLog.CleanupExpiredLogs:output_type -> basis.common.SuccessResp
	8, // 10: basis.sysMonitor.operation_log.OperationLog.Delete:output_type -> basis.common.SuccessResp
	8, // 11: basis.sysMonitor.operation_log.OperationLog.DeleteByIds:output_type -> basis.common.SuccessResp
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sysMonitor_operation_log_proto_init() }
func file_sysMonitor_operation_log_proto_init() {
	if File_sysMonitor_operation_log_proto != nil {
		return
	}
	file_sysMonitor_operation_log_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysMonitor_operation_log_proto_rawDesc), len(file_sysMonitor_operation_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysMonitor_operation_log_proto_goTypes,
		DependencyIndexes: file_sysMonitor_operation_log_proto_depIdxs,
		MessageInfos:      file_sysMonitor_operation_log_proto_msgTypes,
	}.Build()
	File_sysMonitor_operation_log_proto = out.File
	file_sysMonitor_operation_log_proto_goTypes = nil
	file_sysMonitor_operation_log_proto_depIdxs = nil
}
