// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: sysManagement/api.proto

package api_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAPIReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	GroupEn       string                 `protobuf:"bytes,3,opt,name=group_en,json=groupEn,proto3" json:"group_en,omitempty"`
	GroupCn       string                 `protobuf:"bytes,4,opt,name=group_cn,json=groupCn,proto3" json:"group_cn,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIReq) Reset() {
	*x = CreateAPIReq{}
	mi := &file_sysManagement_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIReq) ProtoMessage() {}

func (x *CreateAPIReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIReq.ProtoReflect.Descriptor instead.
func (*CreateAPIReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAPIReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateAPIReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreateAPIReq) GetGroupEn() string {
	if x != nil {
		return x.GroupEn
	}
	return ""
}

func (x *CreateAPIReq) GetGroupCn() string {
	if x != nil {
		return x.GroupCn
	}
	return ""
}

func (x *CreateAPIReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateAPIReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          *string                `protobuf:"bytes,2,opt,name=path,proto3,oneof" json:"path,omitempty"`
	Method        *string                `protobuf:"bytes,3,opt,name=method,proto3,oneof" json:"method,omitempty"`
	GroupEn       *string                `protobuf:"bytes,4,opt,name=group_en,json=groupEn,proto3,oneof" json:"group_en,omitempty"`
	GroupCn       *string                `protobuf:"bytes,5,opt,name=group_cn,json=groupCn,proto3,oneof" json:"group_cn,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAPIReq) Reset() {
	*x = UpdateAPIReq{}
	mi := &file_sysManagement_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAPIReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAPIReq) ProtoMessage() {}

func (x *UpdateAPIReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAPIReq.ProtoReflect.Descriptor instead.
func (*UpdateAPIReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_api_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateAPIReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAPIReq) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *UpdateAPIReq) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

func (x *UpdateAPIReq) GetGroupEn() string {
	if x != nil && x.GroupEn != nil {
		return *x.GroupEn
	}
	return ""
}

func (x *UpdateAPIReq) GetGroupCn() string {
	if x != nil && x.GroupCn != nil {
		return *x.GroupCn
	}
	return ""
}

func (x *UpdateAPIReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type APIResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	GroupEn       string                 `protobuf:"bytes,4,opt,name=group_en,json=groupEn,proto3" json:"group_en,omitempty"`
	GroupCn       string                 `protobuf:"bytes,5,opt,name=group_cn,json=groupCn,proto3" json:"group_cn,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResp) Reset() {
	*x = APIResp{}
	mi := &file_sysManagement_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResp) ProtoMessage() {}

func (x *APIResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResp.ProtoReflect.Descriptor instead.
func (*APIResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_api_proto_rawDescGZIP(), []int{2}
}

func (x *APIResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *APIResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *APIResp) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *APIResp) GetGroupEn() string {
	if x != nil {
		return x.GroupEn
	}
	return ""
}

func (x *APIResp) GetGroupCn() string {
	if x != nil {
		return x.GroupCn
	}
	return ""
}

func (x *APIResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *APIResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *APIResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListAPIResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*APIResp             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIResp) Reset() {
	*x = ListAPIResp{}
	mi := &file_sysManagement_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIResp) ProtoMessage() {}

func (x *ListAPIResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIResp.ProtoReflect.Descriptor instead.
func (*ListAPIResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_api_proto_rawDescGZIP(), []int{3}
}

func (x *ListAPIResp) GetList() []*APIResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListAPIResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAPIsByGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupEn       string                 `protobuf:"bytes,1,opt,name=group_en,json=groupEn,proto3" json:"group_en,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIsByGroupReq) Reset() {
	*x = GetAPIsByGroupReq{}
	mi := &file_sysManagement_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIsByGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIsByGroupReq) ProtoMessage() {}

func (x *GetAPIsByGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIsByGroupReq.ProtoReflect.Descriptor instead.
func (*GetAPIsByGroupReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetAPIsByGroupReq) GetGroupEn() string {
	if x != nil {
		return x.GroupEn
	}
	return ""
}

type APITreeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APITreeReq) Reset() {
	*x = APITreeReq{}
	mi := &file_sysManagement_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APITreeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APITreeReq) ProtoMessage() {}

func (x *APITreeReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APITreeReq.ProtoReflect.Descriptor instead.
func (*APITreeReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_api_proto_rawDescGZIP(), []int{5}
}

func (x *APITreeReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type APITreeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupEn       string                 `protobuf:"bytes,1,opt,name=group_en,json=groupEn,proto3" json:"group_en,omitempty"`
	GroupCn       string                 `protobuf:"bytes,2,opt,name=group_cn,json=groupCn,proto3" json:"group_cn,omitempty"`
	Apis          []*APIResp             `protobuf:"bytes,3,rep,name=apis,proto3" json:"apis,omitempty"`
	Checked       bool                   `protobuf:"varint,4,opt,name=checked,proto3" json:"checked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APITreeItem) Reset() {
	*x = APITreeItem{}
	mi := &file_sysManagement_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APITreeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APITreeItem) ProtoMessage() {}

func (x *APITreeItem) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APITreeItem.ProtoReflect.Descriptor instead.
func (*APITreeItem) Descriptor() ([]byte, []int) {
	return file_sysManagement_api_proto_rawDescGZIP(), []int{6}
}

func (x *APITreeItem) GetGroupEn() string {
	if x != nil {
		return x.GroupEn
	}
	return ""
}

func (x *APITreeItem) GetGroupCn() string {
	if x != nil {
		return x.GroupCn
	}
	return ""
}

func (x *APITreeItem) GetApis() []*APIResp {
	if x != nil {
		return x.Apis
	}
	return nil
}

func (x *APITreeItem) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

type APITreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*APITreeItem         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	CheckedIds    []int64                `protobuf:"varint,2,rep,packed,name=checked_ids,json=checkedIds,proto3" json:"checked_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APITreeResp) Reset() {
	*x = APITreeResp{}
	mi := &file_sysManagement_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APITreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APITreeResp) ProtoMessage() {}

func (x *APITreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APITreeResp.ProtoReflect.Descriptor instead.
func (*APITreeResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_api_proto_rawDescGZIP(), []int{7}
}

func (x *APITreeResp) GetList() []*APITreeItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *APITreeResp) GetCheckedIds() []int64 {
	if x != nil {
		return x.CheckedIds
	}
	return nil
}

var File_sysManagement_api_proto protoreflect.FileDescriptor

const file_sysManagement_api_proto_rawDesc = "" +
	"\n" +
	"\x17sysManagement/api.proto\x12\x17basis.sysManagement.api\x1a\x13common/common.proto\"\x92\x01\n" +
	"\fCreateAPIReq\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x19\n" +
	"\bgroup_en\x18\x03 \x01(\tR\agroupEn\x12\x19\n" +
	"\bgroup_cn\x18\x04 \x01(\tR\agroupCn\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xf9\x01\n" +
	"\fUpdateAPIReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04path\x18\x02 \x01(\tH\x00R\x04path\x88\x01\x01\x12\x1b\n" +
	"\x06method\x18\x03 \x01(\tH\x01R\x06method\x88\x01\x01\x12\x1e\n" +
	"\bgroup_en\x18\x04 \x01(\tH\x02R\agroupEn\x88\x01\x01\x12\x1e\n" +
	"\bgroup_cn\x18\x05 \x01(\tH\x03R\agroupCn\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x04R\vdescription\x88\x01\x01B\a\n" +
	"\x05_pathB\t\n" +
	"\a_methodB\v\n" +
	"\t_group_enB\v\n" +
	"\t_group_cnB\x0e\n" +
	"\f_description\"\xdb\x01\n" +
	"\aAPIResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x19\n" +
	"\bgroup_en\x18\x04 \x01(\tR\agroupEn\x12\x19\n" +
	"\bgroup_cn\x18\x05 \x01(\tR\agroupCn\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"Y\n" +
	"\vListAPIResp\x124\n" +
	"\x04list\x18\x01 \x03(\v2 .basis.sysManagement.api.APIRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\".\n" +
	"\x11GetAPIsByGroupReq\x12\x19\n" +
	"\bgroup_en\x18\x01 \x01(\tR\agroupEn\"%\n" +
	"\n" +
	"APITreeReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\"\x93\x01\n" +
	"\vAPITreeItem\x12\x19\n" +
	"\bgroup_en\x18\x01 \x01(\tR\agroupEn\x12\x19\n" +
	"\bgroup_cn\x18\x02 \x01(\tR\agroupCn\x124\n" +
	"\x04apis\x18\x03 \x03(\v2 .basis.sysManagement.api.APIRespR\x04apis\x12\x18\n" +
	"\achecked\x18\x04 \x01(\bR\achecked\"h\n" +
	"\vAPITreeResp\x128\n" +
	"\x04list\x18\x01 \x03(\v2$.basis.sysManagement.api.APITreeItemR\x04list\x12\x1f\n" +
	"\vchecked_ids\x18\x02 \x03(\x03R\n" +
	"checkedIds2\xed\x04\n" +
	"\x03API\x12?\n" +
	"\x06GetAPI\x12\x13.basis.common.IdReq\x1a .basis.sysManagement.api.APIResp\x12F\n" +
	"\aListAPI\x12\x15.basis.common.PageReq\x1a$.basis.sysManagement.api.ListAPIResp\x12b\n" +
	"\x0eGetAPIsByGroup\x12*.basis.sysManagement.api.GetAPIsByGroupReq\x1a$.basis.sysManagement.api.ListAPIResp\x12M\n" +
	"\tCreateAPI\x12%.basis.sysManagement.api.CreateAPIReq\x1a\x19.basis.common.SuccessResp\x12T\n" +
	"\tUpdateAPI\x12%.basis.sysManagement.api.UpdateAPIReq\x1a .basis.sysManagement.api.APIResp\x12;\n" +
	"\tDeleteAPI\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessResp\x12>\n" +
	"\vDeleteByIds\x12\x14.basis.common.IdsReq\x1a\x19.basis.common.SuccessResp\x12W\n" +
	"\n" +
	"GetAPITree\x12#.basis.sysManagement.api.APITreeReq\x1a$.basis.sysManagement.api.APITreeRespB2Z0td27/rpc/basis/types/sysManagement/api_pb;api_pbb\x06proto3"

var (
	file_sysManagement_api_proto_rawDescOnce sync.Once
	file_sysManagement_api_proto_rawDescData []byte
)

func file_sysManagement_api_proto_rawDescGZIP() []byte {
	file_sysManagement_api_proto_rawDescOnce.Do(func() {
		file_sysManagement_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysManagement_api_proto_rawDesc), len(file_sysManagement_api_proto_rawDesc)))
	})
	return file_sysManagement_api_proto_rawDescData
}

var file_sysManagement_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sysManagement_api_proto_goTypes = []any{
	(*CreateAPIReq)(nil),          // 0: basis.sysManagement.api.CreateAPIReq
	(*UpdateAPIReq)(nil),          // 1: basis.sysManagement.api.UpdateAPIReq
	(*APIResp)(nil),               // 2: basis.sysManagement.api.APIResp
	(*ListAPIResp)(nil),           // 3: basis.sysManagement.api.ListAPIResp
	(*GetAPIsByGroupReq)(nil),     // 4: basis.sysManagement.api.GetAPIsByGroupReq
	(*APITreeReq)(nil),            // 5: basis.sysManagement.api.APITreeReq
	(*APITreeItem)(nil),           // 6: basis.sysManagement.api.APITreeItem
	(*APITreeResp)(nil),           // 7: basis.sysManagement.api.APITreeResp
	(*common_pb.IdReq)(nil),       // 8: basis.common.IdReq
	(*common_pb.PageReq)(nil),     // 9: basis.common.PageReq
	(*common_pb.IdsReq)(nil),      // 10: basis.common.IdsReq
	(*common_pb.SuccessResp)(nil), // 11: basis.common.SuccessResp
}
var file_sysManagement_api_proto_depIdxs = []int32{
	2,  // 0: basis.sysManagement.api.ListAPIResp.list:type_name -> basis.sysManagement.api.APIResp
	2,  // 1: basis.sysManagement.api.APITreeItem.apis:type_name -> basis.sysManagement.api.APIResp
	6,  // 2: basis.sysManagement.api.APITreeResp.list:type_name -> basis.sysManagement.api.APITreeItem
	8,  // 3: basis.sysManagement.api.API.GetAPI:input_type -> basis.common.IdReq
	9,  // 4: basis.sysManagement.api.API.ListAPI:input_type -> basis.common.PageReq
	4,  // 5: basis.sysManagement.api.API.GetAPIsByGroup:input_type -> basis.sysManagement.api.GetAPIsByGroupReq
	0,  // 6: basis.sysManagement.api.API.CreateAPI:input_type -> basis.sysManagement.api.CreateAPIReq
	1,  // 7: basis.sysManagement.api.API.UpdateAPI:input_type -> basis.sysManagement.api.UpdateAPIReq
	8,  // 8: basis.sysManagement.api.API.DeleteAPI:input_type -> basis.common.IdReq
	10, // 9: basis.sysManagement.api.API.DeleteByIds:input_type -> basis.common.IdsReq
	5,  // 10: basis.sysManagement.api.API.GetAPITree:input_type -> basis.sysManagement.api.APITreeReq
	2,  // 11: basis.sysManagement.api.API.GetAPI:output_type -> basis.sysManagement.api.APIResp
	3,  // 12: basis.sysManagement.api.API.ListAPI:output_type -> basis.sysManagement.api.ListAPIResp
	3,  // 13: basis.sysManagement.api.API.GetAPIsByGroup:output_type -> basis.sysManagement.api.ListAPIResp
	11, // 14: basis.sysManagement.api.API.CreateAPI:output_type -> basis.common.SuccessResp
	2,  // 15: basis.sysManagement.api.API.UpdateAPI:output_type -> basis.sysManagement.api.APIResp
	11, // 16: basis.sysManagement.api.API.DeleteAPI:output_type -> basis.common.SuccessResp
	11, // 17: basis.sysManagement.api.API.DeleteByIds:output_type -> basis.common.SuccessResp
	7,  // 18: basis.sysManagement.api.API.GetAPITree:output_type -> basis.sysManagement.api.APITreeResp
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_sysManagement_api_proto_init() }
func file_sysManagement_api_proto_init() {
	if File_sysManagement_api_proto != nil {
		return
	}
	file_sysManagement_api_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysManagement_api_proto_rawDesc), len(file_sysManagement_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysManagement_api_proto_goTypes,
		DependencyIndexes: file_sysManagement_api_proto_depIdxs,
		MessageInfos:      file_sysManagement_api_proto_msgTypes,
	}.Build()
	File_sysManagement_api_proto = out.File
	file_sysManagement_api_proto_goTypes = nil
	file_sysManagement_api_proto_depIdxs = nil
}
