// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: tool/file.proto

package file_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileContent   []byte                 `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileReq) Reset() {
	*x = UploadFileReq{}
	mi := &file_tool_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileReq) ProtoMessage() {}

func (x *UploadFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_tool_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileReq.ProtoReflect.Descriptor instead.
func (*UploadFileReq) Descriptor() ([]byte, []int) {
	return file_tool_file_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileReq) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type UploadFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        uint64                 `protobuf:"varint,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FullPath      string                 `protobuf:"bytes,3,opt,name=full_path,json=fullPath,proto3" json:"full_path,omitempty"`
	Mime          string                 `protobuf:"bytes,4,opt,name=mime,proto3" json:"mime,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResp) Reset() {
	*x = UploadFileResp{}
	mi := &file_tool_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResp) ProtoMessage() {}

func (x *UploadFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_tool_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResp.ProtoReflect.Descriptor instead.
func (*UploadFileResp) Descriptor() ([]byte, []int) {
	return file_tool_file_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResp) GetFileId() uint64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *UploadFileResp) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadFileResp) GetFullPath() string {
	if x != nil {
		return x.FullPath
	}
	return ""
}

func (x *UploadFileResp) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *UploadFileResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FullPath      string                 `protobuf:"bytes,3,opt,name=full_path,json=fullPath,proto3" json:"full_path,omitempty"`
	Mime          string                 `protobuf:"bytes,4,opt,name=mime,proto3" json:"mime,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResp) Reset() {
	*x = FileResp{}
	mi := &file_tool_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResp) ProtoMessage() {}

func (x *FileResp) ProtoReflect() protoreflect.Message {
	mi := &file_tool_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResp.ProtoReflect.Descriptor instead.
func (*FileResp) Descriptor() ([]byte, []int) {
	return file_tool_file_proto_rawDescGZIP(), []int{2}
}

func (x *FileResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileResp) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileResp) GetFullPath() string {
	if x != nil {
		return x.FullPath
	}
	return ""
}

func (x *FileResp) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *FileResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileResp) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListFileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FileResp            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileResp) Reset() {
	*x = ListFileResp{}
	mi := &file_tool_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileResp) ProtoMessage() {}

func (x *ListFileResp) ProtoReflect() protoreflect.Message {
	mi := &file_tool_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileResp.ProtoReflect.Descriptor instead.
func (*ListFileResp) Descriptor() ([]byte, []int) {
	return file_tool_file_proto_rawDescGZIP(), []int{3}
}

func (x *ListFileResp) GetList() []*FileResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListFileResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_tool_file_proto protoreflect.FileDescriptor

const file_tool_file_proto_rawDesc = "" +
	"\n" +
	"\x0ftool/file.proto\x12\x0fbasis.tool.file\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n" +
	"\rUploadFileReq\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\ffile_content\x18\x02 \x01(\fR\vfileContent\"\x8b\x01\n" +
	"\x0eUploadFileResp\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\x04R\x06fileId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfull_path\x18\x03 \x01(\tR\bfullPath\x12\x12\n" +
	"\x04mime\x18\x04 \x01(\tR\x04mime\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\"\xde\x01\n" +
	"\bFileResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfull_path\x18\x03 \x01(\tR\bfullPath\x12\x12\n" +
	"\x04mime\x18\x04 \x01(\tR\x04mime\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"S\n" +
	"\fListFileResp\x12-\n" +
	"\x04list\x18\x01 \x03(\v2\x19.basis.tool.file.FileRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x90\x02\n" +
	"\x04File\x12M\n" +
	"\n" +
	"UploadFile\x12\x1e.basis.tool.file.UploadFileReq\x1a\x1f.basis.tool.file.UploadFileResp\x129\n" +
	"\aGetFile\x12\x13.basis.common.IdReq\x1a\x19.basis.tool.file.FileResp\x12@\n" +
	"\bListFile\x12\x15.basis.common.PageReq\x1a\x1d.basis.tool.file.ListFileResp\x12<\n" +
	"\n" +
	"DeleteFile\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessRespB+Z)td27/rpc/basis/types/tool/file_pb;file_pbb\x06proto3"

var (
	file_tool_file_proto_rawDescOnce sync.Once
	file_tool_file_proto_rawDescData []byte
)

func file_tool_file_proto_rawDescGZIP() []byte {
	file_tool_file_proto_rawDescOnce.Do(func() {
		file_tool_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tool_file_proto_rawDesc), len(file_tool_file_proto_rawDesc)))
	})
	return file_tool_file_proto_rawDescData
}

var file_tool_file_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tool_file_proto_goTypes = []any{
	(*UploadFileReq)(nil),         // 0: basis.tool.file.UploadFileReq
	(*UploadFileResp)(nil),        // 1: basis.tool.file.UploadFileResp
	(*FileResp)(nil),              // 2: basis.tool.file.FileResp
	(*ListFileResp)(nil),          // 3: basis.tool.file.ListFileResp
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*common_pb.IdReq)(nil),       // 5: basis.common.IdReq
	(*common_pb.PageReq)(nil),     // 6: basis.common.PageReq
	(*common_pb.SuccessResp)(nil), // 7: basis.common.SuccessResp
}
var file_tool_file_proto_depIdxs = []int32{
	4, // 0: basis.tool.file.FileResp.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: basis.tool.file.FileResp.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: basis.tool.file.ListFileResp.list:type_name -> basis.tool.file.FileResp
	0, // 3: basis.tool.file.File.UploadFile:input_type -> basis.tool.file.UploadFileReq
	5, // 4: basis.tool.file.File.GetFile:input_type -> basis.common.IdReq
	6, // 5: basis.tool.file.File.ListFile:input_type -> basis.common.PageReq
	5, // 6: basis.tool.file.File.DeleteFile:input_type -> basis.common.IdReq
	1, // 7: basis.tool.file.File.UploadFile:output_type -> basis.tool.file.UploadFileResp
	2, // 8: basis.tool.file.File.GetFile:output_type -> basis.tool.file.FileResp
	3, // 9: basis.tool.file.File.ListFile:output_type -> basis.tool.file.ListFileResp
	7, // 10: basis.tool.file.File.DeleteFile:output_type -> basis.common.SuccessResp
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tool_file_proto_init() }
func file_tool_file_proto_init() {
	if File_tool_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tool_file_proto_rawDesc), len(file_tool_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tool_file_proto_goTypes,
		DependencyIndexes: file_tool_file_proto_depIdxs,
		MessageInfos:      file_tool_file_proto_msgTypes,
	}.Build()
	File_tool_file_proto = out.File
	file_tool_file_proto_goTypes = nil
	file_tool_file_proto_depIdxs = nil
}
