// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.2
// source: sysManagement/permission.proto

package permission_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PermissionDomain int32

const (
	PermissionDomain_DOMAIN_MENU   PermissionDomain = 0
	PermissionDomain_DOMAIN_API    PermissionDomain = 1
	PermissionDomain_DOMAIN_BUTTON PermissionDomain = 2
	PermissionDomain_DOMAIN_DATA   PermissionDomain = 3
)

// Enum value maps for PermissionDomain.
var (
	PermissionDomain_name = map[int32]string{
		0: "DOMAIN_MENU",
		1: "DOMAIN_API",
		2: "DOMAIN_BUTTON",
		3: "DOMAIN_DATA",
	}
	PermissionDomain_value = map[string]int32{
		"DOMAIN_MENU":   0,
		"DOMAIN_API":    1,
		"DOMAIN_BUTTON": 2,
		"DOMAIN_DATA":   3,
	}
)

func (x PermissionDomain) Enum() *PermissionDomain {
	p := new(PermissionDomain)
	*p = x
	return p
}

func (x PermissionDomain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionDomain) Descriptor() protoreflect.EnumDescriptor {
	return file_sysManagement_permission_proto_enumTypes[0].Descriptor()
}

func (PermissionDomain) Type() protoreflect.EnumType {
	return &file_sysManagement_permission_proto_enumTypes[0]
}

func (x PermissionDomain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionDomain.Descriptor instead.
func (PermissionDomain) EnumDescriptor() ([]byte, []int) {
	return file_sysManagement_permission_proto_rawDescGZIP(), []int{0}
}

type Action int32

const (
	Action_ACTION_ALL     Action = 0
	Action_ACTION_VIEW    Action = 1
	Action_ACTION_READ    Action = 2
	Action_ACTION_CREATE  Action = 3
	Action_ACTION_UPDATE  Action = 4
	Action_ACTION_DELETE  Action = 5
	Action_ACTION_EXECUTE Action = 6
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_ALL",
		1: "ACTION_VIEW",
		2: "ACTION_READ",
		3: "ACTION_CREATE",
		4: "ACTION_UPDATE",
		5: "ACTION_DELETE",
		6: "ACTION_EXECUTE",
	}
	Action_value = map[string]int32{
		"ACTION_ALL":     0,
		"ACTION_VIEW":    1,
		"ACTION_READ":    2,
		"ACTION_CREATE":  3,
		"ACTION_UPDATE":  4,
		"ACTION_DELETE":  5,
		"ACTION_EXECUTE": 6,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_sysManagement_permission_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_sysManagement_permission_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_sysManagement_permission_proto_rawDescGZIP(), []int{1}
}

type PermissionEffect int32

const (
	PermissionEffect_EFFECT_ALLOW PermissionEffect = 0
	PermissionEffect_EFFECT_DENY  PermissionEffect = 1
)

// Enum value maps for PermissionEffect.
var (
	PermissionEffect_name = map[int32]string{
		0: "EFFECT_ALLOW",
		1: "EFFECT_DENY",
	}
	PermissionEffect_value = map[string]int32{
		"EFFECT_ALLOW": 0,
		"EFFECT_DENY":  1,
	}
)

func (x PermissionEffect) Enum() *PermissionEffect {
	p := new(PermissionEffect)
	*p = x
	return p
}

func (x PermissionEffect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionEffect) Descriptor() protoreflect.EnumDescriptor {
	return file_sysManagement_permission_proto_enumTypes[2].Descriptor()
}

func (PermissionEffect) Type() protoreflect.EnumType {
	return &file_sysManagement_permission_proto_enumTypes[2]
}

func (x PermissionEffect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionEffect.Descriptor instead.
func (PermissionEffect) EnumDescriptor() ([]byte, []int) {
	return file_sysManagement_permission_proto_rawDescGZIP(), []int{2}
}

type CreatePermissionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domain        PermissionDomain       `protobuf:"varint,2,opt,name=domain,proto3,enum=basis.sysManagement.permission.PermissionDomain" json:"domain,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        Action                 `protobuf:"varint,4,opt,name=action,proto3,enum=basis.sysManagement.permission.Action" json:"action,omitempty"`
	DomainId      int64                  `protobuf:"varint,5,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	Effect        PermissionEffect       `protobuf:"varint,6,opt,name=effect,proto3,enum=basis.sysManagement.permission.PermissionEffect" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionReq) Reset() {
	*x = CreatePermissionReq{}
	mi := &file_sysManagement_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionReq) ProtoMessage() {}

func (x *CreatePermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionReq.ProtoReflect.Descriptor instead.
func (*CreatePermissionReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_permission_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePermissionReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionReq) GetDomain() PermissionDomain {
	if x != nil {
		return x.Domain
	}
	return PermissionDomain_DOMAIN_MENU
}

func (x *CreatePermissionReq) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CreatePermissionReq) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_ALL
}

func (x *CreatePermissionReq) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *CreatePermissionReq) GetEffect() PermissionEffect {
	if x != nil {
		return x.Effect
	}
	return PermissionEffect_EFFECT_ALLOW
}

type UpdatePermissionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Domain        *PermissionDomain      `protobuf:"varint,3,opt,name=domain,proto3,enum=basis.sysManagement.permission.PermissionDomain,oneof" json:"domain,omitempty"`
	Resource      *string                `protobuf:"bytes,4,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
	Action        *Action                `protobuf:"varint,5,opt,name=action,proto3,enum=basis.sysManagement.permission.Action,oneof" json:"action,omitempty"`
	DomainId      *int64                 `protobuf:"varint,6,opt,name=domain_id,json=domainId,proto3,oneof" json:"domain_id,omitempty"`
	Effect        *PermissionEffect      `protobuf:"varint,7,opt,name=effect,proto3,enum=basis.sysManagement.permission.PermissionEffect,oneof" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionReq) Reset() {
	*x = UpdatePermissionReq{}
	mi := &file_sysManagement_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionReq) ProtoMessage() {}

func (x *UpdatePermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionReq.ProtoReflect.Descriptor instead.
func (*UpdatePermissionReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_permission_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePermissionReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePermissionReq) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdatePermissionReq) GetDomain() PermissionDomain {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return PermissionDomain_DOMAIN_MENU
}

func (x *UpdatePermissionReq) GetResource() string {
	if x != nil && x.Resource != nil {
		return *x.Resource
	}
	return ""
}

func (x *UpdatePermissionReq) GetAction() Action {
	if x != nil && x.Action != nil {
		return *x.Action
	}
	return Action_ACTION_ALL
}

func (x *UpdatePermissionReq) GetDomainId() int64 {
	if x != nil && x.DomainId != nil {
		return *x.DomainId
	}
	return 0
}

func (x *UpdatePermissionReq) GetEffect() PermissionEffect {
	if x != nil && x.Effect != nil {
		return *x.Effect
	}
	return PermissionEffect_EFFECT_ALLOW
}

type PermissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domain        PermissionDomain       `protobuf:"varint,3,opt,name=domain,proto3,enum=basis.sysManagement.permission.PermissionDomain" json:"domain,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        Action                 `protobuf:"varint,5,opt,name=action,proto3,enum=basis.sysManagement.permission.Action" json:"action,omitempty"`
	DomainId      int64                  `protobuf:"varint,6,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Effect        PermissionEffect       `protobuf:"varint,9,opt,name=effect,proto3,enum=basis.sysManagement.permission.PermissionEffect" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionResp) Reset() {
	*x = PermissionResp{}
	mi := &file_sysManagement_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResp) ProtoMessage() {}

func (x *PermissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResp.ProtoReflect.Descriptor instead.
func (*PermissionResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_permission_proto_rawDescGZIP(), []int{2}
}

func (x *PermissionResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PermissionResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionResp) GetDomain() PermissionDomain {
	if x != nil {
		return x.Domain
	}
	return PermissionDomain_DOMAIN_MENU
}

func (x *PermissionResp) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionResp) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_ALL
}

func (x *PermissionResp) GetDomainId() int64 {
	if x != nil {
		return x.DomainId
	}
	return 0
}

func (x *PermissionResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PermissionResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PermissionResp) GetEffect() PermissionEffect {
	if x != nil {
		return x.Effect
	}
	return PermissionEffect_EFFECT_ALLOW
}

type PolicyIssue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "conflict" (deny overrides an allow), "shadowed" (rule made redundant by a
	// broader rule), or "unassigned" (api permission not attached to any role).
	Severity      string `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoleId        int64  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  int64  `protobuf:"varint,4,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyIssue) Reset() {
	*x = PolicyIssue{}
	mi := &file_sysManagement_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyIssue) ProtoMessage() {}

func (x *PolicyIssue) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyIssue.ProtoReflect.Descriptor instead.
func (*PolicyIssue) Descriptor() ([]byte, []int) {
	return file_sysManagement_permission_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyIssue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *PolicyIssue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PolicyIssue) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *PolicyIssue) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

type LintPoliciesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issues        []*PolicyIssue         `protobuf:"bytes,1,rep,name=issues,proto3" json:"issues,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LintPoliciesResp) Reset() {
	*x = LintPoliciesResp{}
	mi := &file_sysManagement_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LintPoliciesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LintPoliciesResp) ProtoMessage() {}

func (x *LintPoliciesResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LintPoliciesResp.ProtoReflect.Descriptor instead.
func (*LintPoliciesResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_permission_proto_rawDescGZIP(), []int{4}
}

func (x *LintPoliciesResp) GetIssues() []*PolicyIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *LintPoliciesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListPermissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PermissionResp      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionResp) Reset() {
	*x = ListPermissionResp{}
	mi := &file_sysManagement_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionResp) ProtoMessage() {}

func (x *ListPermissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionResp.ProtoReflect.Descriptor instead.
func (*ListPermissionResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_permission_proto_rawDescGZIP(), []int{5}
}

func (x *ListPermissionResp) GetList() []*PermissionResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListPermissionResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CheckPermissionReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Role ids to check. Used when user_id is 0 (legacy callers).
	RoleIds  []int64 `protobuf:"varint,1,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	Resource string  `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action   Action  `protobuf:"varint,3,opt,name=action,proto3,enum=basis.sysManagement.permission.Action" json:"action,omitempty"`
	// When set, roles are resolved live from the database for this user,
	// ignoring role_ids (prevents stale grants embedded in JWTs).
	UserId        int64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionReq) Reset() {
	*x = CheckPermissionReq{}
	mi := &file_sysManagement_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionReq) ProtoMessage() {}

func (x *CheckPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionReq.ProtoReflect.Descriptor instead.
func (*CheckPermissionReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_permission_proto_rawDescGZIP(), []int{6}
}

func (x *CheckPermissionReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *CheckPermissionReq) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckPermissionReq) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_ALL
}

func (x *CheckPermissionReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CheckPermissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResp) Reset() {
	*x = CheckPermissionResp{}
	mi := &file_sysManagement_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResp) ProtoMessage() {}

func (x *CheckPermissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResp.ProtoReflect.Descriptor instead.
func (*CheckPermissionResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_permission_proto_rawDescGZIP(), []int{7}
}

func (x *CheckPermissionResp) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_sysManagement_permission_proto protoreflect.FileDescriptor

const file_sysManagement_permission_proto_rawDesc = "" +
	"\n" +
	"\x1esysManagement/permission.proto\x12\x1ebasis.sysManagement.permission\x1a\x13common/common.proto\"\xb6\x02\n" +
	"\x13CreatePermissionReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12H\n" +
	"\x06domain\x18\x02 \x01(\x0e20.basis.sysManagement.permission.PermissionDomainR\x06domain\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12>\n" +
	"\x06action\x18\x04 \x01(\x0e2&.basis.sysManagement.permission.ActionR\x06action\x12\x1b\n" +
	"\tdomain_id\x18\x05 \x01(\x03R\bdomainId\x12H\n" +
	"\x06effect\x18\x06 \x01(\x0e20.basis.sysManagement.permission.PermissionEffectR\x06effect\"\xa9\x03\n" +
	"\x13UpdatePermissionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12M\n" +
	"\x06domain\x18\x03 \x01(\x0e20.basis.sysManagement.permission.PermissionDomainH\x01R\x06domain\x88\x01\x01\x12\x1f\n" +
	"\bresource\x18\x04 \x01(\tH\x02R\bresource\x88\x01\x01\x12C\n" +
	"\x06action\x18\x05 \x01(\x0e2&.basis.sysManagement.permission.ActionH\x03R\x06action\x88\x01\x01\x12 \n" +
	"\tdomain_id\x18\x06 \x01(\x03H\x04R\bdomainId\x88\x01\x01\x12M\n" +
	"\x06effect\x18\a \x01(\x0e20.basis.sysManagement.permission.PermissionEffectH\x05R\x06effect\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_domainB\v\n" +
	"\t_resourceB\t\n" +
	"\a_actionB\f\n" +
	"\n" +
	"_domain_idB\t\n" +
	"\a_effect\"\xff\x02\n" +
	"\x0ePermissionResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12H\n" +
	"\x06domain\x18\x03 \x01(\x0e20.basis.sysManagement.permission.PermissionDomainR\x06domain\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12>\n" +
	"\x06action\x18\x05 \x01(\x0e2&.basis.sysManagement.permission.ActionR\x06action\x12\x1b\n" +
	"\tdomain_id\x18\x06 \x01(\x03R\bdomainId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12H\n" +
	"\x06effect\x18\t \x01(\x0e20.basis.sysManagement.permission.PermissionEffectR\x06effect\"\x81\x01\n" +
	"\vPolicyIssue\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x03R\x06roleId\x12#\n" +
	"\rpermission_id\x18\x04 \x01(\x03R\fpermissionId\"m\n" +
	"\x10LintPoliciesResp\x12C\n" +
	"\x06issues\x18\x01 \x03(\v2+.basis.sysManagement.permission.PolicyIssueR\x06issues\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"n\n" +
	"\x12ListPermissionResp\x12B\n" +
	"\x04list\x18\x01 \x03(\v2..basis.sysManagement.permission.PermissionRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa4\x01\n" +
	"\x12CheckPermissionReq\x12\x19\n" +
	"\brole_ids\x18\x01 \x03(\x03R\aroleIds\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12>\n" +
	"\x06action\x18\x03 \x01(\x0e2&.basis.sysManagement.permission.ActionR\x06action\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"/\n" +
	"\x13CheckPermissionResp\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed*W\n" +
	"\x10PermissionDomain\x12\x0f\n" +
	"\vDOMAIN_MENU\x10\x00\x12\x0e\n" +
	"\n" +
	"DOMAIN_API\x10\x01\x12\x11\n" +
	"\rDOMAIN_BUTTON\x10\x02\x12\x0f\n" +
	"\vDOMAIN_DATA\x10\x03*\x87\x01\n" +
	"\x06Action\x12\x0e\n" +
	"\n" +
	"ACTION_ALL\x10\x00\x12\x0f\n" +
	"\vACTION_VIEW\x10\x01\x12\x0f\n" +
	"\vACTION_READ\x10\x02\x12\x11\n" +
	"\rACTION_CREATE\x10\x03\x12\x11\n" +
	"\rACTION_UPDATE\x10\x04\x12\x11\n" +
	"\rACTION_DELETE\x10\x05\x12\x12\n" +
	"\x0eACTION_EXECUTE\x10\x06*5\n" +
	"\x10PermissionEffect\x12\x10\n" +
	"\fEFFECT_ALLOW\x10\x00\x12\x0f\n" +
	"\vEFFECT_DENY\x10\x012\xb4\a\n" +
	"\n" +
	"Permission\x12T\n" +
	"\rGetPermission\x12\x13.basis.common.IdReq\x1a..basis.sysManagement.permission.PermissionResp\x12[\n" +
	"\x0eListPermission\x12\x15.basis.common.PageReq\x1a2.basis.sysManagement.permission.ListPermissionResp\x12\\\n" +
	"\x11GetAllPermissions\x12\x13.basis.common.Empty\x1a2.basis.sysManagement.permission.ListPermissionResp\x12a\n" +
	"\x16GetPermissionsByRoleId\x12\x13.basis.common.IdReq\x1a2.basis.sysManagement.permission.ListPermissionResp\x12b\n" +
	"\x10CreatePermission\x123.basis.sysManagement.permission.CreatePermissionReq\x1a\x19.basis.common.SuccessResp\x12w\n" +
	"\x10UpdatePermission\x123.basis.sysManagement.permission.UpdatePermissionReq\x1a..basis.sysManagement.permission.PermissionResp\x12B\n" +
	"\x10DeletePermission\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessResp\x12z\n" +
	"\x0fCheckPermission\x122.basis.sysManagement.permission.CheckPermissionReq\x1a3.basis.sysManagement.permission.CheckPermissionResp\x12>\n" +
	"\fReloadPolicy\x12\x13.basis.common.Empty\x1a\x19.basis.common.SuccessResp\x12U\n" +
	"\fLintPolicies\x12\x13.basis.common.Empty\x1a0.basis.sysManagement.permission.LintPoliciesRespB@Z>td27/rpc/basis/types/sysManagement/permission_pb;permission_pbb\x06proto3"

var (
	file_sysManagement_permission_proto_rawDescOnce sync.Once
	file_sysManagement_permission_proto_rawDescData []byte
)

func file_sysManagement_permission_proto_rawDescGZIP() []byte {
	file_sysManagement_permission_proto_rawDescOnce.Do(func() {
		file_sysManagement_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysManagement_permission_proto_rawDesc), len(file_sysManagement_permission_proto_rawDesc)))
	})
	return file_sysManagement_permission_proto_rawDescData
}

var file_sysManagement_permission_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sysManagement_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sysManagement_permission_proto_goTypes = []any{
	(PermissionDomain)(0),         // 0: basis.sysManagement.permission.PermissionDomain
	(Action)(0),                   // 1: basis.sysManagement.permission.Action
	(PermissionEffect)(0),         // 2: basis.sysManagement.permission.PermissionEffect
	(*CreatePermissionReq)(nil),   // 3: basis.sysManagement.permission.CreatePermissionReq
	(*UpdatePermissionReq)(nil),   // 4: basis.sysManagement.permission.UpdatePermissionReq
	(*PermissionResp)(nil),        // 5: basis.sysManagement.permission.PermissionResp
	(*PolicyIssue)(nil),           // 6: basis.sysManagement.permission.PolicyIssue
	(*LintPoliciesResp)(nil),      // 7: basis.sysManagement.permission.LintPoliciesResp
	(*ListPermissionResp)(nil),    // 8: basis.sysManagement.permission.ListPermissionResp
	(*CheckPermissionReq)(nil),    // 9: basis.sysManagement.permission.CheckPermissionReq
	(*CheckPermissionResp)(nil),   // 10: basis.sysManagement.permission.CheckPermissionResp
	(*common_pb.IdReq)(nil),       // 11: basis.common.IdReq
	(*common_pb.PageReq)(nil),     // 12: basis.common.PageReq
	(*common_pb.Empty)(nil),       // 13: basis.common.Empty
	(*common_pb.SuccessResp)(nil), // 14: basis.common.SuccessResp
}
var file_sysManagement_permission_proto_depIdxs = []int32{
	0,  // 0: basis.sysManagement.permission.CreatePermissionReq.domain:type_name -> basis.sysManagement.permission.PermissionDomain
	1,  // 1: basis.sysManagement.permission.CreatePermissionReq.action:type_name -> basis.sysManagement.permission.Action
	2,  // 2: basis.sysManagement.permission.CreatePermissionReq.effect:type_name -> basis.sysManagement.permission.PermissionEffect
	0,  // 3: basis.sysManagement.permission.UpdatePermissionReq.domain:type_name -> basis.sysManagement.permission.PermissionDomain
	1,  // 4: basis.sysManagement.permission.UpdatePermissionReq.action:type_name -> basis.sysManagement.permission.Action
	2,  // 5: basis.sysManagement.permission.UpdatePermissionReq.effect:type_name -> basis.sysManagement.permission.PermissionEffect
	0,  // 6: basis.sysManagement.permission.PermissionResp.domain:type_name -> basis.sysManagement.permission.PermissionDomain
	1,  // 7: basis.sysManagement.permission.PermissionResp.action:type_name -> basis.sysManagement.permission.Action
	2,  // 8: basis.sysManagement.permission.PermissionResp.effect:type_name -> basis.sysManagement.permission.PermissionEffect
	6,  // 9: basis.sysManagement.permission.LintPoliciesResp.issues:type_name -> basis.sysManagement.permission.PolicyIssue
	5,  // 10: basis.sysManagement.permission.ListPermissionResp.list:type_name -> basis.sysManagement.permission.PermissionResp
	1,  // 11: basis.sysManagement.permission.CheckPermissionReq.action:type_name -> basis.sysManagement.permission.Action
	11, // 12: basis.sysManagement.permission.Permission.GetPermission:input_type -> basis.common.IdReq
	12, // 13: basis.sysManagement.permission.Permission.ListPermission:input_type -> basis.common.PageReq
	13, // 14: basis.sysManagement.permission.Permission.GetAllPermissions:input_type -> basis.common.Empty
	11, // 15: basis.sysManagement.permission.Permission.GetPermissionsByRoleId:input_type -> basis.common.IdReq
	3,  // 16: basis.sysManagement.permission.Permission.CreatePermission:input_type -> basis.sysManagement.permission.CreatePermissionReq
	4,  // 17: basis.sysManagement.permission.Permission.UpdatePermission:input_type -> basis.sysManagement.permission.UpdatePermissionReq
	11, // 18: basis.sysManagement.permission.Permission.DeletePermission:input_type -> basis.common.IdReq
	9,  // 19: basis.sysManagement.permission.Permission.CheckPermission:input_type -> basis.sysManagement.permission.CheckPermissionReq
	13, // 20: basis.sysManagement.permission.Permission.ReloadPolicy:input_type -> basis.common.Empty
	13, // 21: basis.sysManagement.permission.Permission.LintPolicies:input_type -> basis.common.Empty
	5,  // 22: basis.sysManagement.permission.Permission.GetPermission:output_type -> basis.sysManagement.permission.PermissionResp
	8,  // 23: basis.sysManagement.permission.Permission.ListPermission:output_type -> basis.sysManagement.permission.ListPermissionResp
	8,  // 24: basis.sysManagement.permission.Permission.GetAllPermissions:output_type -> basis.sysManagement.permission.ListPermissionResp
	8,  // 25: basis.sysManagement.permission.Permission.GetPermissionsByRoleId:output_type -> basis.sysManagement.permission.ListPermissionResp
	14, // 26: basis.sysManagement.permission.Permission.CreatePermission:output_type -> basis.common.SuccessResp
	5,  // 27: basis.sysManagement.permission.Permission.UpdatePermission:output_type -> basis.sysManagement.permission.PermissionResp
	14, // 28: basis.sysManagement.permission.Permission.DeletePermission:output_type -> basis.common.SuccessResp
	10, // 29: basis.sysManagement.permission.Permission.CheckPermission:output_type -> basis.sysManagement.permission.CheckPermissionResp
	14, // 30: basis.sysManagement.permission.Permission.ReloadPolicy:output_type -> basis.common.SuccessResp
	7,  // 31: basis.sysManagement.permission.Permission.LintPolicies:output_type -> basis.sysManagement.permission.LintPoliciesResp
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_sysManagement_permission_proto_init() }
func file_sysManagement_permission_proto_init() {
	if File_sysManagement_permission_proto != nil {
		return
	}
	file_sysManagement_permission_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysManagement_permission_proto_rawDesc), len(file_sysManagement_permission_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysManagement_permission_proto_goTypes,
		DependencyIndexes: file_sysManagement_permission_proto_depIdxs,
		EnumInfos:         file_sysManagement_permission_proto_enumTypes,
		MessageInfos:      file_sysManagement_permission_proto_msgTypes,
	}.Build()
	File_sysManagement_permission_proto = out.File
	file_sysManagement_permission_proto_goTypes = nil
	file_sysManagement_permission_proto_depIdxs = nil
}
