// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.2
// source: sysManagement/role.proto

package role_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common_pb "td27/rpc/basis/types/common_pb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Role_GetRole_FullMethodName                = "/basis.sysManagement.role.Role/GetRole"
	Role_GetRoleWithChildren_FullMethodName    = "/basis.sysManagement.role.Role/GetRoleWithChildren"
	Role_ListRole_FullMethodName               = "/basis.sysManagement.role.Role/ListRole"
	Role_GetAllRoles_FullMethodName            = "/basis.sysManagement.role.Role/GetAllRoles"
	Role_CreateRole_FullMethodName             = "/basis.sysManagement.role.Role/CreateRole"
	Role_UpdateRole_FullMethodName             = "/basis.sysManagement.role.Role/UpdateRole"
	Role_DeleteRole_FullMethodName             = "/basis.sysManagement.role.Role/DeleteRole"
	Role_AssignPermissions_FullMethodName      = "/basis.sysManagement.role.Role/AssignPermissions"
	Role_GetRolePermissions_FullMethodName     = "/basis.sysManagement.role.Role/GetRolePermissions"
	Role_CreateElevationRequest_FullMethodName = "/basis.sysManagement.role.Role/CreateElevationRequest"
	Role_DecideElevation_FullMethodName        = "/basis.sysManagement.role.Role/DecideElevation"
	Role_RevokeElevation_FullMethodName        = "/basis.sysManagement.role.Role/RevokeElevation"
	Role_ListElevations_FullMethodName         = "/basis.sysManagement.role.Role/ListElevations"
	Role_GetMyElevations_FullMethodName        = "/basis.sysManagement.role.Role/GetMyElevations"
)

// RoleClient is the client API for Role service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoleClient interface {
	GetRole(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*RoleResp, error)
	GetRoleWithChildren(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*RoleTreeResp, error)
	ListRole(ctx context.Context, in *common_pb.PageReq, opts ...grpc.CallOption) (*ListRoleResp, error)
	GetAllRoles(ctx context.Context, in *common_pb.Empty, opts ...grpc.CallOption) (*ListRoleResp, error)
	CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
	UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*RoleResp, error)
	DeleteRole(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
	AssignPermissions(ctx context.Context, in *AssignPermissionsReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
	GetRolePermissions(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*GetRolePermissionsResp, error)
	CreateElevationRequest(ctx context.Context, in *CreateElevationRequestReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
	DecideElevation(ctx context.Context, in *DecideElevationReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
	RevokeElevation(ctx context.Context, in *RevokeElevationReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
	ListElevations(ctx context.Context, in *common_pb.Empty, opts ...grpc.CallOption) (*ListElevationResp, error)
	GetMyElevations(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*ListElevationResp, error)
}

type roleClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleClient(cc grpc.ClientConnInterface) RoleClient {
	return &roleClient{cc}
}

func (c *roleClient) GetRole(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*RoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleResp)
	err := c.cc.Invoke(ctx, Role_GetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) GetRoleWithChildren(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*RoleTreeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleTreeResp)
	err := c.cc.Invoke(ctx, Role_GetRoleWithChildren_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) ListRole(ctx context.Context, in *common_pb.PageReq, opts ...grpc.CallOption) (*ListRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoleResp)
	err := c.cc.Invoke(ctx, Role_ListRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) GetAllRoles(ctx context.Context, in *common_pb.Empty, opts ...grpc.CallOption) (*ListRoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoleResp)
	err := c.cc.Invoke(ctx, Role_GetAllRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Role_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*RoleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoleResp)
	err := c.cc.Invoke(ctx, Role_UpdateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) DeleteRole(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Role_DeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) AssignPermissions(ctx context.Context, in *AssignPermissionsReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Role_AssignPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) GetRolePermissions(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*GetRolePermissionsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolePermissionsResp)
	err := c.cc.Invoke(ctx, Role_GetRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) CreateElevationRequest(ctx context.Context, in *CreateElevationRequestReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Role_CreateElevationRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) DecideElevation(ctx context.Context, in *DecideElevationReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Role_DecideElevation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) RevokeElevation(ctx context.Context, in *RevokeElevationReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Role_RevokeElevation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) ListElevations(ctx context.Context, in *common_pb.Empty, opts ...grpc.CallOption) (*ListElevationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListElevationResp)
	err := c.cc.Invoke(ctx, Role_ListElevations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) GetMyElevations(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*ListElevationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListElevationResp)
	err := c.cc.Invoke(ctx, Role_GetMyElevations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleServer is the server API for Role service.
// All implementations must embed UnimplementedRoleServer
// for forward compatibility.
type RoleServer interface {
	GetRole(context.Context, *common_pb.IdReq) (*RoleResp, error)
	GetRoleWithChildren(context.Context, *common_pb.IdReq) (*RoleTreeResp, error)
	ListRole(context.Context, *common_pb.PageReq) (*ListRoleResp, error)
	GetAllRoles(context.Context, *common_pb.Empty) (*ListRoleResp, error)
	CreateRole(context.Context, *CreateRoleReq) (*common_pb.SuccessResp, error)
	UpdateRole(context.Context, *UpdateRoleReq) (*RoleResp, error)
	DeleteRole(context.Context, *common_pb.IdReq) (*common_pb.SuccessResp, error)
	AssignPermissions(context.Context, *AssignPermissionsReq) (*common_pb.SuccessResp, error)
	GetRolePermissions(context.Context, *common_pb.IdReq) (*GetRolePermissionsResp, error)
	CreateElevationRequest(context.Context, *CreateElevationRequestReq) (*common_pb.SuccessResp, error)
	DecideElevation(context.Context, *DecideElevationReq) (*common_pb.SuccessResp, error)
	RevokeElevation(context.Context, *RevokeElevationReq) (*common_pb.SuccessResp, error)
	ListElevations(context.Context, *common_pb.Empty) (*ListElevationResp, error)
	GetMyElevations(context.Context, *common_pb.IdReq) (*ListElevationResp, error)
	mustEmbedUnimplementedRoleServer()
}

// UnimplementedRoleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoleServer struct{}

func (UnimplementedRoleServer) GetRole(context.Context, *common_pb.IdReq) (*RoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRole not implemented")
}
func (UnimplementedRoleServer) GetRoleWithChildren(context.Context, *common_pb.IdReq) (*RoleTreeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleWithChildren not implemented")
}
func (UnimplementedRoleServer) ListRole(context.Context, *common_pb.PageReq) (*ListRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRole not implemented")
}
func (UnimplementedRoleServer) GetAllRoles(context.Context, *common_pb.Empty) (*ListRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRoles not implemented")
}
func (UnimplementedRoleServer) CreateRole(context.Context, *CreateRoleReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedRoleServer) UpdateRole(context.Context, *UpdateRoleReq) (*RoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRole not implemented")
}
func (UnimplementedRoleServer) DeleteRole(context.Context, *common_pb.IdReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedRoleServer) AssignPermissions(context.Context, *AssignPermissionsReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignPermissions not implemented")
}
func (UnimplementedRoleServer) GetRolePermissions(context.Context, *common_pb.IdReq) (*GetRolePermissionsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRolePermissions not implemented")
}
func (UnimplementedRoleServer) CreateElevationRequest(context.Context, *CreateElevationRequestReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateElevationRequest not implemented")
}
func (UnimplementedRoleServer) DecideElevation(context.Context, *DecideElevationReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecideElevation not implemented")
}
func (UnimplementedRoleServer) RevokeElevation(context.Context, *RevokeElevationReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeElevation not implemented")
}
func (UnimplementedRoleServer) ListElevations(context.Context, *common_pb.Empty) (*ListElevationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListElevations not implemented")
}
func (UnimplementedRoleServer) GetMyElevations(context.Context, *common_pb.IdReq) (*ListElevationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyElevations not implemented")
}
func (UnimplementedRoleServer) mustEmbedUnimplementedRoleServer() {}
func (UnimplementedRoleServer) testEmbeddedByValue()              {}

// UnsafeRoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleServer will
// result in compilation errors.
type UnsafeRoleServer interface {
	mustEmbedUnimplementedRoleServer()
}

func RegisterRoleServer(s grpc.ServiceRegistrar, srv RoleServer) {
	// If the following call pancis, it indicates UnimplementedRoleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Role_ServiceDesc, srv)
}

func _Role_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_GetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).GetRole(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_GetRoleWithChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).GetRoleWithChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_GetRoleWithChildren_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).GetRoleWithChildren(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_ListRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.PageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).ListRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_ListRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).ListRole(ctx, req.(*common_pb.PageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_GetAllRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).GetAllRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_GetAllRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).GetAllRoles(ctx, req.(*common_pb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).CreateRole(ctx, req.(*CreateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_UpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).UpdateRole(ctx, req.(*UpdateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).DeleteRole(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_AssignPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignPermissionsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).AssignPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_AssignPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).AssignPermissions(ctx, req.(*AssignPermissionsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_GetRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).GetRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_GetRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).GetRolePermissions(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_CreateElevationRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateElevationRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).CreateElevationRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_CreateElevationRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).CreateElevationRequest(ctx, req.(*CreateElevationRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_DecideElevation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideElevationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).DecideElevation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_DecideElevation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).DecideElevation(ctx, req.(*DecideElevationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_RevokeElevation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeElevationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).RevokeElevation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_RevokeElevation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).RevokeElevation(ctx, req.(*RevokeElevationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_ListElevations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).ListElevations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_ListElevations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).ListElevations(ctx, req.(*common_pb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_GetMyElevations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).GetMyElevations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Role_GetMyElevations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).GetMyElevations(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Role_ServiceDesc is the grpc.ServiceDesc for Role service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Role_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basis.sysManagement.role.Role",
	HandlerType: (*RoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRole",
			Handler:    _Role_GetRole_Handler,
		},
		{
			MethodName: "GetRoleWithChildren",
			Handler:    _Role_GetRoleWithChildren_Handler,
		},
		{
			MethodName: "ListRole",
			Handler:    _Role_ListRole_Handler,
		},
		{
			MethodName: "GetAllRoles",
			Handler:    _Role_GetAllRoles_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _Role_CreateRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _Role_UpdateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _Role_DeleteRole_Handler,
		},
		{
			MethodName: "AssignPermissions",
			Handler:    _Role_AssignPermissions_Handler,
		},
		{
			MethodName: "GetRolePermissions",
			Handler:    _Role_GetRolePermissions_Handler,
		},
		{
			MethodName: "CreateElevationRequest",
			Handler:    _Role_CreateElevationRequest_Handler,
		},
		{
			MethodName: "DecideElevation",
			Handler:    _Role_DecideElevation_Handler,
		},
		{
			MethodName: "RevokeElevation",
			Handler:    _Role_RevokeElevation_Handler,
		},
		{
			MethodName: "ListElevations",
			Handler:    _Role_ListElevations_Handler,
		},
		{
			MethodName: "GetMyElevations",
			Handler:    _Role_GetMyElevations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sysManagement/role.proto",
}
