// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.2
// source: sysManagement/role.proto

package role_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	ParentId      *int64                 `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleReq) Reset() {
	*x = CreateRoleReq{}
	mi := &file_sysManagement_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleReq) ProtoMessage() {}

func (x *CreateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleReq.ProtoReflect.Descriptor instead.
func (*CreateRoleReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoleReq) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *CreateRoleReq) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

type UpdateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName      *string                `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3,oneof" json:"role_name,omitempty"`
	ParentId      *int64                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	mi := &file_sysManagement_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRoleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleReq) GetRoleName() string {
	if x != nil && x.RoleName != nil {
		return *x.RoleName
	}
	return ""
}

func (x *UpdateRoleReq) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

type RoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	ParentId      *int64                 `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResp) Reset() {
	*x = RoleResp{}
	mi := &file_sysManagement_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResp) ProtoMessage() {}

func (x *RoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResp.ProtoReflect.Descriptor instead.
func (*RoleResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{2}
}

func (x *RoleResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleResp) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleResp) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

func (x *RoleResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RoleTreeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *RoleResp              `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Children      []*RoleTreeResp        `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleTreeResp) Reset() {
	*x = RoleTreeResp{}
	mi := &file_sysManagement_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleTreeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleTreeResp) ProtoMessage() {}

func (x *RoleTreeResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleTreeResp.ProtoReflect.Descriptor instead.
func (*RoleTreeResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{3}
}

func (x *RoleTreeResp) GetRole() *RoleResp {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *RoleTreeResp) GetChildren() []*RoleTreeResp {
	if x != nil {
		return x.Children
	}
	return nil
}

type ListRoleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RoleResp            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleResp) Reset() {
	*x = ListRoleResp{}
	mi := &file_sysManagement_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleResp) ProtoMessage() {}

func (x *ListRoleResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleResp.ProtoReflect.Descriptor instead.
func (*ListRoleResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{4}
}

func (x *ListRoleResp) GetList() []*RoleResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListRoleResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AssignPermissionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionIds []int64                `protobuf:"varint,2,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionsReq) Reset() {
	*x = AssignPermissionsReq{}
	mi := &file_sysManagement_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionsReq) ProtoMessage() {}

func (x *AssignPermissionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionsReq.ProtoReflect.Descriptor instead.
func (*AssignPermissionsReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{5}
}

func (x *AssignPermissionsReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AssignPermissionsReq) GetPermissionIds() []int64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

type GetRolePermissionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionIds []int64                `protobuf:"varint,1,rep,packed,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsResp) Reset() {
	*x = GetRolePermissionsResp{}
	mi := &file_sysManagement_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsResp) ProtoMessage() {}

func (x *GetRolePermissionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsResp.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{6}
}

func (x *GetRolePermissionsResp) GetPermissionIds() []int64 {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

type CreateElevationRequestReq struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RoleId int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Reason string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// Requested window in minutes; clamped server-side (5 min .. 24 h).
	DurationMinutes int64 `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	// Requester identity, filled by the gateway from the JWT (never the body).
	UserId        int64 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateElevationRequestReq) Reset() {
	*x = CreateElevationRequestReq{}
	mi := &file_sysManagement_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateElevationRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateElevationRequestReq) ProtoMessage() {}

func (x *CreateElevationRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateElevationRequestReq.ProtoReflect.Descriptor instead.
func (*CreateElevationRequestReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{7}
}

func (x *CreateElevationRequestReq) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CreateElevationRequestReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CreateElevationRequestReq) GetDurationMinutes() int64 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *CreateElevationRequestReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DecideElevationReq struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Approve bool                   `protobuf:"varint,2,opt,name=approve,proto3" json:"approve,omitempty"`
	// Approver identity, filled by the gateway from the JWT (never the body).
	DecidedBy     int64 `protobuf:"varint,3,opt,name=decided_by,json=decidedBy,proto3" json:"decided_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideElevationReq) Reset() {
	*x = DecideElevationReq{}
	mi := &file_sysManagement_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideElevationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideElevationReq) ProtoMessage() {}

func (x *DecideElevationReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideElevationReq.ProtoReflect.Descriptor instead.
func (*DecideElevationReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{8}
}

func (x *DecideElevationReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DecideElevationReq) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

func (x *DecideElevationReq) GetDecidedBy() int64 {
	if x != nil {
		return x.DecidedBy
	}
	return 0
}

type RevokeElevationReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Revoker identity, filled by the gateway from the JWT (never the body).
	RevokedBy     int64 `protobuf:"varint,2,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeElevationReq) Reset() {
	*x = RevokeElevationReq{}
	mi := &file_sysManagement_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeElevationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeElevationReq) ProtoMessage() {}

func (x *RevokeElevationReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeElevationReq.ProtoReflect.Descriptor instead.
func (*RevokeElevationReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeElevationReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RevokeElevationReq) GetRevokedBy() int64 {
	if x != nil {
		return x.RevokedBy
	}
	return 0
}

type ElevationResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId          int64                  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Reason          string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	DurationMinutes int64                  `protobuf:"varint,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ElevationResp) Reset() {
	*x = ElevationResp{}
	mi := &file_sysManagement_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElevationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElevationResp) ProtoMessage() {}

func (x *ElevationResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElevationResp.ProtoReflect.Descriptor instead.
func (*ElevationResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{10}
}

func (x *ElevationResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ElevationResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ElevationResp) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ElevationResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ElevationResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ElevationResp) GetDurationMinutes() int64 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *ElevationResp) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *ElevationResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ElevationResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListElevationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ElevationResp       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListElevationResp) Reset() {
	*x = ListElevationResp{}
	mi := &file_sysManagement_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListElevationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListElevationResp) ProtoMessage() {}

func (x *ListElevationResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListElevationResp.ProtoReflect.Descriptor instead.
func (*ListElevationResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_role_proto_rawDescGZIP(), []int{11}
}

func (x *ListElevationResp) GetList() []*ElevationResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListElevationResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_sysManagement_role_proto protoreflect.FileDescriptor

const file_sysManagement_role_proto_rawDesc = "" +
	"\n" +
	"\x18sysManagement/role.proto\x12\x18basis.sysManagement.role\x1a\x13common/common.proto\"\\\n" +
	"\rCreateRoleReq\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12 \n" +
	"\tparent_id\x18\x02 \x01(\x03H\x00R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_id\"\x7f\n" +
	"\rUpdateRoleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\trole_name\x18\x02 \x01(\tH\x00R\broleName\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x03 \x01(\x03H\x01R\bparentId\x88\x01\x01B\f\n" +
	"\n" +
	"_role_nameB\f\n" +
	"\n" +
	"_parent_id\"\xa5\x01\n" +
	"\bRoleResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12 \n" +
	"\tparent_id\x18\x03 \x01(\x03H\x00R\bparentId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAtB\f\n" +
	"\n" +
	"_parent_id\"\x8a\x01\n" +
	"\fRoleTreeResp\x126\n" +
	"\x04role\x18\x01 \x01(\v2\".basis.sysManagement.role.RoleRespR\x04role\x12B\n" +
	"\bchildren\x18\x02 \x03(\v2&.basis.sysManagement.role.RoleTreeRespR\bchildren\"\\\n" +
	"\fListRoleResp\x126\n" +
	"\x04list\x18\x01 \x03(\v2\".basis.sysManagement.role.RoleRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"V\n" +
	"\x14AssignPermissionsReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12%\n" +
	"\x0epermission_ids\x18\x02 \x03(\x03R\rpermissionIds\"?\n" +
	"\x16GetRolePermissionsResp\x12%\n" +
	"\x0epermission_ids\x18\x01 \x03(\x03R\rpermissionIds\"\x90\x01\n" +
	"\x19CreateElevationRequestReq\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x03R\x0fdurationMinutes\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"]\n" +
	"\x12DecideElevationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aapprove\x18\x02 \x01(\bR\aapprove\x12\x1d\n" +
	"\n" +
	"decided_by\x18\x03 \x01(\x03R\tdecidedBy\"C\n" +
	"\x12RevokeElevationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x02 \x01(\x03R\trevokedBy\"\x89\x02\n" +
	"\rElevationResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x03R\x06roleId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12)\n" +
	"\x10duration_minutes\x18\x06 \x01(\x03R\x0fdurationMinutes\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"f\n" +
	"\x11ListElevationResp\x12;\n" +
	"\x04list\x18\x01 \x03(\v2'.basis.sysManagement.role.ElevationRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xa8\t\n" +
	"\x04Role\x12B\n" +
	"\aGetRole\x12\x13.basis.common.IdReq\x1a\".basis.sysManagement.role.RoleResp\x12R\n" +
	"\x13GetRoleWithChildren\x12\x13.basis.common.IdReq\x1a&.basis.sysManagement.role.RoleTreeResp\x12I\n" +
	"\bListRole\x12\x15.basis.common.PageReq\x1a&.basis.sysManagement.role.ListRoleResp\x12J\n" +
	"\vGetAllRoles\x12\x13.basis.common.Empty\x1a&.basis.sysManagement.role.ListRoleResp\x12P\n" +
	"\n" +
	"CreateRole\x12'.basis.sysManagement.role.CreateRoleReq\x1a\x19.basis.common.SuccessResp\x12Y\n" +
	"\n" +
	"UpdateRole\x12'.basis.sysManagement.role.UpdateRoleReq\x1a\".basis.sysManagement.role.RoleResp\x12<\n" +
	"\n" +
	"DeleteRole\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessResp\x12^\n" +
	"\x11AssignPermissions\x12..basis.sysManagement.role.AssignPermissionsReq\x1a\x19.basis.common.SuccessResp\x12[\n" +
	"\x12GetRolePermissions\x12\x13.basis.common.IdReq\x1a0.basis.sysManagement.role.GetRolePermissionsResp\x12h\n" +
	"\x16CreateElevationRequest\x123.basis.sysManagement.role.CreateElevationRequestReq\x1a\x19.basis.common.SuccessResp\x12Z\n" +
	"\x0fDecideElevation\x12,.basis.sysManagement.role.DecideElevationReq\x1a\x19.basis.common.SuccessResp\x12Z\n" +
	"\x0fRevokeElevation\x12,.basis.sysManagement.role.RevokeElevationReq\x1a\x19.basis.common.SuccessResp\x12R\n" +
	"\x0eListElevations\x12\x13.basis.common.Empty\x1a+.basis.sysManagement.role.ListElevationResp\x12S\n" +
	"\x0fGetMyElevations\x12\x13.basis.common.IdReq\x1a+.basis.sysManagement.role.ListElevationRespB4Z2td27/rpc/basis/types/sysManagement/role_pb;role_pbb\x06proto3"

var (
	file_sysManagement_role_proto_rawDescOnce sync.Once
	file_sysManagement_role_proto_rawDescData []byte
)

func file_sysManagement_role_proto_rawDescGZIP() []byte {
	file_sysManagement_role_proto_rawDescOnce.Do(func() {
		file_sysManagement_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysManagement_role_proto_rawDesc), len(file_sysManagement_role_proto_rawDesc)))
	})
	return file_sysManagement_role_proto_rawDescData
}

var file_sysManagement_role_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sysManagement_role_proto_goTypes = []any{
	(*CreateRoleReq)(nil),             // 0: basis.sysManagement.role.CreateRoleReq
	(*UpdateRoleReq)(nil),             // 1: basis.sysManagement.role.UpdateRoleReq
	(*RoleResp)(nil),                  // 2: basis.sysManagement.role.RoleResp
	(*RoleTreeResp)(nil),              // 3: basis.sysManagement.role.RoleTreeResp
	(*ListRoleResp)(nil),              // 4: basis.sysManagement.role.ListRoleResp
	(*AssignPermissionsReq)(nil),      // 5: basis.sysManagement.role.AssignPermissionsReq
	(*GetRolePermissionsResp)(nil),    // 6: basis.sysManagement.role.GetRolePermissionsResp
	(*CreateElevationRequestReq)(nil), // 7: basis.sysManagement.role.CreateElevationRequestReq
	(*DecideElevationReq)(nil),        // 8: basis.sysManagement.role.DecideElevationReq
	(*RevokeElevationReq)(nil),        // 9: basis.sysManagement.role.RevokeElevationReq
	(*ElevationResp)(nil),             // 10: basis.sysManagement.role.ElevationResp
	(*ListElevationResp)(nil),         // 11: basis.sysManagement.role.ListElevationResp
	(*common_pb.IdReq)(nil),           // 12: basis.common.IdReq
	(*common_pb.PageReq)(nil),         // 13: basis.common.PageReq
	(*common_pb.Empty)(nil),           // 14: basis.common.Empty
	(*common_pb.SuccessResp)(nil),     // 15: basis.common.SuccessResp
}
var file_sysManagement_role_proto_depIdxs = []int32{
	2,  // 0: basis.sysManagement.role.RoleTreeResp.role:type_name -> basis.sysManagement.role.RoleResp
	3,  // 1: basis.sysManagement.role.RoleTreeResp.children:type_name -> basis.sysManagement.role.RoleTreeResp
	2,  // 2: basis.sysManagement.role.ListRoleResp.list:type_name -> basis.sysManagement.role.RoleResp
	10, // 3: basis.sysManagement.role.ListElevationResp.list:type_name -> basis.sysManagement.role.ElevationResp
	12, // 4: basis.sysManagement.role.Role.GetRole:input_type -> basis.common.IdReq
	12, // 5: basis.sysManagement.role.Role.GetRoleWithChildren:input_type -> basis.common.IdReq
	13, // 6: basis.sysManagement.role.Role.ListRole:input_type -> basis.common.PageReq
	14, // 7: basis.sysManagement.role.Role.GetAllRoles:input_type -> basis.common.Empty
	0,  // 8: basis.sysManagement.role.Role.CreateRole:input_type -> basis.sysManagement.role.CreateRoleReq
	1,  // 9: basis.sysManagement.role.Role.UpdateRole:input_type -> basis.sysManagement.role.UpdateRoleReq
	12, // 10: basis.sysManagement.role.Role.DeleteRole:input_type -> basis.common.IdReq
	5,  // 11: basis.sysManagement.role.Role.AssignPermissions:input_type -> basis.sysManagement.role.AssignPermissionsReq
	12, // 12: basis.sysManagement.role.Role.GetRolePermissions:input_type -> basis.common.IdReq
	7,  // 13: basis.sysManagement.role.Role.CreateElevationRequest:input_type -> basis.sysManagement.role.CreateElevationRequestReq
	8,  // 14: basis.sysManagement.role.Role.DecideElevation:input_type -> basis.sysManagement.role.DecideElevationReq
	9,  // 15: basis.sysManagement.role.Role.RevokeElevation:input_type -> basis.sysManagement.role.RevokeElevationReq
	14, // 16: basis.sysManagement.role.Role.ListElevations:input_type -> basis.common.Empty
	12, // 17: basis.sysManagement.role.Role.GetMyElevations:input_type -> basis.common.IdReq
	2,  // 18: basis.sysManagement.role.Role.GetRole:output_type -> basis.sysManagement.role.RoleResp
	3,  // 19: basis.sysManagement.role.Role.GetRoleWithChildren:output_type -> basis.sysManagement.role.RoleTreeResp
	4,  // 20: basis.sysManagement.role.Role.ListRole:output_type -> basis.sysManagement.role.ListRoleResp
	4,  // 21: basis.sysManagement.role.Role.GetAllRoles:output_type -> basis.sysManagement.role.ListRoleResp
	15, // 22: basis.sysManagement.role.Role.CreateRole:output_type -> basis.common.SuccessResp
	2,  // 23: basis.sysManagement.role.Role.UpdateRole:output_type -> basis.sysManagement.role.RoleResp
	15, // 24: basis.sysManagement.role.Role.DeleteRole:output_type -> basis.common.SuccessResp
	15, // 25: basis.sysManagement.role.Role.AssignPermissions:output_type -> basis.common.SuccessResp
	6,  // 26: basis.sysManagement.role.Role.GetRolePermissions:output_type -> basis.sysManagement.role.GetRolePermissionsResp
	15, // 27: basis.sysManagement.role.Role.CreateElevationRequest:output_type -> basis.common.SuccessResp
	15, // 28: basis.sysManagement.role.Role.DecideElevation:output_type -> basis.common.SuccessResp
	15, // 29: basis.sysManagement.role.Role.RevokeElevation:output_type -> basis.common.SuccessResp
	11, // 30: basis.sysManagement.role.Role.ListElevations:output_type -> basis.sysManagement.role.ListElevationResp
	11, // 31: basis.sysManagement.role.Role.GetMyElevations:output_type -> basis.sysManagement.role.ListElevationResp
	18, // [18:32] is the sub-list for method output_type
	4,  // [4:18] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_sysManagement_role_proto_init() }
func file_sysManagement_role_proto_init() {
	if File_sysManagement_role_proto != nil {
		return
	}
	file_sysManagement_role_proto_msgTypes[0].OneofWrappers = []any{}
	file_sysManagement_role_proto_msgTypes[1].OneofWrappers = []any{}
	file_sysManagement_role_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysManagement_role_proto_rawDesc), len(file_sysManagement_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysManagement_role_proto_goTypes,
		DependencyIndexes: file_sysManagement_role_proto_depIdxs,
		MessageInfos:      file_sysManagement_role_proto_msgTypes,
	}.Build()
	File_sysManagement_role_proto = out.File
	file_sysManagement_role_proto_goTypes = nil
	file_sysManagement_role_proto_depIdxs = nil
}
