// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: authority/dict.proto

package dict_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common_pb "td27/rpc/basis/types/common_pb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Dict_GetDict_FullMethodName          = "/basis.authority.dict.Dict/GetDict"
	Dict_GetDictByENName_FullMethodName  = "/basis.authority.dict.Dict/GetDictByENName"
	Dict_ListDict_FullMethodName         = "/basis.authority.dict.Dict/ListDict"
	Dict_CreateDict_FullMethodName       = "/basis.authority.dict.Dict/CreateDict"
	Dict_UpdateDict_FullMethodName       = "/basis.authority.dict.Dict/UpdateDict"
	Dict_DeleteDict_FullMethodName       = "/basis.authority.dict.Dict/DeleteDict"
	Dict_CreateDictDetail_FullMethodName = "/basis.authority.dict.Dict/CreateDictDetail"
	Dict_UpdateDictDetail_FullMethodName = "/basis.authority.dict.Dict/UpdateDictDetail"
	Dict_DeleteDictDetail_FullMethodName = "/basis.authority.dict.Dict/DeleteDictDetail"
)

// DictClient is the client API for Dict service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DictClient interface {
	GetDict(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*DictResp, error)
	GetDictByENName(ctx context.Context, in *GetDictByENNameReq, opts ...grpc.CallOption) (*DictResp, error)
	ListDict(ctx context.Context, in *common_pb.PageReq, opts ...grpc.CallOption) (*ListDictResp, error)
	CreateDict(ctx context.Context, in *CreateDictReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
	UpdateDict(ctx context.Context, in *UpdateDictReq, opts ...grpc.CallOption) (*DictResp, error)
	DeleteDict(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
	CreateDictDetail(ctx context.Context, in *CreateDictDetailReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
	UpdateDictDetail(ctx context.Context, in *UpdateDictDetailReq, opts ...grpc.CallOption) (*DictDetailResp, error)
	DeleteDictDetail(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
}

type dictClient struct {
	cc grpc.ClientConnInterface
}

func NewDictClient(cc grpc.ClientConnInterface) DictClient {
	return &dictClient{cc}
}

func (c *dictClient) GetDict(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*DictResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictResp)
	err := c.cc.Invoke(ctx, Dict_GetDict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) GetDictByENName(ctx context.Context, in *GetDictByENNameReq, opts ...grpc.CallOption) (*DictResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictResp)
	err := c.cc.Invoke(ctx, Dict_GetDictByENName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) ListDict(ctx context.Context, in *common_pb.PageReq, opts ...grpc.CallOption) (*ListDictResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDictResp)
	err := c.cc.Invoke(ctx, Dict_ListDict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) CreateDict(ctx context.Context, in *CreateDictReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Dict_CreateDict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) UpdateDict(ctx context.Context, in *UpdateDictReq, opts ...grpc.CallOption) (*DictResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictResp)
	err := c.cc.Invoke(ctx, Dict_UpdateDict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) DeleteDict(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Dict_DeleteDict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) CreateDictDetail(ctx context.Context, in *CreateDictDetailReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Dict_CreateDictDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) UpdateDictDetail(ctx context.Context, in *UpdateDictDetailReq, opts ...grpc.CallOption) (*DictDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictDetailResp)
	err := c.cc.Invoke(ctx, Dict_UpdateDictDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictClient) DeleteDictDetail(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, Dict_DeleteDictDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictServer is the server API for Dict service.
// All implementations must embed UnimplementedDictServer
// for forward compatibility.
type DictServer interface {
	GetDict(context.Context, *common_pb.IdReq) (*DictResp, error)
	GetDictByENName(context.Context, *GetDictByENNameReq) (*DictResp, error)
	ListDict(context.Context, *common_pb.PageReq) (*ListDictResp, error)
	CreateDict(context.Context, *CreateDictReq) (*common_pb.SuccessResp, error)
	UpdateDict(context.Context, *UpdateDictReq) (*DictResp, error)
	DeleteDict(context.Context, *common_pb.IdReq) (*common_pb.SuccessResp, error)
	CreateDictDetail(context.Context, *CreateDictDetailReq) (*common_pb.SuccessResp, error)
	UpdateDictDetail(context.Context, *UpdateDictDetailReq) (*DictDetailResp, error)
	DeleteDictDetail(context.Context, *common_pb.IdReq) (*common_pb.SuccessResp, error)
	mustEmbedUnimplementedDictServer()
}

// UnimplementedDictServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDictServer struct{}

func (UnimplementedDictServer) GetDict(context.Context, *common_pb.IdReq) (*DictResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDict not implemented")
}
func (UnimplementedDictServer) GetDictByENName(context.Context, *GetDictByENNameReq) (*DictResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDictByENName not implemented")
}
func (UnimplementedDictServer) ListDict(context.Context, *common_pb.PageReq) (*ListDictResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDict not implemented")
}
func (UnimplementedDictServer) CreateDict(context.Context, *CreateDictReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDict not implemented")
}
func (UnimplementedDictServer) UpdateDict(context.Context, *UpdateDictReq) (*DictResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDict not implemented")
}
func (UnimplementedDictServer) DeleteDict(context.Context, *common_pb.IdReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDict not implemented")
}
func (UnimplementedDictServer) CreateDictDetail(context.Context, *CreateDictDetailReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDictDetail not implemented")
}
func (UnimplementedDictServer) UpdateDictDetail(context.Context, *UpdateDictDetailReq) (*DictDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDictDetail not implemented")
}
func (UnimplementedDictServer) DeleteDictDetail(context.Context, *common_pb.IdReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDictDetail not implemented")
}
func (UnimplementedDictServer) mustEmbedUnimplementedDictServer() {}
func (UnimplementedDictServer) testEmbeddedByValue()              {}

// UnsafeDictServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DictServer will
// result in compilation errors.
type UnsafeDictServer interface {
	mustEmbedUnimplementedDictServer()
}

func RegisterDictServer(s grpc.ServiceRegistrar, srv DictServer) {
	// If the following call pancis, it indicates UnimplementedDictServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Dict_ServiceDesc, srv)
}

func _Dict_GetDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).GetDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dict_GetDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).GetDict(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_GetDictByENName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDictByENNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).GetDictByENName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dict_GetDictByENName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).GetDictByENName(ctx, req.(*GetDictByENNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_ListDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.PageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).ListDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dict_ListDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).ListDict(ctx, req.(*common_pb.PageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_CreateDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDictReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).CreateDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dict_CreateDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).CreateDict(ctx, req.(*CreateDictReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_UpdateDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDictReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).UpdateDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dict_UpdateDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).UpdateDict(ctx, req.(*UpdateDictReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_DeleteDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).DeleteDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dict_DeleteDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).DeleteDict(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_CreateDictDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDictDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).CreateDictDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dict_CreateDictDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).CreateDictDetail(ctx, req.(*CreateDictDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_UpdateDictDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDictDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).UpdateDictDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dict_UpdateDictDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).UpdateDictDetail(ctx, req.(*UpdateDictDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dict_DeleteDictDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServer).DeleteDictDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Dict_DeleteDictDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServer).DeleteDictDetail(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Dict_ServiceDesc is the grpc.ServiceDesc for Dict service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dict_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basis.authority.dict.Dict",
	HandlerType: (*DictServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDict",
			Handler:    _Dict_GetDict_Handler,
		},
		{
			MethodName: "GetDictByENName",
			Handler:    _Dict_GetDictByENName_Handler,
		},
		{
			MethodName: "ListDict",
			Handler:    _Dict_ListDict_Handler,
		},
		{
			MethodName: "CreateDict",
			Handler:    _Dict_CreateDict_Handler,
		},
		{
			MethodName: "UpdateDict",
			Handler:    _Dict_UpdateDict_Handler,
		},
		{
			MethodName: "DeleteDict",
			Handler:    _Dict_DeleteDict_Handler,
		},
		{
			MethodName: "CreateDictDetail",
			Handler:    _Dict_CreateDictDetail_Handler,
		},
		{
			MethodName: "UpdateDictDetail",
			Handler:    _Dict_UpdateDictDetail_Handler,
		},
		{
			MethodName: "DeleteDictDetail",
			Handler:    _Dict_DeleteDictDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authority/dict.proto",
}
