// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: authority/dict.proto

package dict_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDictReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CnName        string                 `protobuf:"bytes,1,opt,name=cn_name,json=cnName,proto3" json:"cn_name,omitempty"`
	EnName        string                 `protobuf:"bytes,2,opt,name=en_name,json=enName,proto3" json:"en_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictReq) Reset() {
	*x = CreateDictReq{}
	mi := &file_authority_dict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictReq) ProtoMessage() {}

func (x *CreateDictReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictReq.ProtoReflect.Descriptor instead.
func (*CreateDictReq) Descriptor() ([]byte, []int) {
	return file_authority_dict_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDictReq) GetCnName() string {
	if x != nil {
		return x.CnName
	}
	return ""
}

func (x *CreateDictReq) GetEnName() string {
	if x != nil {
		return x.EnName
	}
	return ""
}

type UpdateDictReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CnName        *string                `protobuf:"bytes,2,opt,name=cn_name,json=cnName,proto3,oneof" json:"cn_name,omitempty"`
	EnName        *string                `protobuf:"bytes,3,opt,name=en_name,json=enName,proto3,oneof" json:"en_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictReq) Reset() {
	*x = UpdateDictReq{}
	mi := &file_authority_dict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictReq) ProtoMessage() {}

func (x *UpdateDictReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictReq.ProtoReflect.Descriptor instead.
func (*UpdateDictReq) Descriptor() ([]byte, []int) {
	return file_authority_dict_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateDictReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDictReq) GetCnName() string {
	if x != nil && x.CnName != nil {
		return *x.CnName
	}
	return ""
}

func (x *UpdateDictReq) GetEnName() string {
	if x != nil && x.EnName != nil {
		return *x.EnName
	}
	return ""
}

type DictDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictDetailResp) Reset() {
	*x = DictDetailResp{}
	mi := &file_authority_dict_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictDetailResp) ProtoMessage() {}

func (x *DictDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dict_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictDetailResp.ProtoReflect.Descriptor instead.
func (*DictDetailResp) Descriptor() ([]byte, []int) {
	return file_authority_dict_proto_rawDescGZIP(), []int{2}
}

func (x *DictDetailResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DictDetailResp) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DictDetailResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *DictDetailResp) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *DictDetailResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DictDetailResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DictDetailResp) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DictResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CnName        string                 `protobuf:"bytes,2,opt,name=cn_name,json=cnName,proto3" json:"cn_name,omitempty"`
	EnName        string                 `protobuf:"bytes,3,opt,name=en_name,json=enName,proto3" json:"en_name,omitempty"`
	Details       []*DictDetailResp      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictResp) Reset() {
	*x = DictResp{}
	mi := &file_authority_dict_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictResp) ProtoMessage() {}

func (x *DictResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dict_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictResp.ProtoReflect.Descriptor instead.
func (*DictResp) Descriptor() ([]byte, []int) {
	return file_authority_dict_proto_rawDescGZIP(), []int{3}
}

func (x *DictResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DictResp) GetCnName() string {
	if x != nil {
		return x.CnName
	}
	return ""
}

func (x *DictResp) GetEnName() string {
	if x != nil {
		return x.EnName
	}
	return ""
}

func (x *DictResp) GetDetails() []*DictDetailResp {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *DictResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DictResp) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListDictResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*DictResp            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictResp) Reset() {
	*x = ListDictResp{}
	mi := &file_authority_dict_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictResp) ProtoMessage() {}

func (x *ListDictResp) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dict_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictResp.ProtoReflect.Descriptor instead.
func (*ListDictResp) Descriptor() ([]byte, []int) {
	return file_authority_dict_proto_rawDescGZIP(), []int{4}
}

func (x *ListDictResp) GetList() []*DictResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListDictResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetDictByENNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnName        string                 `protobuf:"bytes,1,opt,name=en_name,json=enName,proto3" json:"en_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDictByENNameReq) Reset() {
	*x = GetDictByENNameReq{}
	mi := &file_authority_dict_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDictByENNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictByENNameReq) ProtoMessage() {}

func (x *GetDictByENNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dict_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictByENNameReq.ProtoReflect.Descriptor instead.
func (*GetDictByENNameReq) Descriptor() ([]byte, []int) {
	return file_authority_dict_proto_rawDescGZIP(), []int{5}
}

func (x *GetDictByENNameReq) GetEnName() string {
	if x != nil {
		return x.EnName
	}
	return ""
}

type CreateDictDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        uint64                 `protobuf:"varint,1,opt,name=dict_id,json=dictId,proto3" json:"dict_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Sort          *int32                 `protobuf:"varint,4,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ParentId      *int64                 `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictDetailReq) Reset() {
	*x = CreateDictDetailReq{}
	mi := &file_authority_dict_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictDetailReq) ProtoMessage() {}

func (x *CreateDictDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dict_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictDetailReq.ProtoReflect.Descriptor instead.
func (*CreateDictDetailReq) Descriptor() ([]byte, []int) {
	return file_authority_dict_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDictDetailReq) GetDictId() uint64 {
	if x != nil {
		return x.DictId
	}
	return 0
}

func (x *CreateDictDetailReq) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateDictDetailReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateDictDetailReq) GetSort() int32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *CreateDictDetailReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateDictDetailReq) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

type UpdateDictDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         *string                `protobuf:"bytes,2,opt,name=label,proto3,oneof" json:"label,omitempty"`
	Value         *string                `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Sort          *int32                 `protobuf:"varint,4,opt,name=sort,proto3,oneof" json:"sort,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ParentId      *int64                 `protobuf:"varint,6,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictDetailReq) Reset() {
	*x = UpdateDictDetailReq{}
	mi := &file_authority_dict_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictDetailReq) ProtoMessage() {}

func (x *UpdateDictDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_authority_dict_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictDetailReq.ProtoReflect.Descriptor instead.
func (*UpdateDictDetailReq) Descriptor() ([]byte, []int) {
	return file_authority_dict_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDictDetailReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDictDetailReq) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *UpdateDictDetailReq) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *UpdateDictDetailReq) GetSort() int32 {
	if x != nil && x.Sort != nil {
		return *x.Sort
	}
	return 0
}

func (x *UpdateDictDetailReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateDictDetailReq) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

var File_authority_dict_proto protoreflect.FileDescriptor

const file_authority_dict_proto_rawDesc = "" +
	"\n" +
	"\x14authority/dict.proto\x12\x14basis.authority.dict\x1a\x13common/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\rCreateDictReq\x12\x17\n" +
	"\acn_name\x18\x01 \x01(\tR\x06cnName\x12\x17\n" +
	"\aen_name\x18\x02 \x01(\tR\x06enName\"s\n" +
	"\rUpdateDictReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\acn_name\x18\x02 \x01(\tH\x00R\x06cnName\x88\x01\x01\x12\x1c\n" +
	"\aen_name\x18\x03 \x01(\tH\x01R\x06enName\x88\x01\x01B\n" +
	"\n" +
	"\b_cn_nameB\n" +
	"\n" +
	"\b_en_name\"\xf8\x01\n" +
	"\x0eDictDetailResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x82\x02\n" +
	"\bDictResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\acn_name\x18\x02 \x01(\tR\x06cnName\x12\x17\n" +
	"\aen_name\x18\x03 \x01(\tR\x06enName\x12>\n" +
	"\adetails\x18\x04 \x03(\v2$.basis.authority.dict.DictDetailRespR\adetails\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"X\n" +
	"\fListDictResp\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.basis.authority.dict.DictRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"-\n" +
	"\x12GetDictByENNameReq\x12\x17\n" +
	"\aen_name\x18\x01 \x01(\tR\x06enName\"\xe3\x01\n" +
	"\x13CreateDictDetailReq\x12\x17\n" +
	"\adict_id\x18\x01 \x01(\x04R\x06dictId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x17\n" +
	"\x04sort\x18\x04 \x01(\x05H\x00R\x04sort\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x01R\vdescription\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x06 \x01(\x03H\x02R\bparentId\x88\x01\x01B\a\n" +
	"\x05_sortB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_parent_id\"\xf8\x01\n" +
	"\x13UpdateDictDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\x05label\x18\x02 \x01(\tH\x00R\x05label\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x03 \x01(\tH\x01R\x05value\x88\x01\x01\x12\x17\n" +
	"\x04sort\x18\x04 \x01(\x05H\x02R\x04sort\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x03R\vdescription\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\x06 \x01(\x03H\x04R\bparentId\x88\x01\x01B\b\n" +
	"\x06_labelB\b\n" +
	"\x06_valueB\a\n" +
	"\x05_sortB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_parent_id2\xcc\x05\n" +
	"\x04Dict\x12>\n" +
	"\aGetDict\x12\x13.basis.common.IdReq\x1a\x1e.basis.authority.dict.DictResp\x12[\n" +
	"\x0fGetDictByENName\x12(.basis.authority.dict.GetDictByENNameReq\x1a\x1e.basis.authority.dict.DictResp\x12E\n" +
	"\bListDict\x12\x15.basis.common.PageReq\x1a\".basis.authority.dict.ListDictResp\x12L\n" +
	"\n" +
	"CreateDict\x12#.basis.authority.dict.CreateDictReq\x1a\x19.basis.common.SuccessResp\x12Q\n" +
	"\n" +
	"UpdateDict\x12#.basis.authority.dict.UpdateDictReq\x1a\x1e.basis.authority.dict.DictResp\x12<\n" +
	"\n" +
	"DeleteDict\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessResp\x12X\n" +
	"\x10CreateDictDetail\x12).basis.authority.dict.CreateDictDetailReq\x1a\x19.basis.common.SuccessResp\x12c\n" +
	"\x10UpdateDictDetail\x12).basis.authority.dict.UpdateDictDetailReq\x1a$.basis.authority.dict.DictDetailResp\x12B\n" +
	"\x10DeleteDictDetail\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessRespB0Z.td27/rpc/basis/types/authority/dict_pb;dict_pbb\x06proto3"

var (
	file_authority_dict_proto_rawDescOnce sync.Once
	file_authority_dict_proto_rawDescData []byte
)

func file_authority_dict_proto_rawDescGZIP() []byte {
	file_authority_dict_proto_rawDescOnce.Do(func() {
		file_authority_dict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authority_dict_proto_rawDesc), len(file_authority_dict_proto_rawDesc)))
	})
	return file_authority_dict_proto_rawDescData
}

var file_authority_dict_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_authority_dict_proto_goTypes = []any{
	(*CreateDictReq)(nil),         // 0: basis.authority.dict.CreateDictReq
	(*UpdateDictReq)(nil),         // 1: basis.authority.dict.UpdateDictReq
	(*DictDetailResp)(nil),        // 2: basis.authority.dict.DictDetailResp
	(*DictResp)(nil),              // 3: basis.authority.dict.DictResp
	(*ListDictResp)(nil),          // 4: basis.authority.dict.ListDictResp
	(*GetDictByENNameReq)(nil),    // 5: basis.authority.dict.GetDictByENNameReq
	(*CreateDictDetailReq)(nil),   // 6: basis.authority.dict.CreateDictDetailReq
	(*UpdateDictDetailReq)(nil),   // 7: basis.authority.dict.UpdateDictDetailReq
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*common_pb.IdReq)(nil),       // 9: basis.common.IdReq
	(*common_pb.PageReq)(nil),     // 10: basis.common.PageReq
	(*common_pb.SuccessResp)(nil), // 11: basis.common.SuccessResp
}
var file_authority_dict_proto_depIdxs = []int32{
	8,  // 0: basis.authority.dict.DictDetailResp.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: basis.authority.dict.DictDetailResp.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: basis.authority.dict.DictResp.details:type_name -> basis.authority.dict.DictDetailResp
	8,  // 3: basis.authority.dict.DictResp.created_at:type_name -> google.protobuf.Timestamp
	8,  // 4: basis.authority.dict.DictResp.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 5: basis.authority.dict.ListDictResp.list:type_name -> basis.authority.dict.DictResp
	9,  // 6: basis.authority.dict.Dict.GetDict:input_type -> basis.common.IdReq
	5,  // 7: basis.authority.dict.Dict.GetDictByENName:input_type -> basis.authority.dict.GetDictByENNameReq
	10, // 8: basis.authority.dict.Dict.ListDict:input_type -> basis.common.PageReq
	0,  // 9: basis.authority.dict.Dict.CreateDict:input_type -> basis.authority.dict.CreateDictReq
	1,  // 10: basis.authority.dict.Dict.UpdateDict:input_type -> basis.authority.dict.UpdateDictReq
	9,  // 11: basis.authority.dict.Dict.DeleteDict:input_type -> basis.common.IdReq
	6,  // 12: basis.authority.dict.Dict.CreateDictDetail:input_type -> basis.authority.dict.CreateDictDetailReq
	7,  // 13: basis.authority.dict.Dict.UpdateDictDetail:input_type -> basis.authority.dict.UpdateDictDetailReq
	9,  // 14: basis.authority.dict.Dict.DeleteDictDetail:input_type -> basis.common.IdReq
	3,  // 15: basis.authority.dict.Dict.GetDict:output_type -> basis.authority.dict.DictResp
	3,  // 16: basis.authority.dict.Dict.GetDictByENName:output_type -> basis.authority.dict.DictResp
	4,  // 17: basis.authority.dict.Dict.ListDict:output_type -> basis.authority.dict.ListDictResp
	11, // 18: basis.authority.dict.Dict.CreateDict:output_type -> basis.common.SuccessResp
	3,  // 19: basis.authority.dict.Dict.UpdateDict:output_type -> basis.authority.dict.DictResp
	11, // 20: basis.authority.dict.Dict.DeleteDict:output_type -> basis.common.SuccessResp
	11, // 21: basis.authority.dict.Dict.CreateDictDetail:output_type -> basis.common.SuccessResp
	2,  // 22: basis.authority.dict.Dict.UpdateDictDetail:output_type -> basis.authority.dict.DictDetailResp
	11, // 23: basis.authority.dict.Dict.DeleteDictDetail:output_type -> basis.common.SuccessResp
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_authority_dict_proto_init() }
func file_authority_dict_proto_init() {
	if File_authority_dict_proto != nil {
		return
	}
	file_authority_dict_proto_msgTypes[1].OneofWrappers = []any{}
	file_authority_dict_proto_msgTypes[6].OneofWrappers = []any{}
	file_authority_dict_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authority_dict_proto_rawDesc), len(file_authority_dict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authority_dict_proto_goTypes,
		DependencyIndexes: file_authority_dict_proto_depIdxs,
		MessageInfos:      file_authority_dict_proto_msgTypes,
	}.Build()
	File_authority_dict_proto = out.File
	file_authority_dict_proto_goTypes = nil
	file_authority_dict_proto_depIdxs = nil
}
