// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: authority/api.proto

package api_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common_pb "td27/rpc/basis/types/common_pb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	API_GetAPI_FullMethodName         = "/basis.authority.api.API/GetAPI"
	API_ListAPI_FullMethodName        = "/basis.authority.api.API/ListAPI"
	API_GetAPIsByGroup_FullMethodName = "/basis.authority.api.API/GetAPIsByGroup"
	API_CreateAPI_FullMethodName      = "/basis.authority.api.API/CreateAPI"
	API_UpdateAPI_FullMethodName      = "/basis.authority.api.API/UpdateAPI"
	API_DeleteAPI_FullMethodName      = "/basis.authority.api.API/DeleteAPI"
)

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIClient interface {
	GetAPI(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*APIResp, error)
	ListAPI(ctx context.Context, in *common_pb.PageReq, opts ...grpc.CallOption) (*ListAPIResp, error)
	GetAPIsByGroup(ctx context.Context, in *GetAPIsByGroupReq, opts ...grpc.CallOption) (*ListAPIResp, error)
	CreateAPI(ctx context.Context, in *CreateAPIReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
	UpdateAPI(ctx context.Context, in *UpdateAPIReq, opts ...grpc.CallOption) (*APIResp, error)
	DeleteAPI(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) GetAPI(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*APIResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIResp)
	err := c.cc.Invoke(ctx, API_GetAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListAPI(ctx context.Context, in *common_pb.PageReq, opts ...grpc.CallOption) (*ListAPIResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAPIResp)
	err := c.cc.Invoke(ctx, API_ListAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetAPIsByGroup(ctx context.Context, in *GetAPIsByGroupReq, opts ...grpc.CallOption) (*ListAPIResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAPIResp)
	err := c.cc.Invoke(ctx, API_GetAPIsByGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateAPI(ctx context.Context, in *CreateAPIReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, API_CreateAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateAPI(ctx context.Context, in *UpdateAPIReq, opts ...grpc.CallOption) (*APIResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIResp)
	err := c.cc.Invoke(ctx, API_UpdateAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteAPI(ctx context.Context, in *common_pb.IdReq, opts ...grpc.CallOption) (*common_pb.SuccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common_pb.SuccessResp)
	err := c.cc.Invoke(ctx, API_DeleteAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility.
type APIServer interface {
	GetAPI(context.Context, *common_pb.IdReq) (*APIResp, error)
	ListAPI(context.Context, *common_pb.PageReq) (*ListAPIResp, error)
	GetAPIsByGroup(context.Context, *GetAPIsByGroupReq) (*ListAPIResp, error)
	CreateAPI(context.Context, *CreateAPIReq) (*common_pb.SuccessResp, error)
	UpdateAPI(context.Context, *UpdateAPIReq) (*APIResp, error)
	DeleteAPI(context.Context, *common_pb.IdReq) (*common_pb.SuccessResp, error)
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIServer struct{}

func (UnimplementedAPIServer) GetAPI(context.Context, *common_pb.IdReq) (*APIResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAPI not implemented")
}
func (UnimplementedAPIServer) ListAPI(context.Context, *common_pb.PageReq) (*ListAPIResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAPI not implemented")
}
func (UnimplementedAPIServer) GetAPIsByGroup(context.Context, *GetAPIsByGroupReq) (*ListAPIResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAPIsByGroup not implemented")
}
func (UnimplementedAPIServer) CreateAPI(context.Context, *CreateAPIReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAPI not implemented")
}
func (UnimplementedAPIServer) UpdateAPI(context.Context, *UpdateAPIReq) (*APIResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAPI not implemented")
}
func (UnimplementedAPIServer) DeleteAPI(context.Context, *common_pb.IdReq) (*common_pb.SuccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAPI not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}
func (UnimplementedAPIServer) testEmbeddedByValue()             {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	// If the following call pancis, it indicates UnimplementedAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_GetAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_GetAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetAPI(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.PageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_ListAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListAPI(ctx, req.(*common_pb.PageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetAPIsByGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAPIsByGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetAPIsByGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_GetAPIsByGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetAPIsByGroup(ctx, req.(*GetAPIsByGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAPIReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_CreateAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateAPI(ctx, req.(*CreateAPIReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAPIReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_UpdateAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateAPI(ctx, req.(*UpdateAPIReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common_pb.IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_DeleteAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteAPI(ctx, req.(*common_pb.IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basis.authority.api.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAPI",
			Handler:    _API_GetAPI_Handler,
		},
		{
			MethodName: "ListAPI",
			Handler:    _API_ListAPI_Handler,
		},
		{
			MethodName: "GetAPIsByGroup",
			Handler:    _API_GetAPIsByGroup_Handler,
		},
		{
			MethodName: "CreateAPI",
			Handler:    _API_CreateAPI_Handler,
		},
		{
			MethodName: "UpdateAPI",
			Handler:    _API_UpdateAPI_Handler,
		},
		{
			MethodName: "DeleteAPI",
			Handler:    _API_DeleteAPI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authority/api.proto",
}
