// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: sysManagement/button.proto

package button_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	common_pb "td27/rpc/basis/types/common_pb"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateButtonReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ButtonCode    string                 `protobuf:"bytes,1,opt,name=button_code,json=buttonCode,proto3" json:"button_code,omitempty"`
	ButtonName    string                 `protobuf:"bytes,2,opt,name=button_name,json=buttonName,proto3" json:"button_name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	PagePath      string                 `protobuf:"bytes,4,opt,name=page_path,json=pagePath,proto3" json:"page_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateButtonReq) Reset() {
	*x = CreateButtonReq{}
	mi := &file_sysManagement_button_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateButtonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateButtonReq) ProtoMessage() {}

func (x *CreateButtonReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_button_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateButtonReq.ProtoReflect.Descriptor instead.
func (*CreateButtonReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_button_proto_rawDescGZIP(), []int{0}
}

func (x *CreateButtonReq) GetButtonCode() string {
	if x != nil {
		return x.ButtonCode
	}
	return ""
}

func (x *CreateButtonReq) GetButtonName() string {
	if x != nil {
		return x.ButtonName
	}
	return ""
}

func (x *CreateButtonReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateButtonReq) GetPagePath() string {
	if x != nil {
		return x.PagePath
	}
	return ""
}

type UpdateButtonReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ButtonCode    *string                `protobuf:"bytes,2,opt,name=button_code,json=buttonCode,proto3,oneof" json:"button_code,omitempty"`
	ButtonName    *string                `protobuf:"bytes,3,opt,name=button_name,json=buttonName,proto3,oneof" json:"button_name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	PagePath      *string                `protobuf:"bytes,5,opt,name=page_path,json=pagePath,proto3,oneof" json:"page_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateButtonReq) Reset() {
	*x = UpdateButtonReq{}
	mi := &file_sysManagement_button_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateButtonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateButtonReq) ProtoMessage() {}

func (x *UpdateButtonReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_button_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateButtonReq.ProtoReflect.Descriptor instead.
func (*UpdateButtonReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_button_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateButtonReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateButtonReq) GetButtonCode() string {
	if x != nil && x.ButtonCode != nil {
		return *x.ButtonCode
	}
	return ""
}

func (x *UpdateButtonReq) GetButtonName() string {
	if x != nil && x.ButtonName != nil {
		return *x.ButtonName
	}
	return ""
}

func (x *UpdateButtonReq) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateButtonReq) GetPagePath() string {
	if x != nil && x.PagePath != nil {
		return *x.PagePath
	}
	return ""
}

type ButtonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ButtonCode    string                 `protobuf:"bytes,2,opt,name=button_code,json=buttonCode,proto3" json:"button_code,omitempty"`
	ButtonName    string                 `protobuf:"bytes,3,opt,name=button_name,json=buttonName,proto3" json:"button_name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PagePath      string                 `protobuf:"bytes,5,opt,name=page_path,json=pagePath,proto3" json:"page_path,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonResp) Reset() {
	*x = ButtonResp{}
	mi := &file_sysManagement_button_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonResp) ProtoMessage() {}

func (x *ButtonResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_button_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonResp.ProtoReflect.Descriptor instead.
func (*ButtonResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_button_proto_rawDescGZIP(), []int{2}
}

func (x *ButtonResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ButtonResp) GetButtonCode() string {
	if x != nil {
		return x.ButtonCode
	}
	return ""
}

func (x *ButtonResp) GetButtonName() string {
	if x != nil {
		return x.ButtonName
	}
	return ""
}

func (x *ButtonResp) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ButtonResp) GetPagePath() string {
	if x != nil {
		return x.PagePath
	}
	return ""
}

func (x *ButtonResp) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ButtonResp) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListButtonResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ButtonResp          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListButtonResp) Reset() {
	*x = ListButtonResp{}
	mi := &file_sysManagement_button_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListButtonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListButtonResp) ProtoMessage() {}

func (x *ListButtonResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_button_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListButtonResp.ProtoReflect.Descriptor instead.
func (*ListButtonResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_button_proto_rawDescGZIP(), []int{3}
}

func (x *ListButtonResp) GetList() []*ButtonResp {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListButtonResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetButtonsByPagePathReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PagePath      string                 `protobuf:"bytes,1,opt,name=page_path,json=pagePath,proto3" json:"page_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetButtonsByPagePathReq) Reset() {
	*x = GetButtonsByPagePathReq{}
	mi := &file_sysManagement_button_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetButtonsByPagePathReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetButtonsByPagePathReq) ProtoMessage() {}

func (x *GetButtonsByPagePathReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_button_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetButtonsByPagePathReq.ProtoReflect.Descriptor instead.
func (*GetButtonsByPagePathReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_button_proto_rawDescGZIP(), []int{4}
}

func (x *GetButtonsByPagePathReq) GetPagePath() string {
	if x != nil {
		return x.PagePath
	}
	return ""
}

type GetUserButtonsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleIds       []int64                `protobuf:"varint,1,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserButtonsReq) Reset() {
	*x = GetUserButtonsReq{}
	mi := &file_sysManagement_button_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserButtonsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserButtonsReq) ProtoMessage() {}

func (x *GetUserButtonsReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_button_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserButtonsReq.ProtoReflect.Descriptor instead.
func (*GetUserButtonsReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_button_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserButtonsReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type BatchCheckPermissionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ButtonCodes   []string               `protobuf:"bytes,1,rep,name=button_codes,json=buttonCodes,proto3" json:"button_codes,omitempty"`
	RoleIds       []int64                `protobuf:"varint,2,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckPermissionReq) Reset() {
	*x = BatchCheckPermissionReq{}
	mi := &file_sysManagement_button_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckPermissionReq) ProtoMessage() {}

func (x *BatchCheckPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_button_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckPermissionReq.ProtoReflect.Descriptor instead.
func (*BatchCheckPermissionReq) Descriptor() ([]byte, []int) {
	return file_sysManagement_button_proto_rawDescGZIP(), []int{6}
}

func (x *BatchCheckPermissionReq) GetButtonCodes() []string {
	if x != nil {
		return x.ButtonCodes
	}
	return nil
}

func (x *BatchCheckPermissionReq) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type BatchCheckPermissionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       map[string]bool        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckPermissionResp) Reset() {
	*x = BatchCheckPermissionResp{}
	mi := &file_sysManagement_button_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckPermissionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckPermissionResp) ProtoMessage() {}

func (x *BatchCheckPermissionResp) ProtoReflect() protoreflect.Message {
	mi := &file_sysManagement_button_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckPermissionResp.ProtoReflect.Descriptor instead.
func (*BatchCheckPermissionResp) Descriptor() ([]byte, []int) {
	return file_sysManagement_button_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCheckPermissionResp) GetResults() map[string]bool {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_sysManagement_button_proto protoreflect.FileDescriptor

const file_sysManagement_button_proto_rawDesc = "" +
	"\n" +
	"\x1asysManagement/button.proto\x12\x1abasis.sysManagement.button\x1a\x13common/common.proto\"\xa7\x01\n" +
	"\x0fCreateButtonReq\x12\x1f\n" +
	"\vbutton_code\x18\x01 \x01(\tR\n" +
	"buttonCode\x12\x1f\n" +
	"\vbutton_name\x18\x02 \x01(\tR\n" +
	"buttonName\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\tpage_path\x18\x04 \x01(\tR\bpagePathB\x0e\n" +
	"\f_description\"\xf4\x01\n" +
	"\x0fUpdateButtonReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\vbutton_code\x18\x02 \x01(\tH\x00R\n" +
	"buttonCode\x88\x01\x01\x12$\n" +
	"\vbutton_name\x18\x03 \x01(\tH\x01R\n" +
	"buttonName\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x12 \n" +
	"\tpage_path\x18\x05 \x01(\tH\x03R\bpagePath\x88\x01\x01B\x0e\n" +
	"\f_button_codeB\x0e\n" +
	"\f_button_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_page_path\"\xdb\x01\n" +
	"\n" +
	"ButtonResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vbutton_code\x18\x02 \x01(\tR\n" +
	"buttonCode\x12\x1f\n" +
	"\vbutton_name\x18\x03 \x01(\tR\n" +
	"buttonName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tpage_path\x18\x05 \x01(\tR\bpagePath\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"b\n" +
	"\x0eListButtonResp\x12:\n" +
	"\x04list\x18\x01 \x03(\v2&.basis.sysManagement.button.ButtonRespR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"6\n" +
	"\x17GetButtonsByPagePathReq\x12\x1b\n" +
	"\tpage_path\x18\x01 \x01(\tR\bpagePath\".\n" +
	"\x11GetUserButtonsReq\x12\x19\n" +
	"\brole_ids\x18\x01 \x03(\x03R\aroleIds\"W\n" +
	"\x17BatchCheckPermissionReq\x12!\n" +
	"\fbutton_codes\x18\x01 \x03(\tR\vbuttonCodes\x12\x19\n" +
	"\brole_ids\x18\x02 \x03(\x03R\aroleIds\"\xb3\x01\n" +
	"\x18BatchCheckPermissionResp\x12[\n" +
	"\aresults\x18\x01 \x03(\v2A.basis.sysManagement.button.BatchCheckPermissionResp.ResultsEntryR\aresults\x1a:\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x012\x8a\x06\n" +
	"\x06Button\x12H\n" +
	"\tGetButton\x12\x13.basis.common.IdReq\x1a&.basis.sysManagement.button.ButtonResp\x12O\n" +
	"\n" +
	"ListButton\x12\x15.basis.common.PageReq\x1a*.basis.sysManagement.button.ListButtonResp\x12w\n" +
	"\x14GetButtonsByPagePath\x123.basis.sysManagement.button.GetButtonsByPagePathReq\x1a*.basis.sysManagement.button.ListButtonResp\x12k\n" +
	"\x0eGetUserButtons\x12-.basis.sysManagement.button.GetUserButtonsReq\x1a*.basis.sysManagement.button.ListButtonResp\x12V\n" +
	"\fCreateButton\x12+.basis.sysManagement.button.CreateButtonReq\x1a\x19.basis.common.SuccessResp\x12c\n" +
	"\fUpdateButton\x12+.basis.sysManagement.button.UpdateButtonReq\x1a&.basis.sysManagement.button.ButtonResp\x12>\n" +
	"\fDeleteButton\x12\x13.basis.common.IdReq\x1a\x19.basis.common.SuccessResp\x12\x81\x01\n" +
	"\x14BatchCheckPermission\x123.basis.sysManagement.button.BatchCheckPermissionReq\x1a4.basis.sysManagement.button.BatchCheckPermissionRespB8Z6td27/rpc/basis/types/sysManagement/button_pb;button_pbb\x06proto3"

var (
	file_sysManagement_button_proto_rawDescOnce sync.Once
	file_sysManagement_button_proto_rawDescData []byte
)

func file_sysManagement_button_proto_rawDescGZIP() []byte {
	file_sysManagement_button_proto_rawDescOnce.Do(func() {
		file_sysManagement_button_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sysManagement_button_proto_rawDesc), len(file_sysManagement_button_proto_rawDesc)))
	})
	return file_sysManagement_button_proto_rawDescData
}

var file_sysManagement_button_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sysManagement_button_proto_goTypes = []any{
	(*CreateButtonReq)(nil),          // 0: basis.sysManagement.button.CreateButtonReq
	(*UpdateButtonReq)(nil),          // 1: basis.sysManagement.button.UpdateButtonReq
	(*ButtonResp)(nil),               // 2: basis.sysManagement.button.ButtonResp
	(*ListButtonResp)(nil),           // 3: basis.sysManagement.button.ListButtonResp
	(*GetButtonsByPagePathReq)(nil),  // 4: basis.sysManagement.button.GetButtonsByPagePathReq
	(*GetUserButtonsReq)(nil),        // 5: basis.sysManagement.button.GetUserButtonsReq
	(*BatchCheckPermissionReq)(nil),  // 6: basis.sysManagement.button.BatchCheckPermissionReq
	(*BatchCheckPermissionResp)(nil), // 7: basis.sysManagement.button.BatchCheckPermissionResp
	nil,                              // 8: basis.sysManagement.button.BatchCheckPermissionResp.ResultsEntry
	(*common_pb.IdReq)(nil),          // 9: basis.common.IdReq
	(*common_pb.PageReq)(nil),        // 10: basis.common.PageReq
	(*common_pb.SuccessResp)(nil),    // 11: basis.common.SuccessResp
}
var file_sysManagement_button_proto_depIdxs = []int32{
	2,  // 0: basis.sysManagement.button.ListButtonResp.list:type_name -> basis.sysManagement.button.ButtonResp
	8,  // 1: basis.sysManagement.button.BatchCheckPermissionResp.results:type_name -> basis.sysManagement.button.BatchCheckPermissionResp.ResultsEntry
	9,  // 2: basis.sysManagement.button.Button.GetButton:input_type -> basis.common.IdReq
	10, // 3: basis.sysManagement.button.Button.ListButton:input_type -> basis.common.PageReq
	4,  // 4: basis.sysManagement.button.Button.GetButtonsByPagePath:input_type -> basis.sysManagement.button.GetButtonsByPagePathReq
	5,  // 5: basis.sysManagement.button.Button.GetUserButtons:input_type -> basis.sysManagement.button.GetUserButtonsReq
	0,  // 6: basis.sysManagement.button.Button.CreateButton:input_type -> basis.sysManagement.button.CreateButtonReq
	1,  // 7: basis.sysManagement.button.Button.UpdateButton:input_type -> basis.sysManagement.button.UpdateButtonReq
	9,  // 8: basis.sysManagement.button.Button.DeleteButton:input_type -> basis.common.IdReq
	6,  // 9: basis.sysManagement.button.Button.BatchCheckPermission:input_type -> basis.sysManagement.button.BatchCheckPermissionReq
	2,  // 10: basis.sysManagement.button.Button.GetButton:output_type -> basis.sysManagement.button.ButtonResp
	3,  // 11: basis.sysManagement.button.Button.ListButton:output_type -> basis.sysManagement.button.ListButtonResp
	3,  // 12: basis.sysManagement.button.Button.GetButtonsByPagePath:output_type -> basis.sysManagement.button.ListButtonResp
	3,  // 13: basis.sysManagement.button.Button.GetUserButtons:output_type -> basis.sysManagement.button.ListButtonResp
	11, // 14: basis.sysManagement.button.Button.CreateButton:output_type -> basis.common.SuccessResp
	2,  // 15: basis.sysManagement.button.Button.UpdateButton:output_type -> basis.sysManagement.button.ButtonResp
	11, // 16: basis.sysManagement.button.Button.DeleteButton:output_type -> basis.common.SuccessResp
	7,  // 17: basis.sysManagement.button.Button.BatchCheckPermission:output_type -> basis.sysManagement.button.BatchCheckPermissionResp
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_sysManagement_button_proto_init() }
func file_sysManagement_button_proto_init() {
	if File_sysManagement_button_proto != nil {
		return
	}
	file_sysManagement_button_proto_msgTypes[0].OneofWrappers = []any{}
	file_sysManagement_button_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sysManagement_button_proto_rawDesc), len(file_sysManagement_button_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sysManagement_button_proto_goTypes,
		DependencyIndexes: file_sysManagement_button_proto_depIdxs,
		MessageInfos:      file_sysManagement_button_proto_msgTypes,
	}.Build()
	File_sysManagement_button_proto = out.File
	file_sysManagement_button_proto_goTypes = nil
	file_sysManagement_button_proto_depIdxs = nil
}
